### ISSUE TITLE
Crash whenever I search "energy core"

### ISSUE THREAD

**Issue by fmate2006** [brandon3055/Draconic-Evolution#1092]
## Base information
* Minecraft version: 1.11.2
* Mod version: 2.2.5.271
* Minecraft Forge version: 13.20.1.2516
* Mod Pack: (if applicable)

## Crash report
```
16:04:28    game    [14:04:28] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:523]: ---- Minecraft Crash Report ----
16:04:28    game   
16:04:28    game    WARNING: coremods are present:
16:04:28    game    CoFH Loading Plugin (CoFH-Core-1.11.2.jar)
16:04:28    game    CCLCorePlugin (CodeChickenLib-1.11.2.jar)
16:04:28    game    TransformerLoader (OpenComputers-MC1.11.2-1.7.0.40.jar)
16:04:28    game    IC2core (Industrial-Craft-2-Mod-Experimental-1.11.2.jar)
16:04:28    game    Contact their authors BEFORE contacting forge
16:04:28    game   
16:04:28    game    // Why did you do that?
16:04:28    game   
16:04:28    game    Time: 4/14/18 2:04 PM
16:04:28    game    Description: Rendering item
16:04:28    game   
16:04:28    game    java.lang.IllegalStateException: Unable to compile VERTEX shader object:
16:04:28    game    Vertex shader failed to compile with the following errors:
16:04:28    game    at codechicken.lib.render.shader.ShaderObject.compileShader(ShaderObject.java:77)
16:04:28    game    at codechicken.lib.render.shader.ShaderProgram$$Lambda$421/891658483.accept(Unknown Source)
16:04:28    game    at java.lang.Iterable.forEach(Iterable.java:75)
16:04:28    game    at codechicken.lib.render.shader.ShaderProgram.useShader(ShaderProgram.java:123)
16:04:28    game    at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.bindShader(RenderItemEnergyCrystal.java:125)
16:04:28    game    at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.renderItem(RenderItemEnergyCrystal.java:96)
16:04:28    game    at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:85)
16:04:28    game    at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:155)
16:04:28    game    at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:219)
16:04:28    game    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
16:04:28    game    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
16:04:28    game    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
16:04:28    game    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:604)
16:04:28    game    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
16:04:28    game    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1119)
16:04:28    game    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1077)
16:04:28    game    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
16:04:28    game    at net.minecraft.client.main.Main.main(SourceFile:124)
16:04:28    game    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:04:28    game    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:04:28    game    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:04:28    game    at java.lang.reflect.Method.invoke(Method.java:483)
16:04:28    game    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
16:04:28    game    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
16:04:28    game   
16:04:28    game   
16:04:28    game    A detailed walkthrough of the error, its code path and all known details is as follows:
16:04:28    game    ---------------------------------------------------------------------------------------
16:04:28    game   
16:04:28    game    -- Head --
16:04:28    game    Thread: Client thread
16:04:28    game    Stacktrace:
16:04:28    game    at codechicken.lib.render.shader.ShaderObject.compileShader(ShaderObject.java:77)
16:04:28    game    at codechicken.lib.render.shader.ShaderProgram$$Lambda$421/891658483.accept(Unknown Source)
16:04:28    game    at java.lang.Iterable.forEach(Iterable.java:75)
16:04:28    game    at codechicken.lib.render.shader.ShaderProgram.useShader(ShaderProgram.java:123)
16:04:28    game    at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.bindShader(RenderItemEnergyCrystal.java:125)
16:04:28    game    at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.renderItem(RenderItemEnergyCrystal.java:96)
16:04:28    game    at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:85)
16:04:28    game    at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:155)
16:04:28    game   
16:04:28    game    -- Item being rendered --
16:04:28    game    Details:
16:04:28    game    Item Type: com.brandon3055.brandonscore.blocks.ItemBlockBCore@15d02b22
16:04:28    game    Item Aux: 0
16:04:28    game    Item NBT: null
16:04:28    game    Item Foil: false
16:04:28    game    Stacktrace:
16:04:28    game    at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:219)
16:04:28    game    at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:264)
16:04:28    game    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
16:04:28    game    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
16:04:28    game    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:604)
16:04:28    game    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
16:04:28    game   
16:04:28    game    -- Screen render details --
16:04:28    game    Details:
16:04:28    game    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
16:04:28    game    Mouse location: Scaled: (248, 137). Absolute: (744, 334)
16:04:28    game    Screen size: Scaled: (434, 249). Absolute: (1300, 746). Scale factor of 3
16:04:28    game   
16:04:28    game    -- Affected level --
16:04:28    game    Details:
16:04:28    game    Level name: MpServer
16:04:28    game    All players: 1 total; [EntityPlayerSP['fmate2006'/365, l='MpServer', x=3.96, y=80.00, z=73.99]]
16:04:28    game    Chunk stats: MultiplayerChunkCache: 531, 531
16:04:28    game    Level seed: 0
16:04:28    game    Level generator: ID 00 - default, ver 1. Features enabled: false
16:04:28    game    Level generator options:
16:04:28    game    Level spawn location: World: (-64,64,256), Chunk: (at 0,4,0 in -4,16; contains blocks -64,0,256 to -49,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
16:04:28    game    Level time: 283110 game time, 1000 day time
16:04:28    game    Level dimension: 0
16:04:28    game    Level storage version: 0x00000 - Unknown?
16:04:28    game    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
16:04:28    game    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
16:04:28    game    Forced entities: 92 total; [EntitySheep['Sheep'/512, l='MpServer', x=2.96, y=96.00, z=22.58], EntitySkeleton['Skeleton'/2433, l='MpServer', x=-5.50, y=23.00, z=142.50], EntityItem['item.item.egg'/3329, l='MpServer', x=-38.33, y=71.00, z=106.65], EntitySpider['Spider'/1666, l='MpServer', x=81.50, y=33.00, z=25.50], EntityEnderman['Enderman'/3334, l='MpServer', x=7.26, y=35.00, z=71.46], EntityEnderman['Enderman'/3335, l='MpServer', x=4.50, y=34.00, z=75.50], EntityCow['Cow'/264, l='MpServer', x=40.68, y=77.00, z=127.22], EntityZombie['Zombie'/3336, l='MpServer', x=10.50, y=34.00, z=73.50], EntitySheep['Sheep'/265, l='MpServer', x=43.28, y=77.00, z=124.39], EntityZombie['Zombie'/3337, l='MpServer', x=7.50, y=34.00, z=72.50], EntityCow['Cow'/266, l='MpServer', x=41.22, y=77.00, z=126.16], EntityLlama['Llama'/267, l='MpServer', x=36.35, y=74.00, z=136.89], EntityZombie['Zombie'/1547, l='MpServer', x=75.50, y=39.00, z=34.50], EntitySheep['Sheep'/268, l='MpServer', x=37.51, y=76.00, z=121.80], EntitySheep['Sheep'/269, l='MpServer', x=34.23, y=63.00, z=148.48], EntityBat['Bat'/2573, l='MpServer', x=80.07, y=31.89, z=38.64], EntityLlama['Llama'/270, l='MpServer', x=37.68, y=69.00, z=143.64], EntitySkeleton['Skeleton'/1678, l='MpServer', x=0.48, y=66.00, z=112.72], EntityLlama['Llama'/271, l='MpServer', x=36.52, y=73.00, z=137.89], EntitySheep['Sheep'/272, l='MpServer', x=32.44, y=71.00, z=137.45], EntitySheep['Sheep'/273, l='MpServer', x=39.23, y=75.00, z=134.48], EntitySpider['Spider'/2961, l='MpServer', x=-12.50, y=14.00, z=34.50], EntitySheep['Sheep'/274, l='MpServer', x=33.84, y=70.00, z=139.51], EntityLlama['Llama'/275, l='MpServer', x=47.49, y=75.00, z=144.89], EntityLlama['Llama'/276, l='MpServer', x=36.10, y=64.00, z=149.53], EntityCreeper['Creeper'/3353, l='MpServer', x=-28.50, y=37.00, z=124.50], EntityItem['item.item.egg'/1562, l='MpServer', x=-35.88, y=91.00, z=71.08], EntityCreeper['Creeper'/2460, l='MpServer', x=75.50, y=42.00, z=18.50], EntitySkeleton['Skeleton'/2719, l='MpServer', x=-21.50, y=65.00, z=46.50], EntityCreeper['Creeper'/3616, l='MpServer', x=-59.50, y=27.00, z=128.50], EntitySkeleton['Skeleton'/420, l='MpServer', x=80.50, y=32.00, z=-3.50], EntityBat['Bat'/2212, l='MpServer', x=-15.65, y=34.10, z=134.41], EntityBat['Bat'/421, l='MpServer', x=80.48, y=34.10, z=18.73], EntityBat['Bat'/2213, l='MpServer', x=-4.25, y=26.10, z=140.25], EntitySheep['Sheep'/296, l='MpServer', x=42.78, y=76.00, z=134.46], EntitySkeleton['Skeleton'/3624, l='MpServer', x=-64.50, y=17.00, z=137.50], EntityCow['Cow'/297, l='MpServer', x=51.02, y=76.00, z=129.10], EntitySkeleton['Skeleton'/3369, l='MpServer', x=22.50, y=31.00, z=26.50], EntityCreeper['Creeper'/3625, l='MpServer', x=-60.95, y=17.00, z=131.38], EntitySheep['Sheep'/298, l='MpServer', x=49.46, y=76.00, z=139.75], EntityZombie['Zombie'/3370, l='MpServer', x=24.50, y=31.00, z=25.50], EntityCreeper['Creeper'/3626, l='MpServer', x=-64.50, y=17.00, z=137.50], EntityCow['Cow'/299, l='MpServer', x=50.11, y=77.00, z=128.31], EntityZombie['Zombie'/2608, l='MpServer', x=81.50, y=32.00, z=21.28], EntityChicken['Chicken'/179, l='MpServer', x=-68.81, y=76.00, z=120.41], EntityChicken['Chicken'/180, l='MpServer', x=-65.27, y=73.00, z=128.90], EntitySpider['Spider'/2229, l='MpServer', x=49.50, y=30.00, z=47.50], EntityChicken['Chicken'/182, l='MpServer', x=-68.21, y=72.00, z=149.54], EntityZombie['Zombie'/2872, l='MpServer', x=-31.50, y=34.00, z=44.50], EntityChicken['Chicken'/187, l='MpServer', x=-51.61, y=77.00, z=105.43], EntitySkeleton['Skeleton'/2619, l='MpServer', x=55.50, y=25.00, z=140.50], EntityPlayerSP['fmate2006'/365, l='MpServer', x=3.96, y=80.00, z=73.99], EntityItem['item.item.egg'/704, l='MpServer', x=-51.13, y=77.00, z=105.89], EntityCreeper['Creeper'/577, l='MpServer', x=-71.50, y=25.00, z=-2.04], EntityCreeper['Creeper'/2626, l='MpServer', x=-16.50, y=40.00, z=66.50], EntityChicken['Chicken'/197, l='MpServer', x=-35.80, y=91.00, z=71.80], EntitySheep['Sheep'/198, l='MpServer', x=-37.48, y=81.00, z=90.45], EntitySheep['Sheep'/199, l='MpServer', x=-38.84, y=80.00, z=94.82], EntitySheep['Sheep'/200, l='MpServer', x=-41.68, y=80.00, z=95.24], EntitySheep['Sheep'/201, l='MpServer', x=-34.74, y=81.00, z=91.49], EntitySheep['Sheep'/202, l='MpServer', x=-44.50, y=87.00, z=81.81], EntityChicken['Chicken'/203, l='MpServer', x=-37.77, y=71.00, z=106.83], EntityBasalz['Basalz'/3275, l='MpServer', x=52.50, y=52.00, z=12.50], EntityChicken['Chicken'/204, l='MpServer', x=-43.19, y=72.00, z=110.85], EntityMinecartChest['Minecart with Chest'/460, l='MpServer', x=-52.50, y=29.06, z=54.50], EntityItem['item.item.egg'/205, l='MpServer', x=-43.48, y=72.00, z=111.11], EntityChicken['Chicken'/206, l='MpServer', x=-36.63, y=72.00, z=122.15], EntitySkeleton['Skeleton'/2894, l='MpServer', x=-65.50, y=30.00, z=64.50], EntityChicken['Chicken'/208, l='MpServer', x=-45.79, y=71.00, z=138.84], EntitySquid['Squid'/3543, l='MpServer', x=67.32, y=60.47, z=44.69], EntityBat['Bat'/2522, l='MpServer', x=54.68, y=42.81, z=27.40], EntitySkeleton['Skeleton'/222, l='MpServer', x=3.58, y=90.00, z=74.95], EntitySpider['Spider'/3042, l='MpServer', x=38.01, y=45.00, z=23.70], EntityMinecartChest['Minecart with Chest'/483, l='MpServer', x=-47.50, y=29.06, z=48.50], EntityCreeper['Creeper'/3555, l='MpServer', x=28.49, y=36.00, z=17.80], EntitySheep['Sheep'/484, l='MpServer', x=-37.30, y=93.00, z=58.49], EntitySheep['Sheep'/485, l='MpServer', x=-38.46, y=94.00, z=59.24], EntityBat['Bat'/3688, l='MpServer', x=84.75, y=33.06, z=34.50], EntitySheep['Sheep'/491, l='MpServer', x=-9.48, y=92.00, z=23.74], EntitySheep['Sheep'/492, l='MpServer', x=-3.48, y=93.00, z=17.80], EntityBat['Bat'/1644, l='MpServer', x=24.79, y=40.02, z=78.48], EntityCreeper['Creeper'/237, l='MpServer', x=0.82, y=76.00, z=91.51], EntitySkeleton['Skeleton'/2541, l='MpServer', x=38.50, y=30.00, z=29.50], EntitySheep['Sheep'/238, l='MpServer', x=5.80, y=78.00, z=152.67], EntitySkeleton['Skeleton'/2542, l='MpServer', x=36.51, y=30.00, z=26.78], EntityBat['Bat'/3182, l='MpServer', x=-5.84, y=40.96, z=30.36], EntityCreeper['Creeper'/2543, l='MpServer', x=71.50, y=13.00, z=94.50], EntityZombie['Zombie'/3063, l='MpServer', x=13.50, y=13.00, z=133.50], EntityZombie['Zombie'/3064, l='MpServer', x=13.50, y=13.00, z=135.50], EntitySkeleton['Skeleton'/3065, l='MpServer', x=13.50, y=13.00, z=134.50], EntityCreeper['Creeper'/2298, l='MpServer', x=24.50, y=45.00, z=130.50], EntityBat['Bat'/2172, l='MpServer', x=-45.48, y=29.33, z=40.64]]
16:04:28    game    Retry entities: 0 total; []
16:04:28    game    Server brand: fml,forge
16:04:28    game    Server type: Integrated singleplayer server
16:04:28    game    Stacktrace:
16:04:28    game    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
16:04:28    game    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
16:04:28    game    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
16:04:28    game    at net.minecraft.client.main.Main.main(SourceFile:124)
16:04:28    game    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:04:28    game    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
16:04:28    game    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
16:04:28    game    at java.lang.reflect.Method.invoke(Method.java:483)
16:04:28    game    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
16:04:28    game    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
16:04:28    game   
16:04:28    game    -- System Details --
16:04:28    game    Details:
16:04:28    game    Minecraft Version: 1.11.2
16:04:28    game    Operating System: Windows 7 (amd64) version 6.1
16:04:28    game    Java Version: 1.8.0_25, Oracle Corporation
16:04:28    game    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
16:04:28    game    Memory: 245321480 bytes (233 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
16:04:28    game    JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
16:04:28    game    IntCache: cache: 1, tcache: 1, allocated: 14, tallocated: 94
16:04:28    game    FML: MCP 9.38 Powered by Forge 13.20.1.2516 34 mods loaded, 34 mods active
16:04:28    game    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
16:04:28    game    UCHIJAAAA   minecraft{1.11.2} [Minecraft] (minecraft.jar)
16:04:28    game    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
16:04:28    game    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2516.jar)
16:04:28    game    UCHIJAAAA   forge{13.20.1.2516} [Minecraft Forge] (forge-1.11.2-13.20.1.2516.jar)
16:04:28    game    UCHIJAAAA   opencomputers|core{1.7.0.40} [OpenComputers (Core)] (minecraft.jar)
16:04:28    game    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
16:04:28    game    UCHIJAAAA   mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar)
16:04:28    game    UCHIJAAAA   codechickenlib{3.0.0.298} [CodeChicken Lib] (CodeChickenLib-1.11.2.jar)
16:04:28    game    UCHIJAAAA   cofhcore{4.2.5} [CoFH Core] (CoFH-Core-1.11.2.jar)
16:04:28    game    UCHIJAAAA   brandonscore{2.2.5} [Brandon's Core] (BrandonsCore-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildcraftlib{7.99.0} [BuildCraft Lib] (BuildCraft-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildcraftcore{7.99.0} [BuildCraft] (BuildCraft-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildcraftfactory{7.99.0} [BC Factory] (BuildCraft-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildcrafttransport{7.99.0} [BC Transport] (BuildCraft-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildcraftbuilders{7.99.0} [BC Builders] (BuildCraft-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildcraftenergy{7.99.0} [BC Energy] (BuildCraft-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildcraftrobotics{7.99.0} [BC Robotics] (BuildCraft-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildcraftsilicon{7.99.0} [BC Silicon] (BuildCraft-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   buildhelper{0.4.2} [Torojima's Build Helper] (BuildHelper-1.11.2.jar)
16:04:28    game    UCHIJAAAA   compactstorage{v2.0.0a} [CompactStorage] (Compact-Storage-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   ic2{2.7.81-ex111} [IndustrialCraft 2] (Industrial-Craft-2-Mod-Experimental-1.11.2.jar)
16:04:28    game    UCHIJAAAA   compactsolars{1.11.2-5.0.12.333} [Compact Solar Arrays] (CompactSolars-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   computercraft{1.80pr1} [ComputerCraft] (ComputerCraft-SquidDev-CC-ComputerCraft-feature-minecraft-1.11.2-1.80pr1-build0.jar)
16:04:28    game    UCHIJAAAA   thermalfoundation{2.2.3} [Thermal Foundation] (Thermal-Foundation-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   draconicevolution{2.2.5} [Draconic Evolution] (Draconic-Evolution-1.11.2-2.2.5.271-universal.jar)
16:04:28    game    UCHIJAAAA   energyconverters{1.0.1.22} [Energy Converters] (Energy-Converters-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   zerocore{1.11.2-0.1.1.0} [Zero CORE] (zerocore-1.11.2-0.1.1.0.jar)
16:04:28    game    UCHIJAAAA   bigreactors{1.11.2-0.4.5.41} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.41.jar)
16:04:28    game    UCHIJAAAA   ezstorage{2.4.1} [EZStorage 2] (EZStorage-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   opencomputers{1.7.0.40} [OpenComputers] (OpenComputers-MC1.11.2-1.7.0.40.jar)
16:04:28    game    UCHIJAAAA   projecte{1.11.2-PE1.0.0B} [ProjectE] (ProjectE-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   thermaldynamics{2.2.5} [Thermal Dynamics] (Thermal-Dynamics-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   thermalexpansion{5.2.5} [Thermal Expansion] (Thermal-Expansion-Mod-1.11.2.jar)
16:04:28    game    UCHIJAAAA   xaerominimap{1.13.5} [Xaero's Minimap] (Xaeros-Minimap-Mod-1.11.2.jar)
16:04:28    game    Loaded coremods (and transformers):
16:04:28    game    CoFH Loading Plugin (CoFH-Core-1.11.2.jar)
16:04:28    game    cofh.asm.CoFHClassTransformer
16:04:28    game    cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
16:04:28    game    CCLCorePlugin (CodeChickenLib-1.11.2.jar)
16:04:28    game    codechicken.lib.asm.ClassHierarchyManager
16:04:28    game    codechicken.lib.asm.CCL_ASMTransformer
16:04:28    game    TransformerLoader (OpenComputers-MC1.11.2-1.7.0.40.jar)
16:04:28    game    li.cil.oc.common.asm.ClassTransformer
16:04:28    game    IC2core (Industrial-Craft-2-Mod-Experimental-1.11.2.jar)
16:04:28    game   
16:04:28    game    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '3.3.11672 Compatibility Profile Context' Renderer: 'ATI Mobility Radeon HD 4500/5100 Series'
16:04:28    game    codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.:
16:04:28    game    Launched Version: 1.11.2-forge1.11.2-13.20.1.2516
16:04:28    game    LWJGL: 2.9.4
16:04:28    game    OpenGL: ATI Mobility Radeon HD 4500/5100 Series GL version 3.3.11672 Compatibility Profile Context, ATI Technologies Inc.
16:04:28    game    GL Caps: Using GL 1.3 multitexturing.
16:04:28    game    Using GL 1.3 texture combiners.
16:04:28    game    Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
16:04:28    game    Shaders are available because OpenGL 2.1 is supported.
16:04:28    game    VBOs are available because OpenGL 1.5 is supported.
16:04:28    game   
16:04:28    game    Using VBOs: Yes
16:04:28    game    Is Modded: Definitely; Client brand changed to 'fml,forge'
16:04:28    game    Type: Client (map_client.txt)
16:04:28    game    Resource Packs:
16:04:28    game    Current Language: English (US)
16:04:28    game    Profiler Position: N/A (disabled)
16:04:28    game    CPU: 4x Intel(R) Core(TM) i3 CPU M 330 @ 2.13GHz
16:04:28    game    [14:04:28] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:523]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Toshiba\AppData\Roaming\.minecraft\crash-reports\crash-2018-04-14_14.04.28-client.txt
```

**Comment by gigabit101** [comment]
Version is no longer supported.
