### ISSUE TITLE
Failed to download contributors list

### ISSUE THREAD

**Issue by phyyyl** [brandon3055/Draconic-Evolution#1113]
## Base information
* Minecraft version: 1.12.1
* Mod version: Draconic-Evolution-1.12-2.3.11.290-universal.jar
* Minecraft Forge version: 14.23.4.2705
* Mod Pack: custom

## Crash report
[Full log](https://gist.github.com/phyyyl/17895c97e0641edf19a0b51fa6e428c6)
```
[17:58:33] [main/INFO] [brandonscore]: Registering features for mod: draconicevolution
[17:58:33] [main/INFO] [brandonscore]: Registering feature renderers for mod: draconicevolution
[17:58:33] [main/INFO] [draconicevolution]: Finished PreInitialization
[17:58:33] [main/INFO] [FML]: OBJLoader: Domain draconicevolution has been added.
[17:58:33] [DE Contributors DL Thread/ERROR] [draconicevolution]: Failed to download contributors list
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: java.io.IOException: Server returned HTTP response code: 403 for URL: http://www.brandon3055.com/json/DEContributors.json
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at sun.net.www.protocol.http.HttpURLConnection.access$200(Unknown Source)
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at sun.net.www.protocol.http.HttpURLConnection$9.run(Unknown Source)
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at java.security.AccessController.doPrivileged(Native Method)
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at java.net.URL.openStream(Unknown Source)
[17:58:33] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: 	at com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread.run(ContributorHandler.java:165)
[17:58:34] [main/INFO] [draconicevolution]: Downloading Project Intelligence Mod Manifest...
```

**Comment by GreatOrator** [comment]
Double check, the link works fine when you open in a browser, it may have been local settings preventing it.

**Comment by gigabit101** [comment]
This happens some times with no real reason, This is not a issue as it still loads the list.
