### ISSUE TITLE
Use flux capacitor causing game crash

### ISSUE THREAD

**Issue by SeemWind** [brandon3055/Draconic-Evolution#1312]
## Base information
* Minecraft version:1.12.2
* Mod version:2.3.21.342
* Minecraft Forge version:14.23.5.2837
* Mod Pack: (if applicable)

## Crash report
```
CRASH REPORT HERE
```---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2019-05-11 12:52:28 CST
Description: Ticking player

java.lang.UnsupportedOperationException
    at java.util.AbstractList.add(AbstractList.java:148)
    at java.util.AbstractList.add(AbstractList.java:108)
    at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
    at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.updateEnergy(DraconiumCapacitor.java:212)
    at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.onUpdate(DraconiumCapacitor.java:195)
    at net.minecraft.item.ItemStack.updateAnimation(ItemStack.java:526)
    at net.minecraft.entity.player.InventoryPlayer.decrementAnimations(InventoryPlayer.java:363)
    at net.minecraft.entity.player.EntityPlayer.onLivingUpdate(EntityPlayer.java:511)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:234)
    at net.minecraft.entity.player.EntityPlayerMP.onUpdateEntity(EntityPlayerMP.java:382)
    at net.minecraft.network.NetHandlerPlayServer.update(NetHandlerPlayServer.java:173)
    at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.update(NetworkDispatcher.java:209)
    at net.minecraft.network.NetworkManager.processReceivedPackets(NetworkManager.java:285)
    at net.minecraft.network.NetworkSystem.networkTick(NetworkSystem.java:180)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:790)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Player being ticked --
  Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
  Entity ID: 77
  Entity Name: Like_Wind
  Entity's Exact location: -335.84, 4.00, -926.58
  Entity's Block location: World: (-336,4,-927), Chunk: (at 0,0,1 in -21,-58; contains blocks -336,0,-928 to -321,255,-913), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,Spawns:[],ForgeData:{PlayerPersisted:{OpenBlocks:{givenManual:1b},ftbutilities_starting_items:1b}},SleepTimer:0s,Attributes:[{Base:0.0d,Name:"enderio.aoe.xz"},{Base:0.0d,Name:"enderio.aoe.y"},{Base:0.0d,Name:"enderio.aoe.xyz"},{Base:20.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.10000000149011612d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:1.0d,Name:"generic.attackDamage"},{Base:4.0d,Name:"generic.attackSpeed"},{Base:0.0d,Name:"generic.luck"},{Base:5.0d,Name:"generic.reachDistance"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,abilities:{invulnerable:1b,mayfly:1b,instabuild:1b,walkSpeed:0.1f,mayBuild:1b,flying:0b,flySpeed:0.05f},FallDistance:0.0f,recipeBook:{},DeathTime:0s,XpSeed:253675733,ForgeCaps:{"openblocks:luck":0},XpTotal:0,playerGameType:1,seenCredits:0b,Motion:[0.0d,-0.0784000015258789d,0.0d],UUIDLeast:-5076422053633150638L,Health:20.0f,foodSaturationLevel:5.0f,HasSpawnDimensionSet:0b,Air:300s,OnGround:1b,Dimension:0,ForgeDataVersion:{minecraft:1343,mekanism:1,mekanismgenerators:1},Rotation:[187.8004f,14.849976f],XpLevel:0,UpdateBlocked:0b,Score:0,UUIDMost:-1338814959701176466L,Sleeping:0b,Pos:[-335.8446246466883d,4.0d,-926.5765908471592d],Fire:-20s,XpP:0.0f,EnderItems:[],DataVersion:1343,foodLevel:20,foodExhaustionLevel:0.0f,HurtTime:0s,SelectedItemSlot:0,Inventory:[{Slot:0b,id:"draconicevolution:draconium_capacitor",Count:1b,tag:{DEUpgrades:{rfCap:4b},Energy:768000000,Mode:3s},Damage:1s},{Slot:1b,ForgeCaps:{Parent:{Size:27,Items:[]}},id:"draconicevolution:draconic_staff_of_power",Count:1b,tag:{Energy:48000000,Profile_0:{showDigAOE:0b,digDepth:0,digSpeed:100,aoeSafeMode:0b,digAOE:0,attackAOE:2.0d,junkNbtSens:1b,enableJunkFilter:1b}},Damage:0s}],foodTickTimer:0}

-- Ticking connection --
  Connection: net.minecraft.network.NetworkManager@a24154d

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_191, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1325580232 bytes (1264 MB) / 2097152000 bytes (2000 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx2048m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2837 Optifine OptiFine_1.12.2_HD_U_E3 61 mods loaded, 61 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                | Version              | Source                                                            | Signature                                |
       |:------ |:--------------------------------- |:-------------------- |:----------------------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                         | 1.12.2               | minecraft.jar                                                     | None                                     |
       | LCHIJA | mcp                               | 9.42                 | minecraft.jar                                                     | None                                     |
       | LCHIJA | FML                               | 8.0.99.99            | forge-1.12.2-14.23.5.2837.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                             | 14.23.5.2837         | forge-1.12.2-14.23.5.2837.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | jecharacters                      | 1.12.0-3.3.0         | [JECh]通用拼音搜索-JustEnoughCharacters-1.12.0-3.3.0.jar                | None                                     |
       | LCHIJA | openmodscore                      | 0.12.2               | minecraft.jar                                                     | None                                     |
       | LCHIJA | foamfixcore                       | 7.7.4                | minecraft.jar                                                     | None                                     |
       | LCHIJA | inventorytweaks                   | 1.64+dev.146.2180b27 | []R键整理-InventoryTweaks-1.64+dev.146.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | wailaharvestability               | 1.1.12               | []Waila Harvestability-WailaHarvestability-mc1.12-1.1.12.jar      | None                                     |
       | LCHIJA | codechickenlib                    | 3.2.2.354            | [CCL]CodeChickenLib-CodeChickenLib-1.12.2-3.2.2.354-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | chickenchunks                     | 2.4.1.73             | []区块载入器-ChickenChunks-1.12.2-2.4.1.73-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | vanillafix                        | 1.0.10-SNAPSHOT      | []原版修复-VanillaFix-1.0.10-99.jar                                   | None                                     |
       | LCHIJA | chesttransporter                  | 2.8.8                | []搬箱器-ChestTransporter-1.12.2-2.8.8.jar                           | None                                     |
       | LCHIJA | ironchest                         | 1.12.2-7.0.54.838    | []更多箱子-ironchest-1.12.2-7.0.54.838.jar                            | None                                     |
       | LCHIJA | endercore                         | 1.12.2-0.5.45        | []末影核心-EnderCore-1.12.2-0.5.45.jar                                | None                                     |
       | LCHIJA | i18nmod                           | 1.12.2-1.0.8         | []自动汉化更新-i18nupdatemod-1.12.2-1.0.8.jar                           | None                                     |
       | LCHIJA | cookingforblockheads              | 6.4.65               | [CB]懒人厨房-CookingForBlockheads_1.12.2-6.4.65.jar                   | None                                     |
       | LCHIJA | redstoneflux                      | 2.1.0                | [前置]RedstoneFlux-1.12-2.1.0.6-universal.jar                       | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cofhcore                          | 4.6.2                | CoFHCore-1.12.2-4.6.2.25-universal.jar                            | None                                     |
       | LCHIJA | cofhworld                         | 1.3.0                | CoFHWorld-1.12.2-1.3.0.6-universal.jar                            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | thermalfoundation                 | 2.6.2                | [热力基本]ThermalFoundation-1.12.2-2.6.2.26-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | brandonscore                      | 2.4.10               | BrandonsCore-1.12.2-2.4.10.198-universal.jar                      | None                                     |
       | LCHIJA | draconicevolution                 | 2.3.21               | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar                | None                                     |
       | LCHIJA | thermalexpansion                  | 5.5.3                | [热力膨胀]ThermalExpansion-1.12.2-5.5.3.41-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | jei                               | 4.15.0.278           | jei_1.12.2-4.15.0.278.jar                                         | None                                     |
       | LCHIJA | enderio                           | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | enderiointegrationtic             | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | enderiobase                       | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | enderioconduits                   | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | enderioconduitsopencomputers      | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | refinedstorage                    | 1.6.14               | refinedstorage-1.6.14.jar                                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | enderioconduitsrefinedstorage     | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | enderiointegrationforestry        | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | enderiointegrationticlate         | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | ftblib                            | 5.4.1.99             | FTBLib-5.4.1.99.jar                                               | None                                     |
       | LCHIJA | enderiomachines                   | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | enderiopowertools                 | 5.0.40               | [EIO]末影接口-EnderIO-1.12.2-5.0.40.jar                               | None                                     |
       | LCHIJA | ftbutilities                      | 5.4.0.84             | [FTBU]FTB Utilities-FTBUtilities-5.4.0.84.jar                     | None                                     |
       | LCHIJA | blockdrops                        | 1.4.0                | [JEI]blockdrops-1.12.2-1.4.0.jar                                  | None                                     |
       | LCHIJA | jeresources                       | 0.8.5.27             | [JEI]JustEnoughResources-1.12.2-0.8.5.27.jar                      | None                                     |
       | LCHIJA | mcmultipart                       | 2.5.3                | [前置]MCMultiPart-2.5.3.jar                                         | None                                     |
       | LCHIJA | journeymap                        | 1.12.2-5.5.4         | [地图]journeymap-1.12.2-5.5.4.jar                                   | None                                     |
       | LCHIJA | thermaldynamics                   | 2.5.4                | [热动力学]ThermalDynamics-1.12.2-2.5.4.18-universal.jar               | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | fastbench                         | 1.7.1                | FastWorkbench-1.12.2-1.7.1.jar                                    | None                                     |
       | LCHIJA | foamfix                           | 0.10.5-1.12.2        | foamfix-0.10.5-1.12.2.jar                                         | None                                     |
       | LCHIJA | itemfilters                       | 1.0.3.12             | ItemFilters-1.0.3.12.jar                                          | None                                     |
       | LCHIJA | ftbquests                         | 1.5.2.151            | FTBQuests-1.5.2.151.jar                                           | None                                     |
       | LCHIJA | ftbbackups                        | 0.0.0.ftbbackups     | FTBUtilitiesBackups-1.0.0.3.jar                                   | None                                     |
       | LCHIJA | waila                             | 1.8.26               | Hwyla-1.8.26-B41_1.12.2.jar                                       | None                                     |
       | LCHIJA | harvestcraft                      | 1.12.2zb             | Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar       | None                                     |
       | LCHIJA | jehc                              | 1.6.3                | jehc-1.12.2-1.6.3.jar                                             | None                                     |
       | LCHIJA | mekanism                          | 1.12.2-1.2.0         | mekanica-1.12.2-1.2.0.jar                                         | None                                     |
       | LCHIJA | mekanismgenerators                | 1.12.2-1.2.0         | mekanica-generators-1.12.2-1.2.0.jar                              | None                                     |
       | LCHIJA | notenoughcodecs                   | 0.6                  | NotEnoughCodecs-0.6.jar                                           | None                                     |
       | LCHIJA | openmods                          | 0.12.2               | OpenModsLib-1.12.2-0.12.2.jar                                     | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                        | 1.8.1                | OpenBlocks-1.12.2-1.8.1.jar                                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | projectintelligence               | 1.0.5                | ProjectIntelligence-1.12.2-1.0.5.21-universal.jar                 | None                                     |
       | LCHIJA | refinedstorageaddons              | 0.4.4                | refinedstorageaddons-0.4.4.jar                                    | None                                     |
       | LCHIJA | torohealthmod                     | 1.12.2-11            | torohealth-1.12.2-11.jar                                          | None                                     |
       | LCHIJA | yabba                             | 1.1.2.45             | YABBA-1.1.2.45.jar                                                | None                                     |
  Loaded coremods (and transformers): JechCore ([JECh]通用拼音搜索-JustEnoughCharacters-1.12.0-3.3.0.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      VanillaFixLoadingPlugin ([]原版修复-VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      EnderCorePlugin ([]末影核心-EnderCore-1.12.2-0.5.45.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      Inventory Tweaks Coremod ([]R键整理-InventoryTweaks-1.64+dev.146.jar)
                                        invtweaks.forge.asm.ContainerTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Draconic Evolution (draconicevolution)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Like_Wind'/77, l='新的世界---', x=-335.84, y=4.00, z=-926.58]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by FoxMcloud5655** [comment]
Duplicate of #1294.
