### ISSUE TITLE
Draconic Flux Capacitor Crash

### ISSUE THREAD

**Issue by gamermachine404** [brandon3055/Draconic-Evolution#1323]
Draconic evolution ver:2.3.22.343
Brandons core ver:2.4.12.205
Redstone flux ver:2.1.0.6
Code chicken lib ver:3.2.2.353
Minecraft forge ver: 14.23.5.2768
forge mod loader ver: 8.0.99.99
mods that I use with draconic evolution: blockings mod ver: 6.0.1
Minecraft: 1.12.2

my game crash when I try to setup my draconic flux capacitor

either the games crashes or just stop working and I can't do anything in the game.

I where close to an energy core of tier 3 (draconic evolution) with a bit of power in it when the crash happened. there is also 5 or 6 generators, crystal to move the RF and im in creative with cheats activated.
when it crashes, it display this message:

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 6/6/19 4:46 PM
Description: Ticking player

java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.updateEnergy(DraconiumCapacitor.java:212)
	at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.func_77663_a(DraconiumCapacitor.java:195)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:344)
	at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.updateEnergy(DraconiumCapacitor.java:212)
	at com.brandon3055.draconicevolution.items.tools.DraconiumCapacitor.func_77663_a(DraconiumCapacitor.java:195)
	at net.minecraft.item.ItemStack.func_77945_a(ItemStack.java:526)
	at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:363)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:511)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2172)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 231
	Entity Name: CED2YOYO
	Entity's Exact location: 330.70, 80.00, 297.35
	Entity's Block location: World: (330,80,297), Chunk: (at 10,5,9 in 20,18; contains blocks 320,0,288 to 335,255,303), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@38640dd5
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Mac OS X (x86_64) version 10.13.6
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 813362240 bytes (775 MB) / 1375731712 bytes (1312 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 7 total; -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                | Version      | Source                                             | Signature                                |
	|:--------- |:----------------- |:------------ |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft         | 1.12.2       | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp               | 9.42         | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge             | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | blocklings        | 6.0.1        | Blocklings+6.0.1+-+1.12.2.jar                      | None                                     |
	| UCHIJAAAA | codechickenlib    | 3.2.2.353    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux      | 2.1.0        | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | brandonscore      | 2.4.12       | BrandonsCore-1.12.2-2.4.12.205-universal.jar       | None                                     |
	| UCHIJAAAA | draconicevolution | 2.3.22       | Draconic-Evolution-1.12.2-2.3.22.343-universal.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['CED2YOYO'/231, l='test', x=330.70, y=80.00, z=297.35]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

please help! I can't even play on my world and I worked so hard on it!

**Comment by gamermachine404** [comment]
ok I found with was wrong. I just needed to install Baubles

**Comment by gigabit101** [comment]
This issue has been fixed in the newest build
