### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by lebanni** [brandon3055/Draconic-Evolution#1334]
## Base information
MC 1.12.2
forge-1.12.2-14.23.5.2838-universal.jar
Draconic-Evolution-1.12.2-2.3.23.345-universal.jar
BrandonsCore-1.12.2-2.4.15.206-universal.jar

## Crash report
```
[crash-2019-07-07_12.30.33-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/3365512/crash-2019-07-07_12.30.33-server.txt)
```

**Comment by OneDollarMan** [comment]
Man I have the same problem!!! My versions of mode, forge and minecraft are similar (I was trying to downgrade version of draconic, but this doesn't help).

---- Minecraft Crash Report ----

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2838-7.1.7-RC3843.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 07.07.19 13:23
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Draconic Evolution (draconicevolution)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/entity/EntityPlayerSP
	at com.brandon3055.draconicevolution.client.DEParticles.registerServer(DEParticles.java:45)
	at com.brandon3055.draconicevolution.CommonProxy.registerParticles(CommonProxy.java:110)
	at com.brandon3055.draconicevolution.DraconicEvolution.preInit(DraconicEvolution.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$forgeImpl$PostEvent$zza000(LoadController.java:568)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.entity.EntityPlayerSP
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 40 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@4e8e8621 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 42 more
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 44 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjd000(MinecraftServer.java:4712)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjd000(MinecraftServer.java:4712)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_211, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1886265112 bytes (1798 MB) / 2537029632 bytes (2419 MB) up to 2537029632 bytes (2419 MB)
	JVM Flags: 2 total; -Xmx2560M -Xms2560M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 12 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	Mods:

	| State | ID                | Version                  | Source                                             | Signature                                |
	|:----- |:----------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft         | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | mcp               | 9.42                     | minecraft.jar                                      | None                                     |
	| LCH   | FML               | 8.0.99.99                | forge-1.12.2-14.23.5.2838-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge             | 14.23.5.2838             | forge-1.12.2-14.23.5.2838-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | spongeapi         | 7.1.0-e29ab849e          | spongeforge-1.12.2-2838-7.1.7-RC3843.jar           | None                                     |
	| LCH   | sponge            | 1.12.2-7.1.7-SNAPSHOT    | spongeforge-1.12.2-2838-7.1.7-RC3843.jar           | None                                     |
	| LCH   | spongeforge       | 1.12.2-2838-7.1.7-RC3843 | spongeforge-1.12.2-2838-7.1.7-RC3843.jar           | None                                     |
	| LCH   | baubles           | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | codechickenlib    | 3.2.2.353                | CodeChickenLib_1.12.2_3.2.2.353_universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux      | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | brandonscore      | 2.4.15                   | BrandonsCore-1.12.2-2.4.15.206-universal.jar       | None                                     |
	| LCE   | draconicevolution | 2.3.21                   | Draconic-Evolution-1.12.2-2.3.21.342-universal.jar | None                                     |


	Plugins:

	| State | ID | Version | Source | Signature |
	|:----- |:-- |:------- |:------ |:--------- |

	Loaded coremods (and transformers): 
SpongeCoremod (spongeforge-1.12.2-2838-7.1.7-RC3843.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by lebanni** [comment]
> Man I have the same problem!!! My versions of mode, forge and minecraft are similar (I was trying to downgrade version of draconic, but this doesn't help).
> 
Try setting
B:removeErroringEntities=true
and maybe 
B:removeErroringTileEntities=true
in forge.cfg after downgrading.

**Comment by brandon3055** [comment]
This has to be one of the most bizarre issues i have come across...
I have tracked down the cause and its an easy fix. But the code in question has not been touched since 2016 so wtf has it suddenly decided to break now?

**Comment by brandon3055** [comment]
Fixed. Please update BrandonsCore.
