### ISSUE TITLE
Player leaves the server

### ISSUE THREAD

**Issue by BMakkuro** [brandon3055/Draconic-Evolution#1349]
## Base information
MC 1.12.2
Draconic-Evolution-1.12.2-2.3.24.349-universal
BrandonsCore-1.12.2-2.4.17.208-universal
1.12.2-forge1.12.2-14.23.5.2838

## Crash report
```
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2019-08-18 00:11:30 JST
Description: Unexpected error

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at net.minecraft.client.audio.SoundManager.updateAllSounds(SoundManager.java:233)
    at net.minecraft.client.audio.SoundHandler.update(SoundHandler.java:293)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1858)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 2 total; [EntityPlayerSP['B_Makkuro'/512, l='MpServer', x=140.63, y=67.00, z=186.05], EntityOtherPlayerMP['Kren_'/544762, l='MpServer', x=140.10, y=67.14, z=183.70]]
  Chunk stats: MultiplayerChunkCache: 289, 289
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (120,64,196), Chunk: (at 8,4,4 in 7,12; contains blocks 112,0,192 to 127,255,207), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 3799355 game time, 3827223 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
  Forced entities: 86 total; [EntityOtherPlayerMP['Kren_'/541303, l='MpServer', x=141.11, y=67.00, z=183.43], EntityOtherPlayerMP['kotu244w'/514373, l='MpServer', x=139.65, y=69.94, z=178.81], EntityOtherPlayerMP['Kren_'/544762, l='MpServer', x=140.10, y=67.14, z=183.70], EntityVillager['村人'/6, l='MpServer', x=153.61, y=66.00, z=188.27], EntityVillager['村人'/7, l='MpServer', x=152.77, y=66.00, z=187.63], EntityVillager['村人'/8, l='MpServer', x=149.88, y=66.00, z=187.93], EntitySkeleton['スケルトン'/544768, l='MpServer', x=142.50, y=7.00, z=188.50], EntityVillager['村人'/9, l='MpServer', x=155.70, y=68.00, z=189.30], EntityBrainyZombie['怒れるゾンビ'/544769, l='MpServer', x=133.23, y=18.00, z=217.50], EntityVillager['村人'/10, l='MpServer', x=155.30, y=68.00, z=191.30], EntityBrainyZombie['怒れるゾンビ'/544770, l='MpServer', x=125.50, y=17.00, z=215.50], EntityVillager['村人'/11, l='MpServer', x=149.30, y=66.00, z=187.30], EntityChicken['ニワトリ'/651, l='MpServer', x=169.80, y=68.07, z=248.20], EntitySkeleton['スケルトン'/544771, l='MpServer', x=141.50, y=24.00, z=205.50], EntityVillager['村人'/12, l='MpServer', x=151.25, y=66.00, z=191.65], EntityCreeper['クリーパー'/544772, l='MpServer', x=80.50, y=64.00, z=170.50], EntityVillager['村人'/13, l='MpServer', x=149.48, y=66.00, z=191.30], EntityBat['コウモリ'/544773, l='MpServer', x=102.79, y=22.11, z=158.53], EntityVillager['村人'/14, l='MpServer', x=151.09, y=66.00, z=190.88], EntitySkeleton['スケルトン'/542598, l='MpServer', x=106.50, y=16.00, z=164.50], EntityVillager['村人'/15, l='MpServer', x=150.02, y=66.00, z=188.69], EntityVillager['村人'/16, l='MpServer', x=149.93, y=66.00, z=187.30], EntityVillager['村人'/17, l='MpServer', x=155.30, y=68.00, z=187.70], EntityItem['item.item.egg'/542233, l='MpServer', x=100.26, y=66.00, z=211.42], EntityPig['ブタ'/530, l='MpServer', x=79.49, y=63.00, z=126.21], EntityVillager['村人'/18, l='MpServer', x=151.92, y=66.00, z=191.01], EntityVillager['村人'/19, l='MpServer', x=153.70, y=66.00, z=187.30], EntityPig['ブタ'/531, l='MpServer', x=109.74, y=67.00, z=108.54], EntityPig['ブタ'/415, l='MpServer', x=117.74, y=66.00, z=193.61], EntityPig['ブタ'/416, l='MpServer', x=119.48, y=66.00, z=195.27], EntityItem['item.tile.cactus'/544168, l='MpServer', x=179.24, y=13.00, z=218.16], EntitySkeletonHorse['スケルトンホース'/417, l='MpServer', x=122.03, y=66.00, z=193.98], EntitySheep['ヒツジ'/545, l='MpServer', x=199.77, y=65.00, z=254.52], EntitySkeletonHorse['スケルトンホース'/418, l='MpServer', x=114.01, y=66.00, z=194.10], EntityOtherPlayerMP['WahrheitWeiss643'/541420, l='MpServer', x=211.51, y=6.19, z=199.43], EntityChicken['ニワトリ'/420, l='MpServer', x=100.68, y=66.00, z=211.17], EntityCreeper['クリーパー'/542508, l='MpServer', x=185.50, y=24.00, z=134.50], EntityPig['ブタ'/421, l='MpServer', x=101.45, y=66.00, z=214.45], EntityPig['ブタ'/422, l='MpServer', x=101.55, y=66.00, z=214.45], EntityPig['ブタ'/423, l='MpServer', x=101.55, y=66.00, z=215.55], EntityPig['ブタ'/424, l='MpServer', x=101.55, y=66.00, z=215.55], EntityPig['ブタ'/425, l='MpServer', x=101.45, y=66.00, z=215.55], EntityItem['item.item.egg'/540065, l='MpServer', x=101.88, y=66.00, z=210.29], EntityPig['ブタ'/426, l='MpServer', x=101.45, y=66.00, z=214.45], EntityCow['ウシ'/427, l='MpServer', x=105.36, y=66.00, z=215.42], EntitySheep['ヒツジ'/428, l='MpServer', x=103.45, y=66.00, z=211.45], EntitySheep['ヒツジ'/429, l='MpServer', x=104.52, y=66.00, z=212.51], EntityCow['ウシ'/430, l='MpServer', x=103.45, y=66.00, z=214.45], EntitySheep['ヒツジ'/431, l='MpServer', x=103.45, y=66.00, z=212.55], EntityCow['ウシ'/432, l='MpServer', x=104.46, y=66.00, z=216.37], EntityCow['ウシ'/433, l='MpServer', x=104.35, y=66.00, z=217.55], EntityChicken['ニワトリ'/434, l='MpServer', x=100.70, y=66.00, z=210.57], EntityCow['ウシ'/435, l='MpServer', x=106.36, y=66.00, z=217.55], EntityCow['ウシ'/436, l='MpServer', x=107.33, y=66.00, z=217.40], EntityCow['ウシ'/437, l='MpServer', x=107.26, y=66.00, z=214.45], EntityCow['ウシ'/438, l='MpServer', x=103.45, y=66.00, z=217.28], EntityCow['ウシ'/439, l='MpServer', x=104.44, y=66.00, z=215.42], EntityCow['ウシ'/440, l='MpServer', x=106.59, y=66.00, z=216.48], EntityCow['ウシ'/441, l='MpServer', x=105.30, y=66.00, z=217.28], EntityChicken['ニワトリ'/442, l='MpServer', x=100.78, y=66.00, z=209.82], EntityCow['ウシ'/443, l='MpServer', x=104.46, y=66.00, z=214.45], EntityCow['ウシ'/444, l='MpServer', x=105.62, y=66.00, z=216.32], EntityCow['ウシ'/445, l='MpServer', x=103.45, y=66.00, z=216.36], EntityCow['ウシ'/446, l='MpServer', x=107.55, y=66.00, z=216.49], EntityChicken['ニワトリ'/447, l='MpServer', x=101.16, y=66.00, z=211.69], EntityItem['item.tile.cactus'/542519, l='MpServer', x=183.63, y=13.00, z=210.80], EntityChicken['ニワトリ'/448, l='MpServer', x=100.20, y=66.00, z=211.17], EntityCow['ウシ'/449, l='MpServer', x=106.25, y=66.00, z=214.45], EntityItem['item.item.egg'/542537, l='MpServer', x=169.88, y=66.00, z=248.13], EntityCow['ウシ'/450, l='MpServer', x=103.45, y=66.00, z=215.35], EntityChicken['ニワトリ'/451, l='MpServer', x=101.55, y=66.00, z=211.17], EntityOtherPlayerMP['kotu244w'/542711, l='MpServer', x=139.65, y=69.94, z=178.81], EntityZombie['ゾンビ'/458, l='MpServer', x=143.25, y=63.50, z=226.38], EntityVillager['村人'/459, l='MpServer', x=142.70, y=74.00, z=234.30], EntityOtherPlayerMP['WahrheitWeiss643'/542855, l='MpServer', x=211.46, y=5.99, z=199.28], EntityPlayerSP['B_Makkuro'/512, l='MpServer', x=140.63, y=67.00, z=186.05], EntityCreeper['クリーパー'/539990, l='MpServer', x=105.50, y=55.00, z=162.50], EntityOtherPlayerMP['kotu244w'/542571, l='MpServer', x=139.65, y=69.94, z=178.81], EntityBat['コウモリ'/544738, l='MpServer', x=99.53, y=15.69, z=164.33], EntityCreeper['クリーパー'/543076, l='MpServer', x=124.50, y=17.00, z=214.50], EntityOtherPlayerMP['Kren_'/544762, l='MpServer', x=140.10, y=67.14, z=183.70], EntityOtherPlayerMP['kotu244w'/543589, l='MpServer', x=139.65, y=69.94, z=178.81], EntityOtherPlayerMP['kotu244w'/544742, l='MpServer', x=139.65, y=69.94, z=178.81], EntityBrainyZombie['怒れるゾンビ'/542588, l='MpServer', x=118.50, y=24.00, z=186.50], EntitySkeleton['スケルトン'/544764, l='MpServer', x=124.54, y=19.00, z=223.78], EntityPig['ブタ'/634, l='MpServer', x=66.81, y=71.00, z=263.69]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1918338368 bytes (1829 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
  FML: MCP 9.42 Powered by Forge 14.23.5.2838 Optifine OptiFine_1.12.2_HD_U_E3 78 mods loaded, 78 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                                          | Version                  | Source                                              | Signature                                |
       |:------ |:------------------------------------------- |:------------------------ |:--------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft                                   | 1.12.2                   | minecraft.jar                                       | None                                     |
       | LCHIJA | mcp                                         | 9.42                     | minecraft.jar                                       | None                                     |
       | LCHIJA | FML                                         | 8.0.99.99                | forge-1.12.2-14.23.5.2838.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                                       | 14.23.5.2838             | forge-1.12.2-14.23.5.2838.jar                       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | smoothfontcore                              | mc1.12.2-2.1             | minecraft.jar                                       | None                                     |
       | LCHIJA | openmodscore                                | 0.12.2                   | minecraft.jar                                       | None                                     |
       | LCHIJA | smoothfont                                  | mc1.12.2-2.1             | SmoothFont-mc1.12.2-2.1.jar                         | None                                     |
       | LCHIJA | net.minecraft.scalar.mineall.mod_mineallsmp | 2.6.5                    | [1.12][forge2413]mod_MineAllSMP_v2.6.5.zip          | None                                     |
       | LCHIJA | net.minecraft.rosettaenchanttable           | 0.0.9                    | [1.12][forge2413]mod_RosettaEnchantTable_v0.0.9.zip | None                                     |
       | LCHIJA | storagebox                                  | 3.2.0                    | [1.12][forge2413]mod_StorageBox_v3.2.0.zip          | None                                     |
       | LCHIJA | quarryplus                                  | 1.1.3                    | AdditionalEnchantedMiner-1.12.2-1.1.3-universal.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
       | LCHIJA | quarryplus_ct                               | 1.1.3                    | AdditionalEnchantedMiner-1.12.2-1.1.3-universal.jar | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
       | LCHIJA | backpack                                    | 3.0.2                    | backpack-3.0.2-1.12.2.jar                           | None                                     |
       | LCHIJA | baubles                                     | 1.5.2                    | Baubles-1.12-1.5.2.jar                              | None                                     |
       | LCHIJA | bedrocklayer                                | 1.2.4                    | BedrockLayer_1.11.2-v1.2.4.jar                      | None                                     |
       | LCHIJA | jei                                         | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                           | None                                     |
       | LCHIJA | thaumcraft                                  | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                    | None                                     |
       | LCHIJA | botania                                     | r1.10-361                | Botania+r1.10-361.jar                               | None                                     |
       | LCHIJA | codechickenlib                              | 3.2.3.357                | CodeChickenLib-1.12.2-3.2.3.357-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | redstoneflux                                | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | brandonscore                                | 2.4.17                   | BrandonsCore-1.12.2-2.4.17.208-universal.jar        | None                                     |
       | LCHIJA | buildcraftlib                               | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | buildcraftcore                              | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | buildcraftbuilders                          | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | buildcrafttransport                         | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | buildcraftsilicon                           | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | buildcraftenergy                            | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | ic2                                         | 2.8.170-ex112            | industrialcraft-2-2.8.170-ex112.jar                 | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | forestry                                    | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                       | None                                     |
       | LCHIJA | buildcraftcompat                            | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | buildcraftfactory                           | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | buildcraftrobotics                          | 7.99.24.2                | buildcraft-all-7.99.24.2.jar                        | None                                     |
       | LCHIJA | chickenchunks                               | 2.4.2.74                 | ChickenChunks-1.12.2-2.4.2.74-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | cofhcore                                    | 4.6.3                    | CoFHCore-1.12.2-4.6.3.27-universal.jar              | None                                     |
       | LCHIJA | cofhworld                                   | 1.3.1                    | CoFHWorld-1.12.2-1.3.1.7-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | cxlibrary                                   | 1.6.1                    | cxlibrary-1.12.1-1.6.1.jar                          | None                                     |
       | LCHIJA | thermalfoundation                           | 2.6.3                    | ThermalFoundation-1.12.2-2.6.3.27-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | draconicevolution                           | 2.3.24                   | Draconic-Evolution-1.12.2-2.3.24.349-universal.jar  | None                                     |
       | LCHIJA | endercore                                   | 1.12.2-0.5.65            | EnderCore-1.12.2-0.5.65.jar                         | None                                     |
       | LCHIJA | thermalexpansion                            | 5.5.4                    | ThermalExpansion-1.12.2-5.5.4.43-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
       | LCHIJA | enderio                                     | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderiointegrationtic                       | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderiobase                                 | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderioconduits                             | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderioconduitsappliedenergistics           | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderioconduitsopencomputers                | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | refinedstorage                              | 1.6.15                   | refinedstorage-1.6.15.jar                           | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | enderioconduitsrefinedstorage               | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderiointegrationforestry                  | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderiointegrationticlate                   | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderiomachines                             | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderiopowertools                           | 5.0.50                   | EnderIO-1.12.2-5.0.50.jar                           | None                                     |
       | LCHIJA | enderstorage                                | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | extrautils2                                 | 1.0                      | extrautils2-1.12-1.9.9.jar                          | None                                     |
       | LCHIJA | forgelin                                    | 1.8.3                    | Forgelin-1.8.3.jar                                  | None                                     |
       | LCHIJA | waila                                       | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                         | None                                     |
       | LCHIJA | mekanism                                    | 1.12.2-9.8.1.383         | Mekanism-1.12.2-9.8.1.383.jar                       | None                                     |
       | LCHIJA | teslacorelib                                | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | industrialforegoing                         | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar          | None                                     |
       | LCHIJA | inventorytweaks                             | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                            | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCHIJA | jeiintegration                              | 1.5.1.36                 | jeiintegration_1.12.2-1.5.1.36.jar                  | None                                     |
       | LCHIJA | journeymap                                  | 1.12.2-5.5.5             | journeymap-1.12.2-5.5.5.jar                         | None                                     |
       | LCHIJA | logisticspipes                              | 0.10.2.203               | logisticspipes-0.10.2.203.jar                       | e0c86912b2f7cc0cc646ad57799574aea43dbd45 |
       | LCHIJA | mekanismgenerators                          | 1.12.2-9.8.1.383         | MekanismGenerators-1.12.2-9.8.1.383.jar             | None                                     |
       | LCHIJA | mekanismtools                               | 1.12.2-9.8.1.383         | MekanismTools-1.12.2-9.8.1.383.jar                  | None                                     |
       | LCHIJA | morefurnaces                                | 1.10.5                   | More-Furnaces-Mod-1.12.2.jar                        | None                                     |
       | LCHIJA | multipagechest                              | 1.9.1                    | MultiPageChest-1.12-1.9.1.jar                       | None                                     |
       | LCHIJA | projectintelligence                         | 1.0.8                    | ProjectIntelligence-1.12.2-1.0.8.25-universal.jar   | None                                     |
       | LCHIJA | nei                                         | 2.4.3                    | NotEnoughItems-1.12.2-2.4.3.245-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | openmods                                    | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                       | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | openblocks                                  | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                         | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
       | LCHIJA | skyland                                     | 1.5.3                    | Skyland_1.12.2-v1.5.3.jar                           | None                                     |
       | LCHIJA | flammpfeil.slashblade                       | mc1.12-r28               | SlashBlade-mc1.12-r28.jar                           | None                                     |
       | LCHIJA | treecutter                                  | 1.0.5                    | TreeCutter_1.12-v1.0.5.jar                          | None                                     |
       | LCHIJA | twilightforest                              | 3.9.984                  | twilightforest-1.12.2-3.9.984-universal.jar         | None                                     |
       | LCHIJA | vanillafix                                  | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                            | None                                     |
       | LCHIJA | wailaharvestability                         | 1.1.12                   | WailaHarvestability-mc1.12-1.1.12.jar               | None                                     |
       | LCHIJA | teslacorelib_registries                     | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                    | None                                     |
  Loaded coremods (and transformers): ForgelinPlugin (Forgelin-1.8.3.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      MekanismCoremod (Mekanism-1.12.2-9.8.1.383.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.jar)
                                        bre.smoothfont.asm.Transformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
                                        openmods.core.OpenModsClassTransformer
                                      CXLibraryCore (cxlibrary-1.12.1-1.6.1.jar)
                                        cubex2.cxlibrary.CoreModTransformer
                                      LogisticsPipesCoreLoader (logisticspipes-0.10.2.203.jar)
                                        logisticspipes.asm.LogisticsClassTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.65-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 431.36' Renderer: 'GeForce RTX 2070/PCIe/SSE2'
  OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Unknown
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
  LWJGL: 2.9.4
  OpenGL: GeForce RTX 2070/PCIe/SSE2 GL version 4.6.0 NVIDIA 431.36, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: 日本語 (日本)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

```
Other players leave when using Fusion Crafting Core. I do not leave myself.

However, it does n’t seem to leave if you ’re in another dimension.

Sorry, I'm using a translation site

**Comment by FoxMcloud5655** [comment]
I can confirm this issue.  I think anything related to syncing tile entities crashes other players.  I've had this issue with Spawners and the Energy Core.

**Comment by BMakkuro** [comment]
Is there a fix or solution for this issue?

**Comment by FoxMcloud5655** [comment]
It was working before, so something must have changed somewhere for it not to work.  Yes, there is, but it hasn't been deduced yet!  I'll probably take a crack at it today.

**Comment by BMakkuro** [comment]
That means you can't do anything now?

**Comment by FoxMcloud5655** [comment]
That is correct.

**Comment by FoxMcloud5655** [comment]
Update: After testing with minimal mods, this issue does not appear to happen...  I'm beginning to think this is a mod conflict and not the fault of Draconic Evolution.  Going to try narrowing it down.

Between my modpack (Eternity 2) and BMakkuro's modpack, I'll create a new one that has mods that are in both of our packs and start testing further.

**Comment by FoxMcloud5655** [comment]
I do get a different error than posted above, though:
```
[10:30:00] [Netty Server IO #3/ERROR] [FML]: NetworkDispatcher exception
io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.UnpooledHeapByteBuf.array(UnpooledHeapByteBuf.java:154) ~[UnpooledHeapByteBuf.class:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.array(PacketBuffer.java:1264) ~[gy.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toS3FPackets(FMLProxyPacket.java:151) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:537) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [NioEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
```

**Comment by BMakkuro** [comment]
In other words ... Should I look for a competing mod and remove it?

**Comment by FoxMcloud5655** [comment]
Found the issue!  I hope this helps you as well...

CodeChickenLib recently (as of 08/06/19) updated, breaking compatibility with Draconic Evolution.  I believe the issue lies with the line of code located in `/lib/packet/PacketCustom.java` on line 217: `payload.release();`.  I'm forking the repo and building a custom build to see if this is in fact the issue.

**Comment by PonderPonPon** [comment]
I just made this account so I could leave this message.

My boyfriend and I put together a small modpack to play on LAN that included Draconic Evolution and Ender Storage. We were having issues with him disconnecting whenever interacting anything from either mod. He would get no errors, but my java console would display the same io.netty.util error you got.

Now after downgrading CodeChickenLib and Ender Storage both mods work perfectly.

After some testing we did find out that the error seems to only happen when playing on a LAN world, setting up a server with the same mods did not have the same issues. And whoever is the host seems to have no issues but the client disconnects with no error messages while the hosts console has the io.netty.util error.

I hope this was the right place to put this and I hope it helps in any way.

**Comment by BMakkuro** [comment]
Thank you all! Today or tomorrow, lower the mod version and play with friends. I will report here again soon! Sorry for the translated English!

**Comment by FoxMcloud5655** [comment]
@PonderPonPon That is exactly what I've concluded.  This issue can safely be closed, as I've already sent a pull request to the CodeChickenLib!

**Comment by BMakkuro** [comment]
Today I was able to play with my friends without any problems! I'm really thankful to you!
