### ISSUE TITLE
Spawner issue Player disconect

### ISSUE THREAD

**Issue by tretapolis-dev** [brandon3055/Draconic-Evolution#1357]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.24.349
* Minecraft Forge version: 14.23.5.2846
* Mod Pack: (if applicable) OWN

Once a spawner is placed and the soul is added, each local player gets a disconect at the host, there are no problems. If the spawner continues to work and a player joins, he immediately flies out again. Once the spawner is disabled with a lever or dismantled, the player can re-join and there are no more problems

Optifine also already disabled no change

Only this error message appears in the log (there is no crash log):

`[00:01:08] [Server thread/INFO] [minecraft/MinecraftServer]: Tschonsen123 left the game
[00:01:08] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] Tschonsen123 left the game
[00:01:27] [User Authenticator #10/INFO] [minecraft/NetHandlerLoginServer]: UUID of player Tschonsen123 is 8713bfbc-5080-4768-830b-3ccd08f5dbfb
[00:01:27] [Netty Server IO #19/INFO] [FML]: Client protocol version 2
[00:01:27] [Netty Server IO #19/INFO] [FML]: Client attempting to join with 128 mods : buildcraftlib@7.99.24.2,p455w0rdslib@2.2.156,enderiointegrationforestry@5.1.51,globalgamerules@2.2,openmods@0.12.2,rftools@7.72,buildcraftenergy@7.99.24.2,mtrm@1.2.2.30,cofhcore@4.6.3,draconicevolution@2.3.24,endercore@1.12.2-0.5.68,ctm@MC1.12.2-0.3.3.22,reauth@3.6.0,ae2stuff@0.7.0.4,bookshelf@2.3.585,forgelin@1.8.3,microblockcbe@2.6.2.83,malisisblocks@1.12.2-6.1.0,projectred-illumination@4.9.4.120,wct@3.12.93,cofhworld@1.3.1,sonarcore@5.0.19,waila@1.8.26,enderioconduitsrefinedstorage@5.1.51,galacticraftplanets@4.0.2.236,thaumcraft@6.1.BETA26,mcjtylib_ng@3.5.4,twilightforest@3.9.984,enderioconduits@5.1.51,malisisdoors@1.12.2-7.3.0,industrialforegoing@1.12.2-1.12.2,malisiscore@1.12.2-6.5.1-SNAPSHOT,unidict@1.12.2-2.9.2,aim@1.4.1,crafttweakerjei@2.0.3,enderiomachines@5.1.51,biomesoplenty@7.0.1.2441,redstoneflux@2.1.0,buildcraftsilicon@7.99.24.2,openmodscore@0.12.2,mychunkloader@1.12.2-01,aromabackup@2.1.1.4,autoswitch@5.6.2,energyconverters@1.3.0.15,teslacorelib_registries@1.0.15,projectred-core@4.9.4.120,ic2@2.8.1000,buildcraftbuilders@7.99.24.2,randomthings@4.2.7.3,buildcraftfactory@7.99.24.2,teslacorelib@1.0.15,projectred-transmission@4.9.4.120,FML@8.0.99.99,thermalexpansion@5.5.4,projectred-integration@4.9.4.120,rftoolsdim@5.71,enderiointegrationtic@5.1.51,aromabackuprecovery@2.1.1.4,thebombzenapi@2.9.3,enderioconduitsappliedenergistics@5.1.51,worldedit@6.1.10-SNAPSHOT,buildcraftcompat@7.99.24.2,computercraft@1.84.0,bigreactors@1.12.2-0.4.5.67,forgemultipartcbe@2.6.2.83,ic2-classic-spmod@0.0.0.0,customstartinggear@1.2.0,codechickenlib@3.2.3.357,buildcraftcore@7.99.24.2,wailaharvestability@1.1.12,cctweaked@1.84.0,ctgui@1.0.0,extracells@2.6.2,wft@1.0.1,ae2wtlib@1.0.30,jee@1.0.7,jei@4.15.0.268,buildcrafttransport@7.99.24.2,splan@2.65,thermalfoundation@2.6.3,bdlib@1.14.3.12,mcp@9.42,treecapitator@at_0.9,journeymap@1.12.2-5.5.5,appliedenergistics2@rv6-stable-7,enderiointegrationticlate@5.1.51,bno@1.12.2-1.0.4.0,aroma1997core@2.0.0.2,inventorytweaks@1.63+release.109.220f184,thutessentials@2.2.22,micdoodlecore@,crafttweaker@4.1.19,enderstorage@2.4.6.137,forge@14.23.5.2846,brandonscore@2.4.17,wpt@1.0.1,buildcraftrobotics@7.99.24.2,eplus@5.0.176,ironchest@1.12.2-7.0.67.844,openblocks@1.8.1,zerocore@1.12.2-0.1.2.8,minecraft@1.12.2,tconstruct@1.12.2-2.12.0.157,thermaldynamics@2.5.5,immersiveengineering@0.12-91,baubles@1.5.2,bspkrscore@at_0.9,enderiopowertools@5.1.51,signedit@1.12.2-4,enderio@5.1.51,extrautils2@1.0,mantle@1.12-1.3.3.55,fluxnetworks@3.0.19,galacticraftcore@4.0.2.236,mrtjpcore@2.1.4.43,playerstorage@1.3.11,wit@1.0.0,worldeditcuife2@2.1.2-mf-1.12.2-14.23.5.2768,enderiobase@5.1.51,wrcbe@2.3.2,wanionlib@1.12.2-2.2,chisel@MC1.12.2-0.2.1.35,minecraftmultipartcbe@2.6.2.83,enderioconduitsopencomputers@5.1.51,limelib@1.7.12,recipehandler@0.13,chiselsandbits@14.33,moreplanets@2.0.21
[00:01:27] [Netty Server IO #19/INFO] [CodeChickenLib-ConfigSync]: Skipping config sync, No mods have registered a syncable config.
[00:01:35] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[00:01:35] [Server thread/INFO] [minecraft/PlayerList]: Tschonsen123[/XXX.XXX.XXX:54093] logged in with entity id 1636080 at (121007.27326372244, 95.0, 122186.0756672999)
[00:01:35] [Server thread/INFO] [mcjtylib_ng]: SMP: Sync dimensions to client
[00:01:35] [Server thread/INFO] [minecraft/MinecraftServer]: Tschonsen123 joined the game
[00:01:35] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] Tschonsen123 joined the game
[00:01:35] [Server thread/INFO] [Waila]: Player GCEntityPlayerMP['Tschonsen123'/1636080, l='Multiplayer', x=121007.27, y=95.00, z=122186.08] connected. Sending ping
[00:01:35] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[00:01:35] [Server thread/INFO] [mcjtylib_ng]: SMP: Player logged in: Sync diminfo to clients
[00:01:35] [Server thread/INFO] [mcjtylib_ng]: Send dimlet rules to the client
[00:01:35] [Server thread/INFO] [mcjtylib_ng]: Rules packet size: 5779 of 8192
[00:01:55] [Server thread/INFO] [minecraft/MinecraftServer]: [Tschonsen123: Set own game mode to Creative Mode]
[00:02:46] [Client thread/INFO] [journeymap]: TileDrawStep.updateRegionTexture hit max count, 1000000
[00:02:47] [Client thread/INFO] [journeymap]: TileDrawStep.draw(low) hit max count, 1000000

[00:03:40] [Netty Server IO #19/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[MessageToByteEncoder.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:730) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:816) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:723) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:543) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[AbstractChannelHandlerContext.class:4.1.9.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[DefaultChannelPipeline.class:4.1.9.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[AbstractChannel.class:4.1.9.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:4.1.9.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [NioEventLoop.class:4.1.9.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:4.1.9.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1408) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.UnpooledHeapByteBuf.capacity(UnpooledHeapByteBuf.java:114) ~[UnpooledHeapByteBuf.class:4.1.9.Final]
	at io.netty.buffer.DuplicatedByteBuf.capacity(DuplicatedByteBuf.java:84) ~[DuplicatedByteBuf.class:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.capacity(PacketBuffer.java:434) ~[gy.class:?]
	at io.netty.buffer.UnsafeByteBufUtil.setBytes(UnsafeByteBufUtil.java:546) ~[UnsafeByteBufUtil.class:4.1.9.Final]
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:260) ~[PooledUnsafeDirectByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1069) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1060) ~[AbstractByteBuf.class:4.1.9.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1050) ~[AbstractByteBuf.class:4.1.9.Final]
	at net.minecraft.network.PacketBuffer.writeBytes(PacketBuffer.java:1094) ~[gy.class:?]
	at net.minecraft.network.play.server.SPacketCustomPayload.func_148840_b(SPacketCustomPayload.java:51) ~[iw.class:?]
	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:51) ~[ha.class:?]
	at net.minecraft.network.NettyPacketEncoder.encode(NettyPacketEncoder.java:12) ~[ha.class:?]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[MessageToByteEncoder.class:4.1.9.Final]
	... 18 more
[00:03:40] [Server thread/INFO] [minecraft/NetHandlerPlayServer]: Tschonsen123 lost connection: Internal Exception: io.netty.handler.codec.EncoderException: io.netty.util.IllegalReferenceCountException: refCnt: 0

[00:03:40] [Server thread/INFO] [minecraft/MinecraftServer]: Tschonsen123 left the game
[00:03:40] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] Tschonsen123 left the game`

**Comment by FoxMcloud5655** [comment]
This is not an issue with Draconic Evolution.  It's an issue with CodeChickenLib.  I've already submitted a pull request, and a new version of CodeChickenLib is on CurseForge (Twitch).

Update it, and your problem will be solved.

**Comment by tretapolis-dev** [comment]
Thanks :D
