### ISSUE TITLE
[1.7.10] crash of draconic evolution 1.0.2h with dragonApi v25c

### ISSUE THREAD

**Issue by OptimusZeGaming** [brandon3055/Draconic-Evolution#1411]
Hello 

I have just finished my modspack 1.7.10 but I have a problem with draconic evolution when I create a new map all is well I leave the map but when I come back on it crashes and according to the crash report it comes from draconic evolution I put the complete crash report attached. 

thank you for your help.

## Base information
* Minecraft version: 1.7.10
* Mod version: 1.7.10 draconic evolution 1.0.2h and dragon api v25c
* Minecraft Forge version: 1614
* Mod Pack: (if applicable)

## Crash report
```
CRASH REPORT HERE
```
Please note assuming the issue is a crash something like this

[crash-2020-04-12_21.50.25-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/4468713/crash-2020-04-12_21.50.25-server.txt)

```java.lang.ArrayIndexOutOfBoundsException: 1
	at Reika.DragonAPI.Auxiliary.Trackers.VersionTransitionTracker.loadCacheAndUpdate(VersionTransitionTracker.java:52)
	at Reika.DragonAPI.Auxiliary.Trackers.VersionTransitionTracker.onWorldLoad(VersionTransitionTracker.java:38)
	at Reika.DragonAPI.Auxiliary.DragonAPIEventWatcher.checkModChanges(DragonAPIEventWatcher.java:143)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_635_DragonAPIEventWatcher_checkModChanges_Load.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:73)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)```

**Comment by FoxMcloud5655** [comment]
Minecraft version 1.7.10 is no longer supported.

**Comment by OptimusZeGaming** [comment]
> La version 1.7.10 de Minecraft n'est plus prise en charge.

Yet it was recently updated

**Comment by FoxMcloud5655** [comment]
Not sure why you think that almost 4 years ago since the last update is recently updated...  But brandon3055 himself has said that Draconic Evolution for Minecraft version 1.7.10 is no longer supported.

MC 1.12.2 is getting bugfixes, but no new content; that's the only version that's currently being supported right now.

**Comment by OptimusZeGaming** [comment]
thanks for the help 

I'll pass on the bug to ReikaKalseki who made the DragonAPI mod.

> Je ne sais pas pourquoi vous pensez qu'il y a près de 4 ans depuis la dernière mise à jour, mais brandon3055 lui-même a déclaré que Draconic Evolution pour Minecraft version 1.7.10 n'était plus pris en charge.
> 
> MC 1.12.2 obtient des corrections de bogues, mais pas de nouveau contenu; c'est la seule version actuellement prise en charge.
> 
> Il semble également que DragonAPI soit à l'origine de l'accident, et non Draconic Evolution. Si vous allez commencer n'importe où, commencez par là!
thanks for the help 

I'll pass on the bug to ReikaKalseki who made the DragonAPI mod.
