### ISSUE TITLE
Crash. DE: Blocks and Items

### ISSUE THREAD

**Issue by Dimon22131** [brandon3055/Draconic-Evolution#1458]
## Base information
* Minecraft version: 1.12.2
* Mod version: 2.3.27.353
* Minecraft Forge version: 14.23.5.2854

## Crash report
```
CRASH REPORT HERE
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 9/12/20 4:56 PM
Description: 
CCL Has caught an exception whilst rendering an item.
  Item Class:     class com.brandon3055.brandonscore.blocks.ItemBlockBCore
  Registry Name:  draconicevolution:energy_crystal
  Metadata:       0
  NBT:            null
  Model Class:    class net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper$1
  Model Location: draconicevolution:energy_crystal#inventory
You can turn off player messages in the CCL config file.
If you want CCL to attempt to recover the game next time, enable it in the CCL config.


java.lang.RuntimeException: ShaderProgram validation has failed!
Fragment info
-------------
0(45) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
0(45) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable
0(45) : error C6013: Only arrays of texcoords may be indexed in this profile, and only with a loop index variable

	at codechicken.lib.render.shader.ShaderProgram.checkValidation(ShaderProgram.java:88)
	at codechicken.lib.render.shader.ShaderProgram.useShader(ShaderProgram.java:121)
	at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.bindShader(RenderItemEnergyCrystal.java:121)
	at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.renderItem(RenderItemEnergyCrystal.java:92)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)
	at codechicken.lib.render.item.CCRenderItem.func_191962_a(CCRenderItem.java:270)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:337)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at codechicken.lib.render.shader.ShaderProgram.checkValidation(ShaderProgram.java:88)
	at codechicken.lib.render.shader.ShaderProgram.useShader(ShaderProgram.java:121)
	at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.bindShader(RenderItemEnergyCrystal.java:121)
	at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.renderItem(RenderItemEnergyCrystal.java:92)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:207)

-- Item being rendered --
Details:
	Item Type: com.brandon3055.brandonscore.blocks.ItemBlockBCore@420cf372
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:188)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:343)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:265)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:98)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1457)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (177, 51). Absolute: (354, 426)
	Screen size: Scaled: (463, 265). Absolute: (925, 530). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Dimon22131'/85, l='MpServer', x=865.32, y=4.00, z=-383.69]]
	Chunk stats: MultiplayerChunkCache: 286, 286
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (867,4,-394), Chunk: (at 3,0,6 in 54,-25; contains blocks 864,0,-400 to 879,255,-385), Region: (1,-1; contains chunks 32,-32 to 63,-1, blocks 512,0,-512 to 1023,255,-1)
	Level time: 25385 game time, 25385 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Dimon22131'/85, l='MpServer', x=865.32, y=4.00, z=-383.69]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 193169704 bytes (184 MB) / 561758208 bytes (535 MB) up to 3203661824 bytes (3055 MB)
	JVM Flags: 3 total; -Xmn128M -Xmx3067M -XX:+UseConcMarkSweepGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F4 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                         | Version      | Source                                             | Signature                                |
	|:------ |:-------------------------- |:------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                  | 1.12.2       | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                        | 9.42         | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                      | 14.23.5.2854 | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | codechickenlib             | 3.2.2.353    | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux               | 2.1.1        | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | brandonscore               | 2.4.19       | BrandonsCore-1.12.2-2.4.19.214-universal.jar       | None                                     |
	| LCHIJA | draconicevolution          | 2.3.27       | Draconic-Evolution-1.12.2-2.3.27.353-universal.jar | None                                     |
	| LCHIJA | solarflux                  | 12.3.7       | solarfluxreborn_1.12.2_12.3.7.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
	| LCHIJA | tlauncher_custom_cape_skin | 1.4          | tlskincape_1.12.2-1.4.jar                          | None                                     |

	Loaded coremods (and transformers): 
TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '2.1.2' Renderer: 'GeForce 7600 GS/PCIe/SSE2'
	Launched Version: ForgeOptiFine 1.12.2
	LWJGL: 2.9.4
	OpenGL: GeForce 7600 GS/PCIe/SSE2 GL version 2.1.2, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) 4 CPU 3.06GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_F4
	OptiFine Build: 20191023-234904
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 2.1.2
	OpenGlRenderer: GeForce 7600 GS/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 2
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
You are using OptiFine.  Disable shaders in the config.

**Comment by Dimon22131** [comment]
I'm don't use shaders

**Comment by covers1624** [comment]
Yeah, brandon needs to not use things from gl versions that arent supported. Your gpu is really old, try updating your drivers.

**Comment by Dimon22131** [comment]
Okay, i will update the driver.

**Comment by Dimon22131** [comment]
P.S. I'm ukrainian

**Comment by Dimon22131** [comment]
Ok, I updated the driver
