### ISSUE TITLE
Minecraft crashes when I activate the draconic core.

### ISSUE THREAD

**Issue by maximusthezorua** [brandon3055/Draconic-Evolution#1464]
## Base information
* Minecraft version: 1.12.2
* Mod version: Draconic-Evolution-1.12.2-2.3.27.353-universal
* Minecraft Forge version: 1.12.2-forge1.12.2-14.23.5.2847
* Mod Pack: (if applicable) 

## Crash report
```
CRASH REPORT HERE

---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 9/30/20 8:55 PM
Description: Ticking block entity

net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToAccessFieldException: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: soundName
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:210)
	at com.brandon3055.draconicevolution.lib.DESoundHandler.playSoundFromServer(DESoundHandler.java:95)
	at com.brandon3055.draconicevolution.lib.DESoundHandler.playSoundFromServer(DESoundHandler.java:90)
	at com.brandon3055.draconicevolution.blocks.reactor.tileentity.TileReactorCore.checkBlockIntrusions(TileReactorCore.java:719)
	at com.brandon3055.draconicevolution.blocks.reactor.tileentity.TileReactorCore.updateCoreLogic(TileReactorCore.java:234)
	at com.brandon3055.draconicevolution.blocks.reactor.tileentity.TileReactorCore.func_73660_a(TileReactorCore.java:151)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)
Caused by: net.minecraftforge.fml.relauncher.ReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: soundName
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:166)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:206)
	... 12 more
Caused by: java.lang.NoSuchFieldException: soundName
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at net.minecraftforge.fml.relauncher.ReflectionHelper.findField(ReflectionHelper.java:160)
	... 13 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.relauncher.ReflectionHelper.getPrivateValue(ReflectionHelper.java:210)
	at com.brandon3055.draconicevolution.lib.DESoundHandler.playSoundFromServer(DESoundHandler.java:95)
	at com.brandon3055.draconicevolution.lib.DESoundHandler.playSoundFromServer(DESoundHandler.java:90)
	at com.brandon3055.draconicevolution.blocks.reactor.tileentity.TileReactorCore.checkBlockIntrusions(TileReactorCore.java:719)
	at com.brandon3055.draconicevolution.blocks.reactor.tileentity.TileReactorCore.updateCoreLogic(TileReactorCore.java:234)
	at com.brandon3055.draconicevolution.blocks.reactor.tileentity.TileReactorCore.func_73660_a(TileReactorCore.java:151)

-- Block entity being ticked --
Details:
	Name: draconicevolution:reactor_core // com.brandon3055.draconicevolution.blocks.reactor.tileentity.TileReactorCore
	Block type: ID #295 (tile.draconicevolution:reactor_core // com.brandon3055.draconicevolution.blocks.reactor.ReactorCore // draconicevolution:reactor_core)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-486,244,1057), Chunk: (at 10,15,1 in -31,66; contains blocks -496,0,1056 to -481,255,1071), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Actual block type: ID #295 (tile.draconicevolution:reactor_core // com.brandon3055.draconicevolution.blocks.reactor.ReactorCore // draconicevolution:reactor_core)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: Copy of New World
	All players: 1 total; [GCEntityPlayerMP['maximusthezorua'/44, l='Copy of New World', x=-483.54, y=245.29, z=1063.29]]
	Chunk stats: ServerChunkCache: 441 Drop: 0
	Level seed: 147371767942160069
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 3;230*minecraft:stone,5*minecraft:dirt,minecraft:grass;3;biome_1,decoration,stronghold,mineshaft,dungeon
	Level spawn location: World: (-495,4,1063), Chunk: (at 1,0,7 in -31,66; contains blocks -496,0,1056 to -481,255,1071), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Level time: 14040 game time, 14040 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 22557 (now: true), thunder time: 9642 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 450941744 bytes (430 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                | Version         | Source                                                | Signature                                |
	|:------ |:--------------------------------- |:--------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                         | 1.12.2          | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                               | 9.42            | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                               | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
	| LCHIJA | forge                             | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
	| LCHIJA | micdoodlecore                     |                 | minecraft.jar                                         | None                                     |
	| LCHIJA | opencomputers|core                | 1.7.5.192       | minecraft.jar                                         | None                                     |
	| LCHIJA | bdlib                             | 1.14.3.12       | bdlib-1.14.3.12-mc1.12.2.jar                          | None                                     |
	| LCHIJA | codechickenlib                    | 3.2.3.358       | CodeChickenLib-1.12.2-3.2.3.358-universal.jar         | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux                      | 2.1.1           | RedstoneFlux-1.12-2.1.1.1-universal.jar               | None                                     |
	| LCHIJA | brandonscore                      | 2.4.19          | BrandonsCore-1.12.2-2.4.19.214-universal.jar          | None                                     |
	| LCHIJA | cctweaked                         | 1.88.0          | cc-tweaked-1.12.2-1.88.0.jar                          | None                                     |
	| LCHIJA | computercraft                     | 1.88.0          | cc-tweaked-1.12.2-1.88.0.jar                          | None                                     |
	| LCHIJA | cofhcore                          | 4.6.6           | CoFHCore-1.12.2-4.6.6.1-universal.jar                 | None                                     |
	| LCHIJA | cofhworld                         | 1.4.0           | CoFHWorld-1.12.2-1.4.0.1-universal.jar                | None                                     |
	| LCHIJA | thermalfoundation                 | 2.6.7           | ThermalFoundation-1.12.2-2.6.7.1-universal.jar        | None                                     |
	| LCHIJA | draconicevolution                 | 2.3.19          | Draconic-Evolution-1.12.2-2.3.19.330-universal.jar    | None                                     |
	| LCHIJA | endercore                         | 1.12.2-0.5.76   | EnderCore-1.12.2-0.5.76.jar                           | None                                     |
	| LCHIJA | thermalexpansion                  | 5.5.7           | ThermalExpansion-1.12.2-5.5.7.1-universal.jar         | None                                     |
	| LCHIJA | enderio                           | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderiointegrationtic             | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderiobase                       | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderioconduits                   | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderioconduitsappliedenergistics | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | opencomputers                     | 1.7.5.192       | OpenComputers-MC1.12.2-1.7.5.192.jar                  | None                                     |
	| LCHIJA | enderioconduitsopencomputers      | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderioconduitsrefinedstorage     | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderiointegrationforestry        | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderiointegrationticlate         | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderiomachines                   | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | enderiopowertools                 | 5.2.60          | EnderIO-1.12.2-5.2.60.jar                             | None                                     |
	| LCHIJA | zerocore                          | 1.12.2-0.1.2.8  | zerocore-1.12.2-0.1.2.8.jar                           | None                                     |
	| LCHIJA | bigreactors                       | 1.12.2-0.4.5.67 | ExtremeReactors-1.12.2-0.4.5.67.jar                   | None                                     |
	| LCHIJA | fluxnetworks                      | 4.0.14          | fluxnetworks-1.12.2-4.0.14-31.jar                     | None                                     |
	| LCHIJA | galacticraftcore                  | 4.0.2.238       | GalacticraftCore-1.12.2-4.0.2.238.jar                 | None                                     |
	| LCHIJA | galacticraftplanets               | 4.0.2.238       | Galacticraft-Planets-1.12.2-4.0.2.238.jar             | None                                     |
	| LCHIJA | nuclearcraft                      | 2.18x           | NuclearCraft-2.18x-1.12.2.jar                         | None                                     |
	| LCHIJA | pressure                          | 1.3.1.6         | pressure-1.3.1.6-mc1.12.1.jar                         | None                                     |
	| LCHIJA | projectintelligence               | 1.0.9           | ProjectIntelligence-1.12.2-1.0.9.28-universal (1).jar | None                                     |
	| LCHIJA | thermaldynamics                   | 2.5.6           | ThermalDynamics-1.12.2-2.5.6.1-universal.jar          | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.238.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/Austin/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	List of loaded APIs: 
		* bigreactors|API (4.0.1) from ExtremeReactors-1.12.2-0.4.5.67.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.6.1-universal.jar
		* ComputerCraft|API (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|FileSystem (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Lua (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Media (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Network (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Network|Wired (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Peripheral (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Permissions (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Redstone (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Turtle (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* ComputerCraft|API|Turtle|Event (1.88.0) from cc-tweaked-1.12.2-1.88.0.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.19.330-universal.jar
		* enderioapi (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* enderioapi|addon (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* enderioapi|capacitor (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* enderioapi|conduits (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* enderioapi|farm (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* enderioapi|redstone (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* enderioapi|teleport (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* enderioapi|tools (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* enderioapi|upgrades (4.0.0) from EnderIO-1.12.2-5.2.60.jar
		* Galacticraft API (1.3) from GalacticraftCore-1.12.2-4.0.2.238.jar
		* opencomputersapi|component (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|core (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|driver (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|driver|item (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|event (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|filesystem (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|internal (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|machine (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|manual (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|network (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* opencomputersapi|prefab (7.0.0-alpha) from OpenComputers-MC1.12.2-1.7.5.192.jar
		* pressureAPI (1.3.1.6) from pressure-1.3.1.6-mc1.12.1.jar
		* redstonefluxapi (2.1.1) from RedstoneFlux-1.12-2.1.1.1-universal.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.8.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.8.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.8.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12.2-0.1.2.8.jar
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [GCEntityPlayerMP['maximusthezorua'/44, l='Copy of New World', x=-483.54, y=245.29, z=1063.29]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```
Please note assuming the issue is a crash something like this

```Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Some Mod```

Is NOT a crash report!</br>
Attach the crash report as a txt file to your issue or use a link service like pastebin.</br>

I need the full crash report which you can find in the crash-reports folder in the minecraft folder.</br>
Failing that please give me your entire minecraft log from the session when the crash occurred.</br>
If you do not provide these your issue will be insta-closed.

**Comment by FoxMcloud5655** [comment]
Your version of CodeChickenLib is out of date.  Update to build 378.

**Comment by maximusthezorua** [comment]
I'll see if that works

**Comment by maximusthezorua** [comment]
Still crashes.

**Comment by maximusthezorua** [comment]
> Your version of CodeChickenLib is out of date. Update to build 378.

Still crashes

**Comment by maximusthezorua** [comment]
Works now. just had to remove a mod

**Comment by maximusthezorua** [comment]
Works now. just had to remove a mod
