### ISSUE TITLE
Energy Pylon and AE2 P2P crash

### ISSUE THREAD

**Issue by TheRealPhyton** [brandon3055/Draconic-Evolution#1505]
[crash-2021-06-08_01.06.28-server.txt](https://github.com/brandon3055/Draconic-Evolution/files/6612482/crash-2021-06-08_01.06.28-server.txt)

Extracting energy from the Energy Pylons with P2P AE2 crashes everything. Sometimes it works fine, at random moments it crashes. The power for keeping up the AE2 ME is on another Energy Pylon

**Comment by FoxMcloud5655** [comment]
This is an AE2 problem.
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.remove(Unknown Source)
	at appeng.me.cache.EnergyGridCache.extractProviderPower(EnergyGridCache.java:316)
	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:248)
	at appeng.parts.p2p.PartP2PTunnel.queueTunnelDrain(PartP2PTunnel.java:407)
	at appeng.parts.p2p.PartP2PFEPower$InputEnergyStorage.receiveEnergy(PartP2PFEPower.java:146)
	at com.brandon3055.brandonscore.lib.EnergyHelper.insertEnergy(EnergyHelper.java:110)
	at com.brandon3055.brandonscore.blocks.TileEnergyBase.sendEnergyTo(TileEnergyBase.java:130)
	at com.brandon3055.brandonscore.blocks.TileEnergyBase.sendEnergyToAll(TileEnergyBase.java:138)
	at com.brandon3055.draconicevolution.blocks.tileentity.TileEnergyPylon.func_73660_a(TileEnergyPylon.java:69)
```
This references AE2 first, though it may be something that DE could fix via something hacky.

**Comment by brandon3055** [comment]
As fox said this looks like an AE issue. There isn't really much I can do to fix this because all I am doing is inserting energy the same way any other mod would.
