### ISSUE TITLE
[1.16.5] Crash when Digging Out Tool/Weapon

### ISSUE THREAD

**Issue by FoxMcloud5655** [brandon3055/Draconic-Evolution#1580]
## Base information
* Minecraft version: 1.16.5
* Mod version: 3.0.17.420 (with custom CC support from this repo, but it doesn't affect this crash)
* Minecraft Forge version: 36.2.16
* Mod Pack: Duality: Tech & Magic (search for Duality)

### Crash report
There's not a crash report, but here's the relevant part of the log file:
```
Caused by: java.lang.NullPointerException
at com.brandon3055.draconicevolution.api.modules.lib.ModuleHostImpl.serializeNBT(ModuleHostImpl.java:295) ~[draconicevolution:1.16.5-3.0.17.424] {re:classloading}
at com.brandon3055.draconicevolution.api.modules.lib.ModuleHostImpl.serializeNBT(ModuleHostImpl.java:34) ~[draconicevolution:1.16.5-3.0.17.424] {re:classloading}
at com.brandon3055.brandonscore.capability.MultiCapabilityProvider.lambda$serializeNBT$1(MultiCapabilityProvider.java:57) ~[brandonscore:1.16.5-3.0.11.238] {re:classloading}
at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_292] {}
at com.brandon3055.brandonscore.capability.MultiCapabilityProvider.serializeNBT(MultiCapabilityProvider.java:57) ~[brandonscore:1.16.5-3.0.11.238] {re:classloading}
at com.brandon3055.brandonscore.capability.MultiCapabilityProvider.serializeNBT(MultiCapabilityProvider.java:20) ~[brandonscore:1.16.5-3.0.11.238] {re:classloading}
```

### Description / steps to reproduce

I have no idea what's causing this crash, but I'm pretty sure it happened due to a Wyvern Pickaxe or a Draconic Chest Piece, or maybe a combination of the two.  I hope this isn't a mod compat problem, as this would be pretty hard to track down.  Some players crashed, while others did not.  I'm pretty sure that's due to a race condition.

We had about 5 people in the spawn area for a quick event when someone brandished their Wyvern Pickaxe.  They were wearing a Draconic Chest Piece at the time as well, but when they dug out their pick, everyone around them, including them, crashed.  One person didn't, but I think that was due to laggy internet so he didn't get the update in time for the crash to happen.

**Comment by FoxMcloud5655** [comment]
I've now confirmed that it does require the presence of other players nearby.  I've had it happen with as few as 3 players nearby; maybe it has something to do with another modded item?  I'm not sure.  More testing is required.

**Comment by brandon3055** [comment]
This should be fixed in the latest release but will leave this issue open until I know for sure,

**Comment by FoxMcloud5655** [comment]
This issue is definitely been fixed in the latest release.  Closing the issue now...
