### ISSUE TITLE
Chaos Island Generation Crashes Server and No Dragon on Restart

### ISSUE THREAD

**Issue by KaPowXD** [brandon3055/Draconic-Evolution#19]
Sorry for the txt dump here, not sure where to put crash logs.
As soon as i generate a chaos island the server crashes. Upon restart the island is there and intact but with no dragon. please help!

---- Minecraft Crash Report ----
// I feel sad now :(

Time: 3/3/15 2:45 AM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.entity.item.EntityEnderCrystal.<init>(Lnet/minecraft/world/World;DDD)V
	at com.brandon3055.draconicevolution.common.world.WorldGenEnderIsland.generateObelisk(WorldGenEnderIsland.java:148)
	at com.brandon3055.draconicevolution.common.world.WorldGenEnderIsland.generateObelisks(WorldGenEnderIsland.java:133)
	at com.brandon3055.draconicevolution.common.world.WorldGenEnderIsland.func_76484_a(WorldGenEnderIsland.java:37)
	at com.brandon3055.draconicevolution.common.world.DraconicWorldGenerator.generateEnd(DraconicWorldGenerator.java:44)
	at com.brandon3055.draconicevolution.common.world.DraconicWorldGenerator.generate(DraconicWorldGenerator.java:22)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:106)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:174)
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:300)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by brandon3055** [comment]
This is fixed in the latest snapshots.
