### ISSUE TITLE
GUI error

### ISSUE THREAD

**Issue by NicosaurusRex99** [brandon3055/Draconic-Evolution#193]
the crash report said ---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 12/7/15 3:46 PM
Description: Ticking screen

java.lang.ClassCastException: com.brandon3055.draconicevolution.client.gui.guicomponents.ComponentContributorsPage cannot be cast to com.brandon3055.draconicevolution.client.gui.guicomponents.ComponentManualPage
	at com.brandon3055.draconicevolution.client.gui.componentguis.GUIManual.func_73876_c(GUIManual.java:196)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1661)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by wlhlm** [comment]
This has been fixed already. Please update to the latest version. See #177.
