### ISSUE TITLE
Client kicked from server when using DE sword on an Endersteed

### ISSUE THREAD

**Issue by LemADEC** [brandon3055/Draconic-Evolution#208]
When a player try to left click with Draconic sword on a Thaumic Horizons Endersteed, a NPE happens on the server and that player gets kicked:
```
[18:15:09 WARN]: Failed to handle packet for /xxxxxx:34607
java.lang.NullPointerException
>       at com.brandon3055.draconicevolution.common.items.tools.baseclasses.ToolHandler.damageEntityBasedOnHealth(ToolHandler.java:165) ~[ToolHandler.class:?]
>       at com.brandon3055.draconicevolution.common.items.weapons.DraconicSword.onLeftClickEntity(DraconicSword.java:85) ~[DraconicSword.class:?]
>       at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1362) ~[yz.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java) ~[mw.class:?]
>       at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source) ~[ServerPlayerAPI.class:?]
>       at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java) ~[mw.class:?]
>       at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1558) ~[nh.class:?]
>       at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) ~[ja.class:?]
>       at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) ~[ja.class:?]
>       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) ~[ej.class:?]
>       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:991) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431) [lt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:809) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.7.0_85]
```

This happens with the following notable mods:
Baubles-1.7.10-1.0.1.10.jar
Draconic-Evolution-1.7.10-1.0.2-Snapshot_9.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumichorizons-1.7.10-1.1.9.jar

**Comment by LemADEC** [comment]
Issue couldn't be reproduced

**Comment by brandon3055** [comment]
ok i have no idea how that could ever possibly happen but if it ever happens again i have added a check that should prevent it.
