### ISSUE TITLE
Client fails to connect - PlayerCapabilities.func_75092_a(F)V

### ISSUE THREAD

**Issue by fishloaf** [brandon3055/Draconic-Evolution#252]
Just updated to the new Beta (Snapshot 10).  Server comes up fine but when I attempt to connect to the server it fails with the below error.  I thought it may be that flight needed to be enabled but that did not solve the problem.  Seems to be related to the Draconic Armor in some fashion.

[08:20:52] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$PlayerTickEvent@5f086096:
java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_75092_a(F)V
        at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.tickArmorEffects(CustomArmorHandler.java:204) ~[CustomArmorHandler.class:?]
        at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.onPlayerTick(CustomArmorHandler.java:168) ~[CustomArmorHandler.class:?]
        at com.brandon3055.draconicevolution.common.handler.FMLEventHandler.onPlayerTick(FMLEventHandler.java:32) ~[FMLEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_357_FMLEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) [FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295) [mw.class:?]
        at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source) [ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) [jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) [jf.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[08:20:52] [Server thread/ERROR] [FML]: Index: 9 Listeners:
[08:20:52] [Server thread/ERROR] [FML]: 0: NORMAL
[08:20:52] [Server thread/ERROR] [FML]: 1: ASM: cofh.mod.updater.UpdateManager@1d81f756 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 2: ASM: us.ichun.mods.ichunutil.common.core.TickHandlerServer@49dbd651 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 3: ASM: cofh.mod.updater.UpdateManager@508c71a0 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 4: ASM: cofh.mod.updater.UpdateManager@1f33599b tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 5: ASM: mods.railcraft.common.blocks.hidden.TrailTicker@3bb69856 tick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 6: ASM: mods.railcraft.common.items.firestone.FirestoneTickHandler@1e44e046 tick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 7: ASM: crazypants.enderio.item.darksteel.DarkSteelController@14d6c559 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 8: ASM: crazypants.enderio.item.MagnetController@d17b302 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 9: ASM: com.brandon3055.draconicevolution.common.handler.FMLEventHandler@4d20706 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 10: ASM: com.rwtema.extrautils.crafting.LawSwordCraftHandler@40d06db2 event(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 11: ASM: tconstruct.armor.ArmorAbilities@635182f1 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 12: ASM: chylex.hee.mechanics.compendium.events.CompendiumEvents@69e1f7de onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 13: ASM: hardcorequesting.EventHandler@12032f6a onEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 14: ASM: openperipheral.addons.glasses.server.TerminalManagerServer$FmlListener@8e603e9 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 15: ASM: jotato.quantumflux.EventHooks@30875b51 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 16: ASM: Reika.DragonAPI.Auxiliary.Trackers.TickRegistry@60c0d8c1 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 17: ASM: ivorius.reccomplex.events.RCFMLEventHandler@5f3119d8 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 18: ASM: cofh.mod.updater.UpdateManager@5fc4f6fb tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 19: ASM: cofh.mod.updater.UpdateManager@5fa97bc3 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 20: ASM: com.emoniph.witchery.common.ServerTickEvents@73946ee4 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 21: ASM: codechicken.nei.ServerHandler@6077cf38 tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 22: ASM: com.advGenetics.Event.TickEventHandler@7c24967e onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 23: ASM: darkevilmac.archimedes.common.handler.CommonPlayerTicker@4bc7048f onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 24: ASM: de.eydamos.backpack.handler.EventHandlerBackpack@13376b11 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 25: ASM: twilightforest.TFTickHandler@265c36a1 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 26: ASM: INSTANCE onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 27: ASM: com.enderio.core.common.handlers.FireworkHandler@2df20563 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 28: ASM: cofh.mod.updater.UpdateManager@65c176e3 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 29: ASM: mekanism.common.CommonPlayerTickHandler@4338f013 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 30: ASM: extracells.util.ExtraCellsEventHandler@3d6f61e2 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 31: ASM: thaumic.tinkerer.common.potion.PotionEffectHandler@c0f1e7c onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 32: ASM: gravigun.common.core.TickHandlerServer@69bee52c onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 33: ASM: morph.common.core.TickHandlerServer@797506b7 playerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 34: ASM: cofh.mod.updater.UpdateManager@eb5a894 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 35: ASM: openblocks.common.ServerTickHandler@310b10b9 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 36: ASM: portalgun.common.core.TickHandlerServer@5d07b54f onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 37: ASM: mcjty.rftools.FMLEventHandlers@456d4de0 onPlayerTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 38: ASM: com.rwtema.extrautils.worldgen.Underdark.DarknessTickHandler@747e7354 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 39: ASM: crazypants.enderio.machine.wireless.WirelessChargerController@3ab753e6 onPlayerTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 40: ASM: vazkii.botania.common.block.BlockPistonRelay@1a06384c tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 41: ASM: lumien.randomthings.Handler.RTTickHandler@26d6cb1e tick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 42: ASM: ivorius.reccomplex.events.RCFMLEventHandler@5f3119d8 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 43: ASM: appeng.hooks.TickHandler@3eb22527 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[08:20:52] [Server thread/ERROR] [FML]: 44: LOWEST
[08:20:52] [Server thread/ERROR] [FML]: 45: ASM: vazkii.botania.common.item.ItemRegenIvy@2fbb480a onTick(Lcpw/mods/fml/common/gameevent/TickEvent$PlayerTickEvent;)V
[08:20:52] [Server thread/WARN]: Failed to handle packet for /74.222.248.93:50607
net.minecraft.util.ReportedException: Ticking player
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:349) ~[mw.class:?]
        at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source) ~[ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java) ~[mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20) ~[jf.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_75092_a(F)V
        at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.tickArmorEffects(CustomArmorHandler.java:204) ~[CustomArmorHandler.class:?]
        at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.onPlayerTick(CustomArmorHandler.java:168) ~[CustomArmorHandler.class:?]
        at com.brandon3055.draconicevolution.common.handler.FMLEventHandler.onPlayerTick(FMLEventHandler.java:32) ~[FMLEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_357_FMLEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295) ~[mw.class:?]
        ... 12 more

**Comment by therodet** [comment]
+1 Having this error as well. I removed my armor using NBTEdit, and was able to log in. Cheated myself a fresh set, and was disconnected the instant I tried to equip.

**Comment by brandon3055** [comment]
Fix uploaded 
http://minecraft.curseforge.com/projects/draconic-evolution/files/2283565

**Comment by MacCamintosh** [comment]
We have Draconic-Evolution-1.7.10-1.0.2-Snapshot_10-beta2 on our server
Players can't equip armor. When leaving the inventory, armor is automatically de-equiped.
Client and server gives nothing.
Expect for the draconic chestplate. It automaticaly disconnect the player, and give a "Internal Server Error"
And server gives this:

net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_75092_a(F)V
	at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.tickArmorEffects(CustomArmorHandler.java:237) ~[CustomArmorHandler.class:?]
	at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.onPlayerTick(CustomArmorHandler.java:168) ~[CustomArmorHandler.class:?]
	at com.brandon3055.draconicevolution.common.handler.FMLEventHandler.onPlayerTick(FMLEventHandler.java:32) ~[FMLEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_211_FMLEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more

**Comment by araevingaming** [comment]
brandon, that fix link doesnt seem to exist
