### ISSUE TITLE
Equipping Draconic Chestplate Returns Internal Server Error On Multiplayer

### ISSUE THREAD

**Issue by chaNcharge** [brandon3055/Draconic-Evolution#255]
Whenever I equip a Draconic Chestplate on a Multiplayer server, I get kicked with Internal Server Error. This is the error in the log and I am using the snapshot 10 beta version of Draconic Evolution:

[18:03:04] [Server thread/WARN]: Failed to handle packet for /73.25.226.159:39231
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:349) ~[mw.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8) ~[jd.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.player.PlayerCapabilities.func_75092_a(F)V
	at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.tickArmorEffects(CustomArmorHandler.java:204) ~[CustomArmorHandler.class:?]
	at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.onPlayerTick(CustomArmorHandler.java:168) ~[CustomArmorHandler.class:?]
	at com.brandon3055.draconicevolution.common.handler.FMLEventHandler.onPlayerTick(FMLEventHandler.java:32) ~[FMLEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_120_FMLEventHandler_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPlayerPreTick(FMLCommonHandler.java:345) ~[FMLCommonHandler.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:220) ~[yz.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295) ~[mw.class:?]
	... 10 more
[18:03:04] [Server thread/INFO]: chaNcharge lost connection: TextComponent{text='Internal server error', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by brandon3055** [comment]
There is already a fix for this "1.0.2-Snapshot_10-beta2"
