### ISSUE TITLE
RotaryCraft + EnderIO + DE server crash

### ISSUE THREAD

**Issue by MineWitherMC** [brandon3055/Draconic-Evolution#324]
## Description
If DE is installed placing RotaryCraft bedrock alloy sword in EnderIO killer joe crashes the server as soon as killer attacks somebody. Tested with players with electric (quantum), pseudoelectric (dark steel) and normal (diamond) armor. Crash doesn't happen without DE.

## Base information
* Minecraft version: 1.7.10
* Minecraft Forge version: build 1614
* Draconic Evolution version: 1.0.2d

## Mod List or Mod Pack (include version)
BrandonsCore 1.0.0.12
EnderIO 2.3.0.425
EnderCore 0.2.0.34
DragonAPI 13b
DragonAPI 13a

## Crash report
```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 5/28/16 9:39 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at com.brandon3055.draconicevolution.integration.ModHelper.applyModDamageAdjustments(ModHelper.java:62)
	at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.onPlayerAttacked(CustomArmorHandler.java:85)
	at com.brandon3055.draconicevolution.common.handler.MinecraftForgeEventHandler.onLivingAttack(MinecraftForgeEventHandler.java:163)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_30_MinecraftForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:292)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:978)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at crazypants.enderio.machine.killera.TileKillerJoe.processTasks(TileKillerJoe.java:225)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:262)
	at crazypants.enderio.machine.killera.TileKillerJoe.doUpdate(TileKillerJoe.java:141)
	at com.enderio.core.common.TileEntityEnder.func_145845_h(TileEntityEnder.java:45)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.brandon3055.draconicevolution.integration.ModHelper.applyModDamageAdjustments(ModHelper.java:62)
	at com.brandon3055.draconicevolution.common.items.armor.CustomArmorHandler.onPlayerAttacked(CustomArmorHandler.java:85)
	at com.brandon3055.draconicevolution.common.handler.MinecraftForgeEventHandler.onLivingAttack(MinecraftForgeEventHandler.java:163)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_30_MinecraftForgeEventHandler_onLivingAttack_LivingAttackEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.common.ForgeHooks.onLivingAttack(ForgeHooks.java:292)
	at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:978)
	at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:491)
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232)
	at crazypants.enderio.machine.killera.TileKillerJoe.processTasks(TileKillerJoe.java:225)
	at crazypants.enderio.machine.AbstractMachineEntity.doUpdate(AbstractMachineEntity.java:262)
	at crazypants.enderio.machine.killera.TileKillerJoe.doUpdate(TileKillerJoe.java:141)
	at com.enderio.core.common.TileEntityEnder.func_145845_h(TileEntityEnder.java:45)

-- Block entity being ticked --
Details:
	Name: blockKillerJoeTileEntity // crazypants.enderio.machine.killera.TileKillerJoe
	Block type: ID #242 (tile.blockKillerJoe // crazypants.enderio.machine.killera.BlockKillerJoe)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-64,71,180), Chunk: (at 0,4,4 in -4,11; contains blocks -64,0,176 to -49,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Actual block type: ID #242 (tile.blockKillerJoe // crazypants.enderio.machine.killera.BlockKillerJoe)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: 1234
	All players: 1 total; [EntityPlayerMP['_MultiDragon_'/255, l='1234', x=-61.30, y=71.00, z=180.63]]
	Chunk stats: ServerChunkCache: 722 Drop: 0
	Level seed: -8036297734275936518
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-72,64,188), Chunk: (at 8,4,12 in -5,11; contains blocks -80,0,176 to -65,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 633 game time, 633 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 140678 (now: false), thunder time: 121242 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_77, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 792342824 bytes (755 MB) / 1361575936 bytes (1298 MB) up to 1908932608 bytes (1820 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx2048m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10-universal.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2d} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.2d.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (DragonAPI 1.7.10 V13b.jar) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.34_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.34_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.425_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.425_beta.jar) 
	UCHIJAAAA	RotaryCraft{1.0} [RotaryCraft] (RotaryCraft 1.7.10 V13a.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	EnderIO: No known problems detected.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['_MultiDragon_'/255, l='1234', x=-61.30, y=71.00, z=180.63]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by brandon3055** [comment]
Was wondering when someone would find this crash. Will be pushing a fix to curse soon.
