### ISSUE TITLE
ModelWyvernArmor + RenderPlayerAPIEnhancer

### ISSUE THREAD

**Issue by SvEgiiVEteR** [brandon3055/Draconic-Evolution#327]
## Base information
* Minecraft version:1.7.10
* Minecraft Forge version:10.13.4.1614
* Draconic Evolution version:1.0.2e

## Mod List or Mod Pack (include version)
...
NotEnoughIDs-1.4.3.3.jar
DragonAPI 1.7.10 V12e.jar
zExtendedPotions-MC1.7.10-1.2.jar
BrandonsCore-1.0.0.12.jar
Draconic-Evolution-1.7.10-1.0.2e.jar
SmartMoving-1.7.10-15.6.jar
SmartRender-1.7.10-2.1.jar
NEIIntegration-MC1.7.10-1.1.2.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
PlayerAPI-1.7.10-1.4.jar
RenderPlayerAPI-1.7.10-1.4.jar
RenderPlayerAPIEnhancer-1.7.10-1.4.jar
...
```
---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 5/30/16 11:58 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.smart.render.SmartRenderModel.setRotationAngles(SmartRenderModel.java:209)
	at net.smart.render.playerapi.SmartRenderModelPlayerBase.setRotationAngles(SmartRenderModelPlayerBase.java:74)
	at api.player.model.ModelPlayerAPI.setRotationAngles(Unknown Source)
	at api.player.model.ModelPlayerAPI.setRotationAngles(Unknown Source)
	at api.player.model.ModelPlayer.func_78087_a(Unknown Source)
	at com.brandon3055.draconicevolution.client.model.ModelDraconicArmor.localRender(ModelDraconicArmor.java:150)
	at api.player.model.ModelPlayerBase.render(Unknown Source)
	at net.smart.render.playerapi.SmartRenderModelPlayerBase.superRender(SmartRenderModelPlayerBase.java:54)
	at net.smart.render.SmartRenderModel.render(SmartRenderModel.java:143)
	at net.smart.render.playerapi.SmartRenderModelPlayerBase.render(SmartRenderModelPlayerBase.java:48)
	at api.player.model.ModelPlayerAPI.render(Unknown Source)
	at api.player.model.ModelPlayerAPI.render(Unknown Source)
	at api.player.model.ModelPlayer.func_78088_a(Unknown Source)
	at com.brandon3055.draconicevolution.client.render.item.RenderArmor.renderItem(RenderArmor.java:54)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.smart.render.SmartRenderModel.setRotationAngles(SmartRenderModel.java:209)
	at net.smart.render.playerapi.SmartRenderModelPlayerBase.setRotationAngles(SmartRenderModelPlayerBase.java:74)
	at api.player.model.ModelPlayerAPI.setRotationAngles(Unknown Source)
	at api.player.model.ModelPlayerAPI.setRotationAngles(Unknown Source)
	at api.player.model.ModelPlayer.func_78087_a(Unknown Source)
	at com.brandon3055.draconicevolution.client.model.ModelDraconicArmor.localRender(ModelDraconicArmor.java:150)
	at api.player.model.ModelPlayerBase.render(Unknown Source)
	at net.smart.render.playerapi.SmartRenderModelPlayerBase.superRender(SmartRenderModelPlayerBase.java:54)
	at net.smart.render.SmartRenderModel.render(SmartRenderModel.java:143)
	at net.smart.render.playerapi.SmartRenderModelPlayerBase.render(SmartRenderModelPlayerBase.java:48)
	at api.player.model.ModelPlayerAPI.render(Unknown Source)
	at api.player.model.ModelPlayerAPI.render(Unknown Source)
	at api.player.model.ModelPlayer.func_78088_a(Unknown Source)
	at com.brandon3055.draconicevolution.client.render.item.RenderArmor.renderItem(RenderArmor.java:54)
	at net.minecraftforge.client.ForgeHooksClient.renderInventoryItem(ForgeHooksClient.java:183)

-- Item being rendered --
Details:
	Item Type: com.brandon3055.draconicevolution.common.items.armor.DraconicArmor@601df30
	Item Aux: 0
	Item NBT: {Energy:9940000,ShieldEntropy:0.0f,ConfigProfiles:[0:{},1:{},2:{},3:{},4:{}],ProtectionPoints:60.0f}
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:563)
	at codechicken.nei.guihook.GuiContainerManager.drawSlotItem(GuiContainerManager.java:489)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:47)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (322, 162). Absolute: (645, 325)
	Screen size: Scaled: (645, 325). Absolute: (1290, 650). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['SvEgiiVEteR'/276, l='MpServer', x=-200.67, y=73.62, z=180.55]]
	Chunk stats: MultiplayerChunkCache: 81, 81
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-200,64,140), Chunk: (at 8,4,12 in -13,8; contains blocks -208,0,128 to -193,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 5517 game time, 5517 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 68 total; [EntityZombie['Зомби'/128, l='MpServer', x=-236.97, y=20.00, z=129.50], EntityCreeper['Крипер'/129, l='MpServer', x=-232.50, y=34.00, z=187.50], EntityCreeper['Крипер'/130, l='MpServer', x=-231.50, y=19.00, z=192.50], EntityCreeper['Крипер'/131, l='MpServer', x=-223.59, y=43.00, z=199.00], EntityCreeper['Крипер'/132, l='MpServer', x=-225.50, y=44.00, z=203.50], EntityCreeper['Крипер'/133, l='MpServer', x=-234.63, y=47.00, z=199.94], EntitySkeleton['Скелет'/134, l='MpServer', x=-237.13, y=50.00, z=205.50], EntityBat['Летучая мышь'/135, l='MpServer', x=-233.24, y=52.23, z=232.68], EntityZombie['Зомби'/136, l='MpServer', x=-226.84, y=50.00, z=243.78], EntityZombie['Зомби'/137, l='MpServer', x=-227.69, y=50.00, z=244.69], EntityClientPlayerMP['SvEgiiVEteR'/276, l='MpServer', x=-200.67, y=73.62, z=180.55], EntitySkeleton['Скелет'/149, l='MpServer', x=-208.16, y=46.00, z=115.50], EntityItem['item.tile.flower1.dandelion'/150, l='MpServer', x=-212.22, y=66.13, z=138.84], EntityCreeper['Крипер'/151, l='MpServer', x=-209.03, y=16.00, z=148.41], EntityZombie['Зомби'/152, l='MpServer', x=-221.66, y=48.00, z=176.91], EntityBat['Летучая мышь'/153, l='MpServer', x=-213.54, y=47.03, z=189.07], EntityCreeper['Крипер'/154, l='MpServer', x=-206.05, y=19.00, z=217.67], EntityCreeper['Крипер'/155, l='MpServer', x=-206.85, y=21.00, z=230.54], EntityBat['Летучая мышь'/156, l='MpServer', x=-218.33, y=49.74, z=253.45], EntityBat['Летучая мышь'/157, l='MpServer', x=-212.27, y=53.59, z=240.53], EntityBat['Летучая мышь'/158, l='MpServer', x=-215.74, y=51.26, z=237.05], EntitySkeleton['Скелет'/165, l='MpServer', x=-206.41, y=45.00, z=121.46], EntityItem['item.tile.dirt.default'/166, l='MpServer', x=-206.13, y=63.13, z=139.28], EntityItem['item.tile.dirt.default'/167, l='MpServer', x=-207.72, y=63.13, z=138.56], EntityItem['item.tile.dirt.default'/168, l='MpServer', x=-201.13, y=65.13, z=139.19], EntityItem['item.tile.dirt.default'/169, l='MpServer', x=-201.88, y=65.13, z=139.28], EntityBat['Летучая мышь'/170, l='MpServer', x=-211.49, y=47.67, z=190.38], EntityBat['Летучая мышь'/171, l='MpServer', x=-206.91, y=55.10, z=215.51], EntitySkeleton['Скелет'/181, l='MpServer', x=-180.58, y=31.84, z=138.31], EntitySkeleton['Скелет'/182, l='MpServer', x=-184.50, y=31.00, z=140.50], EntityZombie['Зомби'/196, l='MpServer', x=-175.50, y=53.00, z=147.50], EntityCreeper['Крипер'/197, l='MpServer', x=-172.50, y=53.00, z=147.50], EntityCreeper['Крипер'/212, l='MpServer', x=-153.50, y=54.00, z=144.50], EntityCreeper['Крипер'/213, l='MpServer', x=-150.34, y=53.00, z=146.53], EntitySpider['Паук'/91, l='MpServer', x=-257.34, y=36.00, z=142.50], EntityCreeper['Крипер'/92, l='MpServer', x=-270.50, y=35.00, z=135.50], EntityBat['Летучая мышь'/93, l='MpServer', x=-265.32, y=35.33, z=133.68], EntitySquid['Спрут'/221, l='MpServer', x=-139.19, y=56.97, z=121.53], EntityCow['Корова'/94, l='MpServer', x=-257.28, y=64.00, z=139.47], EntityZombie['Зомби'/95, l='MpServer', x=-263.44, y=14.00, z=153.88], EntitySkeleton['Скелет'/96, l='MpServer', x=-263.50, y=14.00, z=157.50], EntityCreeper['Крипер'/225, l='MpServer', x=-138.50, y=35.00, z=137.50], EntityZombie['Зомби'/97, l='MpServer', x=-261.50, y=35.00, z=146.50], EntityCreeper['Крипер'/226, l='MpServer', x=-130.06, y=54.00, z=145.50], EntityBat['Летучая мышь'/98, l='MpServer', x=-262.75, y=35.10, z=209.25], EntityCreeper['Крипер'/100, l='MpServer', x=-261.50, y=41.00, z=224.50], EntityEnderman['Эндермен'/101, l='MpServer', x=-264.33, y=37.81, z=247.22], EntityCreeper['Крипер'/102, l='MpServer', x=-264.51, y=40.47, z=252.31], EntityZombie['Зомби'/103, l='MpServer', x=-256.44, y=56.00, z=246.00], EntitySkeleton['Скелет'/107, l='MpServer', x=-254.50, y=35.00, z=142.50], EntitySkeleton['Скелет'/108, l='MpServer', x=-252.50, y=35.00, z=129.50], EntitySkeleton['Скелет'/109, l='MpServer', x=-256.77, y=36.00, z=128.50], EntityZombie['Зомби'/110, l='MpServer', x=-250.50, y=35.00, z=131.50], EntityBat['Летучая мышь'/111, l='MpServer', x=-243.25, y=36.10, z=135.53], EntityCow['Корова'/112, l='MpServer', x=-244.25, y=65.00, z=139.38], EntityCow['Корова'/113, l='MpServer', x=-253.50, y=65.00, z=132.50], EntityCow['Корова'/114, l='MpServer', x=-253.50, y=65.00, z=130.50], EntityCow['Корова'/115, l='MpServer', x=-241.72, y=65.00, z=143.25], EntityCow['Корова'/116, l='MpServer', x=-245.06, y=65.00, z=137.94], EntityCow['Корова'/117, l='MpServer', x=-241.09, y=65.00, z=141.03], EntityCow['Корова'/118, l='MpServer', x=-245.81, y=65.00, z=135.78], EntitySkeleton['Скелет'/119, l='MpServer', x=-254.50, y=50.00, z=153.50], EntitySkeleton['Скелет'/120, l='MpServer', x=-254.13, y=49.00, z=155.66], EntityCreeper['Крипер'/121, l='MpServer', x=-250.50, y=43.00, z=201.97], EntityZombie['Зомби'/122, l='MpServer', x=-247.50, y=50.00, z=216.50], EntityBat['Летучая мышь'/123, l='MpServer', x=-249.44, y=50.00, z=217.93], EntitySkeleton['Скелет'/126, l='MpServer', x=-233.50, y=20.00, z=114.50], EntityBat['Летучая мышь'/127, l='MpServer', x=-242.85, y=21.00, z=112.47]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_92, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 159658496 bytes (152 MB) / 403288064 bytes (384 MB) up to 6130958336 bytes (5846 MB)
	JVM Flags: 12 total; -Xmx5920m -XX:MaxPermSize=448m -XX:PermSize=448m -XX:NewRatio=8 -XX:SurvivorRatio=7 -XX:-UseAdaptiveSizePolicy -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:+UseParNewGC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 15, tcache: 0, allocated: 13, tallocated: 95
	FML: Minecraft 1.7.10 MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 20 mods loaded, 20 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (INFO_GUI_3_S_NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJAAAA	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHIJAAAA	RenderPlayerAPIEnhancer{1.4} [Render Player API Enhancer] (minecraft.jar) 
	UCHIJAAAA	<DragonAPI ASM>{0} [DragonAPI ASM Data Initialization] (minecraft.jar) 
	UCHIJAAAA	ExtendedPotions{1.2} [Extended Potions] (0EXT_LIB_zExtendedPotions-MC1.7.10-1.2.jar) 
	UCHIJAAAA	notenoughIDs{1.4.3.3} [NotEnoughIDs] (0EXT_0_NotEnoughIDs-1.4.3.3.jar) 
	UCHIJAAAA	DragonAPI{1.0} [DragonAPI] (0EXT_LIB_RM_DragonAPI 1.7.10 V12e.jar) 
	UCHIJAAAA	BrandonsCore{1.0.0.12} [Brandon's Core] (2_15_BrandonsCore-1.0.0.12.jar) 
	UCHIJAAAA	DraconicEvolution{1.0.2e} [Draconic Evolution] (2_15_Draconic-Evolution-1.7.10-1.0.2e.jar) 
	UCHIJAAAA	SmartMoving{15.6} [Smart Moving] (GUI_1_S_SmartMoving-1.7.10-15.6.jar) 
	UCHIJAAAA	SmartRender{2.1} [Smart Render] (GUI_1_SmartRender-1.7.10-2.1.jar) 
	UCHIJAAAA	neiintegration{1.1.2} [NEI Integration] (INFO_GUI_3_S_NEIIntegration-MC1.7.10-1.1.2.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	Launched Version: 1.7.10-LiteLoader1.7.10-1.7.10-Forge10.13.4.1614-1.7.10
	XRay Version: 20
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 5700 Series GL version 4.4.13084 Compatibility Profile Context 14.301.1001.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [TEXTYRfix.zip, Decocraft_Template_TexturePackV2.2.1.zip, HEE Music v1.0.zip, matmos-rhapsodia-0.6.zip, F32-1.7.10fixRUS.zip, RUS-Minecraft-Portal.zip]
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```
crash happens if I write to the file render_player_api_Enhancer_classnames.txt this:
```
com.brandon3055.draconicevolution.client.model.ModelDraconicArmor
com.brandon3055.draconicevolution.client.model.ModelWyvernArmor

```
I wanted to fix the rotation of the armor together with the body using the mod RenderPlayerAPIEnhancer... :(
and the visual glitch ModelWyvernArmor
http://i.imgur.com/NAMaZi3.png

UP

I could fix the rotation of armor....
```
com.brandon3055.draconicevolution.client.model.ModelDraconicArmorOld
```
and:
```
    B:"Use old 2D tool textures"=true
    B:"Use old armor model"=false
    B:"Use the original 3D armor models"=true
```
but when I go to the inventory crash
https://gist.github.com/137ce685c6f411ac8c41041318a898e4

it seems the problem with the display of armor item
I hope this can be resolved)
one of the problems with the rotation of the armor I was able to get rid of)

**Comment by GreatOrator** [comment]
Compatibility with SmartMoving is already on the list of enhancements but will not be added to 1.7.10 as of right now.  There was a couple of other reports/requests.

**Comment by SvEgiiVEteR** [comment]
so it will be added later?
if Yes then it is good)
