### ISSUE TITLE
[1.7.10] Crash rendering Dragon hit

### ISSUE THREAD

**Issue by Eufranio** [brandon3055/Draconic-Evolution#396]
When a player goes to The End, and get a hit from the dragon (from DE), the client crashes.
- Minecraft version: 1.7.10
- Minecraft Forge version: 1614
- Draconic Evolution version: 1.0.2H

```
java.lang.NullPointerException: Rendering screen
    at com.brandon3055.draconicevolution.client.gui.guicomponents.ComponentConfigItemButton.renderFinal(ComponentConfigItemButton.java:69)
    at com.brandon3055.brandonscore.client.gui.guicomponents.ComponentCollection.renderFinal(ComponentCollection.java:73)
    at com.brandon3055.brandonscore.client.gui.guicomponents.GUIBase.func_73863_a(GUIBase.java:93)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

Full crash report: http://hastebin.com/itapexajeq.rb

**Comment by brandon3055** [comment]
That crash is coming from the tool config gui not the dragon. If i had to guess based on the report it looks like the player may have died while they were configuring an item and that may have thrown that error.

I will fis this if i ever push a new bug fix build for 1.7.10 I am nolonger actively developing 1.7.10.

For the moment just tell players to try not to die while configuring their tools.

**Comment by Eufranio** [comment]
They didn't die, and they weren't configuring the GUI, happens when a player is hit by the dragon, or threw by it. 
Please, make a 1.7 release :/

**Comment by brandon3055** [comment]
If they were not configuring an item it would not have been possible for that crash to occure. That crash was thrown by the item config gui.

**Comment by Eufranio** [comment]
The crash happen when the dragon hits them, and they "jump" like 100 blocks away...

**Comment by Morpheus1101** [comment]
1.7.10 is Dead and not very modders actively support or update in this vers .. move onto 1.10.2 :D

**Comment by Eufranio** [comment]
The cause is the bigger vector in the hit given by the DE dragon.

**Comment by brandon3055** [comment]
Ether you have given me the wrong crash report of your just wrong.
