### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by ttamttamS** [brandon3055/Draconic-Evolution#450]
Game crashes on load. I am running multiple mods but this problem goes away when I disable Draconic evolution. I fixed this by rolling back to version 2.0.0.120, which makes me think this is something that can be fixed on this mod's end and not one of the other mods I have running. I'm using Curse Client because I'm lazy and don't miss keeping track of about a hundred mods as they update. Everything is up to date according to Curse Client.
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  MovingWorldCoreMod (movingworld-1.10.2-0003-full.jar)
  FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  BetterFoliageLoader (BetterFoliage-MC1.10-2.1.1.jar)
  StreamsCoreMod (Streams-1.9.4-0.2.1.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 11/18/16 9:02 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Draconic Evolution (draconicevolution)
Caused by: java.lang.NoSuchFieldError: verts
	at com.brandon3055.draconicevolution.client.render.tile.RenderTilePotentiometer.<init>(RenderTilePotentiometer.java:37)
	at com.brandon3055.draconicevolution.blocks.Potentiometer.registerRenderer(Potentiometer.java:186)
	at com.brandon3055.brandonscore.config.ModFeatureParser.registerRendering(ModFeatureParser.java:184)
	at com.brandon3055.draconicevolution.client.ClientProxy.preInit(ClientProxy.java:46)
	at com.brandon3055.draconicevolution.DraconicEvolution.preInit(DraconicEvolution.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1033275896 bytes (985 MB) / 1925185536 bytes (1836 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.2.2151 98 mods loaded, 98 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2151.jar) 
	UCH	Forge{12.18.2.2151} [Minecraft Forge] (forge-1.10.2-12.18.2.2151.jar) 
	UCH	OpenComputers|Core{1.6.0.4} [OpenComputers (Core)] (minecraft.jar) 
	UCH	io.github.elytra.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCH	fenceoverhaul{1.2.1} [Fence Overhaul] ([1.10.x]FenceOverhaul-1.2.1.jar) 
	UCH	Baubles{1.3.5} [Baubles] (Baubles-1.10.2-1.3.5.jar) 
	UCH	Botania{r1.9-338} [Botania] (Botania r1.9-338.jar) 
	UCH	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCH	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCH	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCH	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCH	JEI{3.13.3.377} [Just Enough Items] (jei_1.10.2-3.13.3.377.jar) 
	UCH	AppleCore{2.1.0} [AppleCore] (AppleCore-mc1.10.2-2.1.0.jar) 
	UCH	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCH	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCH	basemetals{2.4.0} [Base Metals] (BaseMetals_1.10.2-2.4.0.11.jar) 
	UCH	BetterFoliage{2.1.1} [Better Foliage] (BetterFoliage-MC1.10-2.1.1.jar) 
	UCH	BiomesOPlenty{5.0.0.2104} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2104-universal.jar) 
	UCH	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCH	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCH	infinitylib{1.10.2-0.2.1} [InfinityLib] (infinitylib-0.2.1.jar) 
	UCH	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.2.jar) 
	UCH	CodeChickenLib{2.4.3.124} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.4.3.124-universal.jar) 
	UCH	brandonscore{2.1.1} [Brandon's Core] (BrandonsCore-1.10.2-2.1.1.61-universal.jar) 
	UCH	Chameleon{1.10-2.1.8} [Chameleon] (Chameleon-1.10-2.1.8.jar) 
	UCH	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCH	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCH	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCH	ChiselsBytes{0.4} [Chisels & Bytes] (ChiselsBytes-1.9.4-0.4.jar) 
	UCH	MineTweaker3{3.0.14} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCH	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.15.jar) 
	UCH	movingworld{1.10.2-0003} [Moving World] (movingworld-1.10.2-0003-full.jar) 
	UCH	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.10.2-0003-full.jar) 
	UCH	ElecCore{1.6.333} [ElecCore] (ElecCore-1.10.2-1.6.333.jar) 
	UCH	OpenComputers{1.6.0.4} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.4.jar) 
	UCH	deepresonance{1.3.0} [DeepResonance] (deepresonance-1.10-1.3.0.jar) 
	UCH	defaultoptions{6.1.5} [Default Options] (DefaultOptions_1.10.2-6.1.5.jar) 
	UCE	draconicevolution{2.0.3} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.3.137-universal.jar) 
	UCH	dsurroundunofficial{3.0.6.1BETA} [Dynamic Surroundings Unofficial] (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar) 
	UCH	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCH	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCH	EnderIO{1.10.2-3.0.1.126_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.126_beta.jar) 
	UCH	enderthing{0.7.1} [Enderthing] (enderthing-1.10.2-0.7.1.jar) 
	UCH	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCH	excore{1.6.2} [EXCore] (Excore-1.6.2-1.10.2.jar) 
	UCH	ExtraBitManipulation{1.10.2-2.1.0} [Extra Bit Manipulation] (ExtraBitManipulation-1.10.2-2.1.0.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.2.jar) 
	UCH	FFS{1.10.2-1.6.5-b31} [Fancy Fluid Storage] (Fancy Fluid Storage-1.10.2-1.6.5-b31.jar) 
	UCH	Farseek{1.9.4} [Farseek] (Farseek-1.9.4-1.1.jar) 
	UCH	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCH	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCH	moreoverlays{1.8} [MoreOverlays] (moreoverlays-1.8-mc1.10.2.jar) 
	UCH	FEI{1.0.17.2} [Forever Enough Items] (ForeverEnoughItems-1.0.17.2-1.10.2.jar) 
	UCH	geographicraft{0.7.5} [GeographiCraft] (GeographiCraft-1.9.4-0.7.6.jar) 
	UCH	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCH	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCH	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCH	jeresources{0.5.7.87} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.7.87.jar) 
	UCH	jet{2.1.38} [JustEnoughTooltips] (JustEnoughTooltips-1.10.2-2.1.38.jar) 
	UCH	mtlib{@VERSION@} [MTLib] (MTLib-1.0.0.jar) 
	UCH	modtweaker{2.0.6} [Mod Tweaker] (ModTweaker2-2.0.6.jar) 
	UCH	natura{1.10.2-4.0.0.93} [Natura] (natura-1.10.2-4.0.0.93.jar) 
	UCH	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCH	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCH	yurtmod{7.01} [Nomadic Tents] (NomadicTents[1.10.2]-7.01.jar) 
	UCH	openprinter{0.1.0.3} [OpenPrinter] (OpenPrinter-1.9.4-0.1.0.3.jar) 
	UCH	openradio{0.9.4} [OpenRadio] (OpenRadio-0.9.4-MC1.10.2.jar) 
	UCH	orespawn{1.1.0} [Ore Spawn] (OreSpawn_1.10.2-1.1.0.jar) 
	UCH	packingtape{0.6.0} [Packing Tape] (PackingTape-1.10.2-0.6.0.jar) 
	UCH	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCH	rftools{5.61} [RFTools] (rftools-1.10-5.61.jar) 
	UCH	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCH	PersistentBits{1.0.6} [Persistent Bits] (PersistentBits-1.10.2-1.0.6.jar) 
	UCH	StellarAPI{0.5.4.1.3} [Stellar API] (Stellar API-0.5.4.1.3.jar) 
	UCH	Photoptics{0.5.1.3.4} [Photoptics] (Photoptics-0.5.1.3.4.jar) 
	UCH	mc{1.6f} [Primordial Crops] (PrimordialCrops-1.6f.jar) 
	UCH	progressiveautomation{1.6.53} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.53.jar) 
	UCH	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCH	reborncore{2.8.1.64} [RebornCore] (RebornCore-1.10.2-2.8.1.64-universal.jar) 
	UCH	reborncore-mcmultipart{2.8.1.64} [reborncore-MCMultiPart] (RebornCore-1.10.2-2.8.1.64-universal.jar) 
	UCH	StorageDrawers{1.10.2-3.4.6} [Storage Drawers] (StorageDrawers-1.10.2-3.4.6.jar) 
	UCH	refinedstorage{1.2.4} [Refined Storage] (refinedstorage-1.2.4.jar) 
	UCH	xreliquary{1.10.2-1.3.3.585} [Reliquary] (Reliquary-1.10.2-1.3.3.585.jar) 
	UCH	rfbridge{1.0.0.1} [RF Bridge] (RF-Bridge-1.0.0.1.jar) 
	UCH	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCH	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCH	RTG{4.1.1.8-SNAPSHOT-1} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.8-SNAPSHOT-1.jar) 
	UCH	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCH	stellarsky{0.5.5.1.7} [Stellar Sky] (Stellar Sky-0.5.5.1.7.jar) 
	UCH	Streams{1.9.4} [Streams] (Streams-1.9.4-0.2.1.jar) 
	UCH	tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
	UCH	teslafied{1.0.0} [Teslafied] (teslafied-1.10.2-1.1.0.jar) 
	UCH	WailaHarvestability{1.1.9} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.9.jar) 
	UCH	xprings{1.2.0} [Experience Rings] (xprings-1.2.0.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
DepLoader (BrandonsCore-1.10.2-2.1.1.61-universal.jar)
  
MovingWorldCoreMod (movingworld-1.10.2-0003-full.jar)
  
FarseekCoreMod (Farseek-1.9.4-1.1.jar)
  farseek.core.FarseekClassTransformer
AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.4.jar)
  li.cil.oc.common.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.10-2.1.1.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
StreamsCoreMod (Streams-1.9.4-0.2.1.jar)
  streams.core.StreamsClassTransformer
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.73-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.4.3.124-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 375.95' Renderer: 'GeForce GTX 960/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	EnderIO: No known problems detected.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/BrandonsCore-1.10.2-2.1.1.61-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/Tesla.class
                  * Tesla API class 'TeslaCapabilities' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/capability/TeslaCapabilities.class
                  * Tesla API class 'ITeslaConsumer' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/ITeslaConsumer.class
                  * Tesla API class 'ITeslaHolder' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/ITeslaHolder.class
                  * Tesla API class 'ITeslaProducer' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/ITeslaProducer.class
                  * Tesla API class 'BaseTeslaContainer' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/BaseTeslaContainer.class
                  * Tesla API class 'BaseTeslaContainerProvider' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/BaseTeslaContainerProvider.class
                  * Tesla API class 'InfiniteTeslaConsumer' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaConsumer.class
                  * Tesla API class 'InfiniteTeslaConsumerProvider' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaConsumerProvider.class
                  * Tesla API class 'InfiniteTeslaProducer' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaProducer.class
                  * Tesla API class 'InfiniteTeslaProducerProvider' is loaded from: jar:file:/C:/Users/Matt/Documents/Curse/Minecraft/Instances/Minecraft%20Labs%20(1)%20(1)/mods/Tesla-1.10.2-1.2.1.49.jar!/net/darkhax/tesla/api/implementation/InfiniteTeslaProducerProvider.class
```

**Comment by covers1624** [comment]
Remove the duplicated CodeChickenLib from /mods/1.10/
