### ISSUE TITLE
1.10.2 - Server Crash Exception ticking world 	at com.brandon3055.draconicevolution.blocks.tileentity.TilePlacedItem.writeInventoryToNBT

### ISSUE THREAD

**Issue by ProsperCraft** [brandon3055/Draconic-Evolution#490]
This keeps happening, we just disable the deep resonance mod and its eleccore, one of the players had a couple crystals placed using draconic evolution, we suspect that is what is causing the crashes.

https://gist.github.com/ProsperCraft/d984d351b7e3b25c68241fc4b952e51b

Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
	at com.brandon3055.draconicevolution.blocks.tileentity.TilePlacedItem.writeInventoryToNBT(TilePlacedItem.java:265)
	at com.brandon3055.brandonscore.blocks.TileInventoryBase.writeDataToNBT(TileInventoryBase.java:171)
	at com.brandon3055.brandonscore.blocks.TileBCBase.func_189517_E_(TileBCBase.java:127)
	at net.minecraft.network.play.server.SPacketChunkData.<init>(SourceFile:52)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:156)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

**Comment by brandon3055** [comment]
This Should* be fixed in the latest version
