### ISSUE TITLE
Crash In Modpack

### ISSUE THREAD

**Issue by XxultramagexX** [brandon3055/Draconic-Evolution#553]
I'm making a small modpack, but it crashes due to an incompatibility. Here is crash report---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  LoadingHook (Mekanism-1.10.2-9.2.0.294.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.1.185-universal.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.3.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 1/21/17 4:31 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from CodeChicken Lib (CodeChickenLib)
Caused by: java.lang.NoClassDefFoundError: [Lcodechicken/lib/colour/Colour;
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetPublicMethods(Class.java:2894)
	at java.lang.Class.getMethods(Class.java:1607)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:83)
	at codechicken.lib.texture.TextureUtils.<clinit>(TextureUtils.java:41)
	at codechicken.lib.model.blockbakery.BlockBakery.init(BlockBakery.java:81)
	at codechicken.lib.internal.proxy.ClientProxy.preInit(ClientProxy.java:21)
	at codechicken.lib.CodeChickenLib.preInit(CodeChickenLib.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:614)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: codechicken.lib.colour.Colour
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NoClassDefFoundError: codechicken/lib/util/Copyable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 47 more
Caused by: java.lang.ClassNotFoundException: codechicken.lib.util.Copyable
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 51 more
Caused by: java.lang.SecurityException: class "codechicken.lib.util.Copyable"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 53 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 285069208 bytes (271 MB) / 852164608 bytes (812 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 44 mods loaded, 44 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCH	appliedenergistics2-core{rv4-alpha-9} [Applied Energistics 2 Core] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.1.185-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	appliedenergistics2{rv4-alpha-9} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-9.jar) 
	UCH	Psi{r1.0-41} [Psi] (Psi-r1.0-41.jar) 
	UCH	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCE	CodeChickenLib{2.5.1.185} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.1.185-universal.jar) 
	UCE	brandonscore{2.1.3} [Brandon's Core] (BrandonsCore-1.10.2-2.1.3.82-universal.jar) 
	UCH	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCH	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCH	JEI{3.13.2.360} [Just Enough Items] (jei_1.10.2-3.13.2.360.jar) 
	UCH	mcmultipart{1.2.0_74} [MCMultiPart] (MCMultiPart-experimental-1.2.0_74-universal.jar) 
	UCH	chiselsandbits{12.7} [Chisels & Bits] (chiselsandbits-12.7.jar) 
	UCE	draconicevolution{2.0.6} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.6.157-universal.jar) 
	UCH	StorageDrawers{1.10.2-3.4.2} [Storage Drawers] (StorageDrawers-1.10.2-3.4.2.jar) 
	UCH	bitdrawers{0.32} [Drawers & Bits] (DrawersBits-1.10.2-0.32.jar) 
	UCH	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCH	EnderIO{1.10.2-3.0.1.126_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.126_beta.jar) 
	UCH	shetiphiancore{3.3.3} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.3.jar) 
	UCH	endertanks{1.4.3} [EnderTanks] (endertanks-1.10.0-1.4.3.jar) 
	UCH	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.1.jar) 
	UCH	zerocore{1.10.2-0.0.8.0} [Zero CORE] (zerocore-1.10.2-0.0.8.0.jar) 
	UCH	bigreactors{0.4.5.18} [Extreme Reactors] (ExtremeReactors-1.10.2-0.4.5.18.jar) 
	UCH	flighttweaks{0.0.6-alpha} [Flight Tweaks] (flighttweaks-1.10.2-0.0.6-alpha.jar) 
	UCH	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.1.4.jar) 
	UCH	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.1.4.jar) 
	UCH	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCH	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCH	jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
	UCH	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCH	Mekanism{9.2.0} [Mekanism] (Mekanism-1.10.2-9.2.0.294.jar) 
	UCH	MekanismGenerators{9.2.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.2.0.294.jar) 
	UCH	MekanismTools{9.2.0} [MekanismTools] (MekanismTools-1.10.2-9.2.0.294.jar) 
	UCH	rftools{5.59} [RFTools] (rftools-1.10-5.59.jar) 
	UCH	rftoolscontrol{1.5.2} [RFTools Control] (rftoolsctrl-1.10-1.5.2.jar) 
	UCH	rftoolsdim{4.45} [RFTools Dimensions] (rftoolsdim-1.10-4.45.jar) 
	UCH	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCH	TinkersAddons{1.0.3} [Tinkers' Addons] (Tinkers' Addons-1.10.x-1.0.3.jar) 
	UCH	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCH	Torcherino{4.2s} [Torcherino] (Torcherino-4.2s.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
LoadingHook (Mekanism-1.10.2-9.2.0.294.jar)
  
Brandon's Core (BrandonsCore-1.10.2-2.1.3.82-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.58-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.1.185-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
AppEngCore (appliedenergistics2-rv4-alpha-9.jar)
  appeng.coremod.asm.ASMIntegration
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.3.jar)
  shetiphian.core.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.201.1101.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
	AE2 Version: alpha rv4-alpha-9 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * An unsupportted RF API is installed (1.7.10R1.3.1 from (guessing) jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/CoFHAPIProps.class).
                    Ender IO needs at least 1.8.9R1.2.0B1 and will NOT work with older versions.
                  * An unknown AE2 API is installed (rv4 from appliedenergistics2-rv4-alpha-9.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/Xxult/Desktop/MPacks%20Lite/Psychic%20Construct/mods/BrandonsCore-1.10.2-2.1.3.82-universal.jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

**Comment by covers1624** [comment]
Remove any version of CCL fron /mods/1.10.2. Ensure the only version of CCL you have is in the /mods folder.

**Comment by XxultramagexX** [comment]
OK
