### ISSUE TITLE
Can't launch the game!

### ISSUE THREAD

**Issue by Voidrainbows** [brandon3055/Draconic-Evolution#558]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 1/23/17 9:33 PM
Description: Initializing game

java.lang.NoSuchMethodError: com.brandon3055.draconicevolution.common.blocks.ChaosShardAtmos.setTickRandomly(Z)Lnet/minecraft/block/Block;
	at com.brandon3055.draconicevolution.common.blocks.ChaosShardAtmos.<init>(ChaosShardAtmos.java:18)
	at com.brandon3055.draconicevolution.common.ModBlocks.<clinit>(ModBlocks.java:53)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:554)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I always keep getting this error. pls help

**Comment by covers1624** [comment]
We will need your full crash report in order to help. Please use a service lile pastebin.com and provide us with the full crash report.

**Comment by Voidrainbows** [comment]
terribly sorry i am very bad at this... http://pastebin.com/dr9AaYEE

**Comment by brandon3055** [comment]
you are using the -deobf jar. This is only for other mod developers to use in a obfuscated dev environment. you need the -universal jar
