### ISSUE TITLE
[1.10] Max Payload on Infusion Crafter

### ISSUE THREAD

**Issue by tedsenft** [brandon3055/Draconic-Evolution#562]
Accidentally placed an RF Tools storage tablet with ~60 items on it on an infusion pedestal. The second I looked at it with WAILA (didn't even open it, though it was probably a packet issue) I was booted with a MAX PAYLOAD error.

This is a common packet issue; details are as follows:
BDLib 1.12.2.20
Brandon's Core 2.1.3.82
Draconic Evolution 2.0.7.168
TheOneProbe 1.3.3
Waila 1.7.0-B3_1.9.4
WAWLA 2.3.1.214

**Comment by covers1624** [comment]
We need your log in order to do anything.

**Comment by tedsenft** [comment]
Warning ya, the only thing I have in my log that's even slightly related will probably be utterly useless to you.

Here's the stack trace:
```
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28) ~[it.class:?]
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:143) ~[FMLProxyPacket.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:527) ~[NetworkDispatcher.class:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741) ~[AbstractChannelHandlerContext.class:4.0.23.Final]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895) ~[DefaultChannelPipeline.class:4.0.23.Final]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240) ~[AbstractChannel.class:4.0.23.Final]
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:247) [eo$4.class:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [SingleThreadEventExecutor.class:4.0.23.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [NioEventLoop.class:4.0.23.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [SingleThreadEventExecutor$2.class:4.0.23.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_112]
```

That's it. I'm a mod developer and have had others looking at this too- it's an issue of packet size. The item doesn't matter, the NBT mattered.

If you need a full mod list, I can get you it.

**Comment by brandon3055** [comment]
This is an issue with the RFTools tablet. Basically the tablet is storing soo much data that it is exceeding that max packet size when that data is sent to the client. Im guessing your tablet contains a lot of items that have large NBT tags? Anyway there is nothing i can do on my end.

To fix this the @McJty needs to override getNBTShareTag in the tablet item and only send that data that the client needs.
