### ISSUE TITLE
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer at com.brandon3055.draconicevolution.entity.EntityGuardianCrystal.func_70071_h_(EntityGuardianCrystal.java:87)

### ISSUE THREAD

**Issue by frenzye** [brandon3055/Draconic-Evolution#573]
Time: 1/31/17 7:52 PM
Description: Ticking entity
 
java.lang.ClassCastException: java.lang.Float cannot be cast to java.lang.Integer
    at com.brandon3055.draconicevolution.entity.EntityGuardianCrystal.func_70071_h_(EntityGuardianCrystal.java:87)
    at net.minecraft.world.World.func_72866_a(World.java:1964)
    at net.minecraft.world.World.func_72870_g(World.java:1934)
    at net.minecraft.world.World.func_72939_s(World.java:1750)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

http://pastebin.com/w2TcA9AV

**Comment by brandon3055** [comment]
Can you give me any details about what you where doing when this happened? I have seen something like this before but it was with vanilla entities and i have no idea what caused it. Possibly some corrupted data somwear.

**Comment by frenzye** [comment]
Player says he was flying near an asteroid belt, and perhaps the chaos dragon, and this happened. Loading the chunk would result in the above crash. I edited the player dat location and ended up deleting the end to fix it. I just went back to the chaos dragon and didn't crash.

**Comment by brandon3055** [comment]
This happened to me with a vanilla dragon breath effect entity. I think it happened when i was screwing around with the world save.

**Comment by frenzye** [comment]
I haven't touched the world saves, and it happened again last night with a different player. He says it was the same log? How likely is this a conflict with another mod? It would be difficult to test for since it doesn't seem to happen everytime.

**Comment by brandon3055** [comment]
It could be that another mod is looking at the dataManager sideways.

**Comment by frenzye** [comment]
full crash log http://pastebin.com/YspMSS1e
