### ISSUE TITLE
Entity Detector Crashes Game

### ISSUE THREAD

**Issue by DigitalSketch** [brandon3055/Draconic-Evolution#592]
I'm working with the SkyFactory 3 (version 3.0.5) mod pack, and running Draconic Evolution 1.10.2-2.0.1.168.  When I click on the "+ Entity" to add an entity to the list, the game crashes.  If it helps, I only have "Hostile" mobs active when I click on the button.

**Comment by Elvarion** [comment]
I am able to press the +Entity and +Player button, but there is nothing you can do in the meny.
(Not sure what is supposed to be there)

Using
- DRACONIC-EVOLUTION-1.10.2-2.0.7.168-UNIVERSAL
- BRANDONSCORE-1.10.2-2.1.3.82-UNIVERSAL

Using the +Custom works with mobs/passive mobs and players. So if you crash when using the +Entity just use the +Custom and add what you wanna track.

**Comment by brandon3055** [comment]
Crash report or it didnt happen.

**Comment by DigitalSketch** [comment]
[12:30:19] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1121) ~[bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_111]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:25) ~[GameProfile.class:?]
	at ganymedes01.headcrumbs.entity.EntityHuman.getProfile(EntityHuman.java:473) ~[EntityHuman.class:?]
	at ganymedes01.headcrumbs.renderers.RenderHuman.setModel(RenderHuman.java:77) ~[RenderHuman.class:?]
	at ganymedes01.headcrumbs.renderers.RenderHuman.doRender(RenderHuman.java:50) ~[RenderHuman.class:?]
	at ganymedes01.headcrumbs.renderers.RenderHuman.func_76986_a(RenderHuman.java:21) ~[RenderHuman.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366) ~[bsh.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiEntityRenderer.renderBackgroundLayer(MGuiEntityRenderer.java:78) ~[MGuiEntityRenderer.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.MGuiElementBase.renderBackgroundLayer(MGuiElementBase.java:345) ~[MGuiElementBase.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiLabel.renderBackgroundLayer(MGuiLabel.java:36) ~[MGuiLabel.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.MGuiElementBase.renderBackgroundLayer(MGuiElementBase.java:345) ~[MGuiElementBase.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiList.renderBackgroundLayer(MGuiList.java:101) ~[MGuiList.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiSelectDialog.renderBackgroundLayer(MGuiSelectDialog.java:45) ~[MGuiSelectDialog.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.ModuleManager.renderBackgroundLayer(ModuleManager.java:188) ~[ModuleManager.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiContainer.renderBackgroundLayer(ModularGuiContainer.java:168) ~[ModularGuiContainer.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiContainer.func_146976_a(ModularGuiContainer.java:146) ~[ModularGuiContainer.class:?]
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:76) ~[bgl.class:?]
	at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiContainer.func_73863_a(ModularGuiContainer.java:161) ~[ModularGuiContainer.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) ~[ForgeHooksClient.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) ~[bnz.class:?]
	... 9 more

**Comment by brandon3055** [comment]
Ok i think i found the problem. WIll be fixed in the next release.
