### ISSUE TITLE
game charsh when i start it there is no crash report or idk how to get it...

### ISSUE THREAD

**Issue by BluieMBA** [brandon3055/Draconic-Evolution#661]
newst everything

**Comment by ktole1999** [comment]
error is in the launcher console. need to edit profile and select option to reopen launcher on game exit. then copy/paste error to pastebin.com and share the link.

**Comment by BluieMBA** [comment]
ok

**Comment by BluieMBA** [comment]
![2017-03-22_19-18-03](https://cloud.githubusercontent.com/assets/26604610/24208342/7372db76-0f34-11e7-84a8-accb5c58d309.png)

**Comment by BluieMBA** [comment]
![2017-03-22_19-19-53](https://cloud.githubusercontent.com/assets/26604610/24208400/9727bcb2-0f34-11e7-9014-8a33ea73645f.png)

**Comment by BluieMBA** [comment]
look

**Comment by BluieMBA** [comment]
@ktole1999

**Comment by BluieMBA** [comment]
help?

**Comment by BluieMBA** [comment]
i got this in minecraft folder

[19:24:08] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:24:08] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[19:24:08] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[19:24:08] [main/INFO]: Forge Mod Loader version 12.18.3.2185 for Minecraft 1.10.2 loading
[19:24:08] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Program Files (x86)\Minecraft\runtime\jre-x64\1.8.0_25
[19:24:08] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:24:08] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[19:24:08] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:24:08] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[19:24:08] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:24:10] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[19:24:10] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[19:24:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:24:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NoClassDefFoundError: codechicken/lib/asm/ModularASMTransformer$ClassNodeTransformer
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.getConstructor0(Class.java:3067)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:408)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:237)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at $wrapper.com.brandon3055.brandonscore.asm.ClassTransformer.<init>(Unknown Source)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:438)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:131)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.ClassNotFoundException: codechicken.lib.asm.ModularASMTransformer$ClassNodeTransformer
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[19:24:10] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 15 more
[19:24:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.NullPointerException
[19:24:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[19:24:10] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 17 more

**Comment by BluieMBA** [comment]
please @ktole1999 @brandon3055 @all

**Comment by ktole1999** [comment]
java.lang.ClassNotFoundException: codechicken.lib. what mods are in your pack?

**Comment by BluieMBA** [comment]
oh i need the chicken core!

**Comment by BluieMBA** [comment]
sorry did not know that

**Comment by covers1624** [comment]
Not core, Lib. you can find it here: https://minecraft.curseforge.com/projects/codechicken-lib-1-8

**Comment by BluieMBA** [comment]
ok
