### ISSUE TITLE
Draconic Evolution doesn't respect shader settings / doesn't handle rendering errors

### ISSUE THREAD

**Issue by curiosity-a** [brandon3055/Draconic-Evolution#682]
Since my graphics card doesn't support shaders, I have disabled them like this:

    # This allowes you to just disable the energy crystal shader which can be a lot lagier than the reactor since there are usually a lot more of them (The fallback crystal texture is not soooo bad...)
    B:useCrystalShaders=false

    # Set this to false if your system can not handle the awesomeness that is shaders! (Warning will make cool things look like crap)
    B:useShaders=false

When I was browsing JEI, the game crashed with the following error:

    java.lang.ExceptionInInitializerError
    	at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.bindShader(RenderItemEnergyCrystal.java:149)`
Despite shaders being disabled in config, Draconic Evolution tries to create them and crashes when the attempt fails.

**Comment by curiosity-a** [comment]
Tried the new version. The old issue is gone, but it can't render the crystal still:

	[23:20:30] [Client thread/ERROR] [JEI/]: Rendering ingredient crashed: 1xtile.draconicevolution:energy_crystal@0 draconicevolution:energy_crystal
	net.minecraft.util.ReportedException: Rendering item
		at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:305) ~[RenderItemWrapper.class:?]
		at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:27) ~[ItemStackRenderer.class:?]
		at mezz.jei.plugins.vanilla.ingredients.ItemStackRenderer.render(ItemStackRenderer.java:21) ~[ItemStackRenderer.class:?]
		at mezz.jei.gui.ingredients.GuiIngredientFast.renderSlow(GuiIngredientFast.java:181) [GuiIngredientFast.class:?]
		at mezz.jei.gui.ingredients.GuiIngredientFast.renderSlow(GuiIngredientFast.java:170) [GuiIngredientFast.class:?]
		at mezz.jei.gui.ingredients.GuiIngredientFastList.render(GuiIngredientFastList.java:194) [GuiIngredientFastList.class:?]
		at mezz.jei.gui.ItemListOverlayInternal.drawScreen(ItemListOverlayInternal.java:305) [ItemListOverlayInternal.class:?]
		at mezz.jei.GuiEventHandler.onDrawBackgroundEventPost(GuiEventHandler.java:89) [GuiEventHandler.class:?]
		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_747_GuiEventHandler_onDrawBackgroundEventPost_BackgroundDrawnEvent.invoke(.dynamic) [?:?]
		at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
		at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) [EventBus.class:?]
		at net.minecraft.client.gui.GuiScreen.func_146276_q_(GuiScreen.java:590) [bft.class:?]
		at mezz.jei.gui.recipes.RecipesGui.func_73863_a(RecipesGui.java:168) [RecipesGui.class:?]
		at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
		at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) [bnz.class:?]
		at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
		at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
		at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
		at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
		at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
		at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	Caused by: java.lang.ExceptionInInitializerError
		at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.bindShader(RenderItemEnergyCrystal.java:147) ~[RenderItemEnergyCrystal.class:?]
		at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.renderItem(RenderItemEnergyCrystal.java:130) ~[RenderItemEnergyCrystal.class:?]
		at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86) ~[CCRenderItem.class:?]
		at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:167) ~[CCRenderItem.class:?]
		at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:231) ~[CCRenderItem.class:?]
		at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:293) ~[RenderItemWrapper.class:?]
		... 23 more
	Caused by: java.lang.RuntimeException: Error compiling shader: ERROR: 0:1: '' :  Version number not supported by GL2
	ERROR: 0:24: 'min' : no matching overloaded function found 
	ERROR: 0:24: 'max' : no matching overloaded function found 
	ERROR: 0:25: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
	ERROR: 0:25: '-' :  wrong operand types  no operation '-' exists that takes a left-hand operand of type 'const int' and a right operand of type 'float' (or there is no acceptable conversion)
	ERROR: 0:25: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'float' and a right operand of type 'const int' (or there is no acceptable conversion)
	ERROR: 0:25: 'max' : no matching overloaded function found 
	ERROR: 0:25: 'max' : no matching overloaded function found 
	ERROR: 0:27: 'min' : no matching overloaded function found 
	ERROR: 0:27: '*' :  wrong operand types  no operation '*' exists that takes a left-hand operand of type 'const float' and a right operand of type 'const int' (or there is no acceptable conversion)
	ERROR: 0:29: '=' :  cannot convert from 'const int' to 'float'
	ERROR: 0:32: 'pow' : no matching overloaded function found 
	ERROR: 0:33: '+' :  wrong operand types  no operation '+' exists that takes a left-hand operand of type 'const int' and a right operand of type 'float' (or there is no acceptable conversion)
	ERROR: 0:33: 'max' : no matching overloaded function found 
	 
		at codechicken.lib.render.shader.ShaderProgram.attach(ShaderProgram.java:105) ~[ShaderProgram.class:?]
		at codechicken.lib.render.shader.ShaderProgram.attach(ShaderProgram.java:82) ~[ShaderProgram.class:?]
		at codechicken.lib.render.shader.ShaderProgram.attachFrag(ShaderProgram.java:73) ~[ShaderProgram.class:?]
		at com.brandon3055.draconicevolution.client.render.shaders.DEShaders.initReactorShader(DEShaders.java:59) ~[DEShaders.class:?]
		at com.brandon3055.draconicevolution.client.render.shaders.DEShaders.<clinit>(DEShaders.java:44) ~[DEShaders.class:?]
		at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.bindShader(RenderItemEnergyCrystal.java:147) ~[RenderItemEnergyCrystal.class:?]
		at com.brandon3055.draconicevolution.client.render.item.RenderItemEnergyCrystal.renderItem(RenderItemEnergyCrystal.java:130) ~[RenderItemEnergyCrystal.class:?]
		at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86) ~[CCRenderItem.class:?]
		at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:167) ~[CCRenderItem.class:?]
		at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:231) ~[CCRenderItem.class:?]
		at net.darkhax.bookshelf.client.render.item.RenderItemWrapper.func_184391_a(RenderItemWrapper.java:293) ~[RenderItemWrapper.class:?]
		... 23 more
