### ISSUE TITLE
Wireless crystal crash with Draconic and XU2

### ISSUE THREAD

**Issue by checkium** [brandon3055/Draconic-Evolution#700]
When any energy crystal in the world is loaded, the server crashes with this error:
`
net.minecraft.util.ReportedException: Exception ticking world
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:704) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=tier, clazz=class java.lang.Integer, values=[0, 1, 2]} as it does not exist in XUBlockStateCreator{block=extrautils2:scanner, properties=[facing]}
at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
at com.brandon3055.draconicevolution.blocks.energynet.tileentity.TileCrystalBase.getTier(TileCrystalBase.java:354) ~[TileCrystalBase.class:?]
at com.brandon3055.draconicevolution.blocks.energynet.tileentity.TileCrystalBase.writeRetainedData(TileCrystalBase.java:532) ~[TileCrystalBase.class:?]
at com.brandon3055.brandonscore.blocks.TileBCBase.func_189517_E_(TileBCBase.java:141) ~[TileBCBase.class:?]
at net.minecraft.network.play.server.SPacketChunkData.(SourceFile:52) ~[gt.class:?]
at net.minecraft.server.management.PlayerChunkMapEntry.func_187272_b(PlayerChunkMapEntry.java:156) ~[lx.class:?]
at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:165) ~[ly.class:?]
at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222) ~[ls.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698) ~[MinecraftServer.class:?]
... 4 more`

This started to happen after a level.dat corruption where I had to replace level.dat with level.dat_old

**Comment by covers1624** [comment]
Please provide your crash via pastebin.com That is basically unreadable with githubs formatting.

**Comment by brandon3055** [comment]
What version of DE are you using? This should have been fixed a few versions back.
