### ISSUE TITLE
Draconic Evolution 2.0.12.222 Crashes on Startup in Minecraft

### ISSUE THREAD

**Issue by F4RSAKE** [brandon3055/Draconic-Evolution#749]
I was going to make a modpack on _1.10.2_ and then it crashed
I took out the Draconic Evolution and the Brandon's Core and it seems to work fine.
But I think the new version of the mod makes it crash :(
I tried downgrading both the mod and Brandon's Core but nothing changed ;-;
The version of Brandon's Core is 2.1.7.102
both mods are "-universal"

Please help D:

Crash Report:

**---- Minecraft Crash Report ----

WARNING: coremods are present:
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.1.7.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.7.102-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  IC2core (industrialcraft-2-2.6.188-ex110.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 15.05.2017 18:52
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Draconic Evolution (draconicevolution)
Caused by: java.lang.ExceptionInInitializerError
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at sun.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(Unknown Source)
	at sun.reflect.ReflectionFactory.newFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.getFieldAccessor(Unknown Source)
	at java.lang.reflect.Field.get(Unknown Source)
	at com.brandon3055.brandonscore.config.ModFeatureParser.loadFeatures(ModFeatureParser.java:63)
	at com.brandon3055.draconicevolution.DraconicEvolution.preInit(DraconicEvolution.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:616)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:624)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:259)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Block: class com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal has property: type with invalidly named value: crystal_ıo
	at net.minecraft.block.state.BlockStateContainer.func_185919_a(BlockStateContainer.java:115)
	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:75)
	at net.minecraft.block.state.BlockStateContainer.<init>(BlockStateContainer.java:60)
	at com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal.func_180661_e(EnergyCrystal.java:87)
	at net.minecraft.block.Block.<init>(Block.java:225)
	at net.minecraft.block.Block.<init>(Block.java:234)
	at com.brandon3055.brandonscore.blocks.BlockBCore.<init>(BlockBCore.java:48)
	at com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal.<init>(EnergyCrystal.java:56)
	at com.brandon3055.draconicevolution.DEFeatures.<clinit>(DEFeatures.java:109)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6948401224 bytes (6626 MB) / 8232370176 bytes (7851 MB) up to 8232370176 bytes (7851 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -Xms8G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2254 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2254.jar) 
	UCH	Forge{12.18.3.2254} [Minecraft Forge] (forge-1.10.2-12.18.3.2254.jar) 
	UCH	AdvancedRocketryCore{1} [Advanced Rocketry] (minecraft.jar) 
	UCH	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCH	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCH	IC2{2.6.188-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.188-ex110.jar) 
	UCH	advanced_machines{60.0.2} [Advanced Machines] (Advanced Machines-60.0.2.jar) 
	UCH	libVulpes{0.2.2.20170409194831} [libVulpes] (LibVulpes-1.10.2-0.2.2-universal.jar) 
	UCH	advancedRocketry{1.1.7} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.1.7.jar) 
	UCH	CodeChickenLib{2.5.8.255} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCH	brandonscore{9.9.9} [Brandon's Core] (BrandonsCore-1.10.2-2.1.7.102-universal.jar) 
	UCH	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCE	draconicevolution{2.0.12} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.12.222-universal.jar) 
	Loaded coremods (and transformers): 
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.1.7.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.7.102-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
IC2core (industrialcraft-2-2.6.188-ex110.jar)
  
	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports:**

**Comment by brandon3055** [comment]
Hmm... i have no idea why your getting that crash... Can you also show me your startup log please. I recommend using pastebin or something for errors/logs
https://pastebin.com/

**Comment by brandon3055** [comment]
Closed because no reply from OP

**Comment by yusufkandemir** [comment]
> `java.lang.IllegalArgumentException: Block: class com.brandon3055.draconicevolution.blocks.energynet.EnergyCrystal has property: type with invalidly named value: crystal_ıo`

The problem here is localization. The letter `ı` is suspicious. A **fix** to this might be adding `-Duser.country=US -Duser.language=en` as launch parameters. I experienced this issue with a forge server instance and fixed by adding these.

**Comment by umutcantkn** [comment]
-Duser.country=US -Duser.language=en where do i paste it ? Settings.cfg ?

**Comment by yusufkandemir** [comment]
> -Duser.country=US -Duser.language=en where do i paste it ? Settings.cfg ?

It depends on what you are using as launcher.

### Twitch App Settings
![image](https://user-images.githubusercontent.com/6266078/55851682-53102380-5b62-11e9-918b-fbff5ad910c2.png)

### Up-to-date Minecraft Launcher
![image](https://user-images.githubusercontent.com/6266078/55851576-ebf26f00-5b61-11e9-86df-07795e9da5a0.png)

### Old Minecraft Launcher
![image](https://user-images.githubusercontent.com/6266078/55851446-49d28700-5b61-11e9-8752-5e2452f3770c.png)
