### ISSUE TITLE
Crash while viewing draconic tablet when mob soul cycles to Headcrumbs Human

### ISSUE THREAD

**Issue by TeetoKaziim** [brandon3055/Draconic-Evolution#784]
## Description
When browsing the draconic information tablet, the game will crash if the mob soul entry's icon cycles to a Headcrumbs human.

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2297 AND 12.18.3.2316
* TolkienCraft II version: Not Applicable

## Crash report
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Brandon's Core (BrandonsCore-1.10.2-2.1.8.107-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 6/13/17 4:45 PM
Description: Rendering entity in world

java.lang.IllegalArgumentException: Name and ID cannot both be blank
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:25)
	at ganymedes01.headcrumbs.entity.EntityHuman.getProfile(EntityHuman.java:473)
	at ganymedes01.headcrumbs.renderers.RenderHuman.setModel(RenderHuman.java:77)
	at ganymedes01.headcrumbs.renderers.RenderHuman.doRender(RenderHuman.java:50)
	at ganymedes01.headcrumbs.renderers.RenderHuman.func_76986_a(RenderHuman.java:21)
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at com.brandon3055.draconicevolution.client.render.item.RenderItemMobSoul.renderItem(RenderItemMobSoul.java:99)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86)
	at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:167)
	at codechicken.lib.render.item.CCRenderItem.func_175042_a(CCRenderItem.java:211)
	at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiStackIcon.renderBackgroundLayer(MGuiStackIcon.java:56)
	at com.brandon3055.brandonscore.client.gui.modulargui.MGuiElementBase.renderBackgroundLayer(MGuiElementBase.java:354)
	at com.brandon3055.draconicevolution.client.gui.modwiki.moddata.guidoctree.TreeBranchContent.renderBackgroundLayer(TreeBranchContent.java:150)
	at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiList.renderBackgroundLayer(MGuiList.java:115)
	at com.brandon3055.draconicevolution.client.gui.modwiki.WikiContentList.renderBackgroundLayer(WikiContentList.java:166)
	at com.brandon3055.brandonscore.client.gui.modulargui.ModuleManager.renderBackgroundLayer(ModuleManager.java:190)
	at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiScreen.renderBackgroundLayer(ModularGuiScreen.java:155)
	at com.brandon3055.draconicevolution.client.gui.modwiki.GuiModWiki.renderBackgroundLayer(GuiModWiki.java:98)
	at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiScreen.func_73863_a(ModularGuiScreen.java:147)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.mojang.authlib.GameProfile.<init>(GameProfile.java:25)
	at ganymedes01.headcrumbs.entity.EntityHuman.getProfile(EntityHuman.java:473)
	at ganymedes01.headcrumbs.renderers.RenderHuman.setModel(RenderHuman.java:77)
	at ganymedes01.headcrumbs.renderers.RenderHuman.doRender(RenderHuman.java:50)
	at ganymedes01.headcrumbs.renderers.RenderHuman.func_76986_a(RenderHuman.java:21)

-- Entity being rendered --
Details:
	Entity Type: headcrumbs.Human (ganymedes01.headcrumbs.entity.EntityHuman)
	Entity ID: 8806
	Entity Name: 
	Entity's Exact location: 0.00, 0.00, 0.00
	Entity's Block location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null

-- Renderer details --
Details:
	Assigned renderer: ganymedes01.headcrumbs.renderers.RenderHuman@4bf12c48
	Location: 0.00,0.00,0.00 - World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: 0.0
	Delta: 1.0
Stacktrace:
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:366)
	at com.brandon3055.draconicevolution.client.render.item.RenderItemMobSoul.renderItem(RenderItemMobSoul.java:99)
	at codechicken.lib.render.item.CCRenderItem.func_180454_a(CCRenderItem.java:86)
	at codechicken.lib.render.item.CCRenderItem.func_184390_a(CCRenderItem.java:167)
	at codechicken.lib.render.item.CCRenderItem.func_175042_a(CCRenderItem.java:211)
	at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiStackIcon.renderBackgroundLayer(MGuiStackIcon.java:56)
	at com.brandon3055.brandonscore.client.gui.modulargui.MGuiElementBase.renderBackgroundLayer(MGuiElementBase.java:354)
	at com.brandon3055.draconicevolution.client.gui.modwiki.moddata.guidoctree.TreeBranchContent.renderBackgroundLayer(TreeBranchContent.java:150)
	at com.brandon3055.brandonscore.client.gui.modulargui.modularelements.MGuiList.renderBackgroundLayer(MGuiList.java:115)
	at com.brandon3055.draconicevolution.client.gui.modwiki.WikiContentList.renderBackgroundLayer(WikiContentList.java:166)
	at com.brandon3055.brandonscore.client.gui.modulargui.ModuleManager.renderBackgroundLayer(ModuleManager.java:190)
	at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiScreen.renderBackgroundLayer(ModularGuiScreen.java:155)
	at com.brandon3055.draconicevolution.client.gui.modwiki.GuiModWiki.renderBackgroundLayer(GuiModWiki.java:98)
	at com.brandon3055.brandonscore.client.gui.modulargui.ModularGuiScreen.func_73863_a(ModularGuiScreen.java:147)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)

-- Screen render details --
Details:
	Screen name: com.brandon3055.draconicevolution.client.gui.modwiki.GuiModWiki
	Mouse location: Scaled: (122, 189). Absolute: (245, 371)
	Screen size: Scaled: (680, 375). Absolute: (1360, 749). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Teeto_K'/903, l='MpServer', x=-229.80, y=101.00, z=84.86]]
	Chunk stats: MultiplayerChunkCache: 581, 581
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-216,64,76), Chunk: (at 8,4,12 in -14,4; contains blocks -224,0,64 to -209,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 559 game time, 559 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 128 total; [EntityPig['Pig'/90, l='MpServer', x=-307.50, y=69.00, z=13.50], EntityPig['Pig'/91, l='MpServer', x=-300.72, y=69.00, z=20.35], EntityPig['Pig'/92, l='MpServer', x=-300.88, y=69.00, z=18.44], EntityPig['Pig'/93, l='MpServer', x=-307.30, y=69.00, z=8.79], EntityChicken['Chicken'/94, l='MpServer', x=-301.50, y=84.00, z=143.50], EntityBat['Bat'/4190, l='MpServer', x=-252.25, y=34.10, z=143.48], EntityBat['Bat'/4191, l='MpServer', x=-256.73, y=32.85, z=143.84], EntityChicken['Chicken'/95, l='MpServer', x=-299.50, y=85.00, z=145.48], EntityChicken['Chicken'/96, l='MpServer', x=-299.50, y=85.00, z=144.92], EntityChicken['Chicken'/97, l='MpServer', x=-297.50, y=85.00, z=145.50], EntityChicken['Chicken'/114, l='MpServer', x=-279.49, y=81.00, z=96.48], EntityHuman['EcuTruin'/4210, l='MpServer', x=-234.50, y=18.00, z=72.50], EntityChicken['Chicken'/115, l='MpServer', x=-275.50, y=80.00, z=92.50], EntityChicken['Chicken'/116, l='MpServer', x=-266.58, y=84.00, z=88.50], EntityChicken['Chicken'/117, l='MpServer', x=-277.56, y=80.00, z=93.80], EntityChicken['Chicken'/118, l='MpServer', x=-278.50, y=79.00, z=111.50], EntityChicken['Chicken'/119, l='MpServer', x=-277.50, y=79.00, z=112.50], EntityChicken['Chicken'/120, l='MpServer', x=-276.50, y=79.00, z=116.50], EntityChicken['Chicken'/121, l='MpServer', x=-272.56, y=78.00, z=114.17], EntitySheep['Sheep'/122, l='MpServer', x=-266.50, y=78.00, z=115.50], EntitySheep['Sheep'/123, l='MpServer', x=-268.98, y=78.00, z=114.07], EntitySheep['Sheep'/124, l='MpServer', x=-275.22, y=79.00, z=110.82], EntitySheep['Sheep'/125, l='MpServer', x=-264.79, y=78.00, z=109.79], EntityCow['Cow'/134, l='MpServer', x=-263.48, y=75.00, z=25.22], EntityCow['Cow'/135, l='MpServer', x=-260.50, y=74.00, z=22.55], EntityCow['Cow'/136, l='MpServer', x=-263.41, y=72.00, z=20.52], EntityCow['Cow'/137, l='MpServer', x=-260.50, y=74.00, z=21.49], EntityChicken['Chicken'/146, l='MpServer', x=-238.50, y=93.00, z=164.50], EntityChicken['Chicken'/147, l='MpServer', x=-236.50, y=93.00, z=162.50], EntityChicken['Chicken'/148, l='MpServer', x=-235.50, y=93.00, z=161.50], EntityChicken['Chicken'/149, l='MpServer', x=-236.50, y=93.00, z=162.50], EntityChicken['Chicken'/160, l='MpServer', x=-202.50, y=75.00, z=143.50], EntityChicken['Chicken'/161, l='MpServer', x=-205.50, y=75.00, z=146.50], EntityChicken['Chicken'/162, l='MpServer', x=-207.50, y=76.00, z=142.50], EntityChicken['Chicken'/163, l='MpServer', x=-205.50, y=76.00, z=141.50], EntityCow['Cow'/168, l='MpServer', x=-197.42, y=65.00, z=31.21], EntityCow['Cow'/169, l='MpServer', x=-194.50, y=66.00, z=23.50], EntityCow['Cow'/170, l='MpServer', x=-186.53, y=67.00, z=16.85], EntityCow['Cow'/171, l='MpServer', x=-195.50, y=68.00, z=15.50], EntityCow['Cow'/172, l='MpServer', x=-193.33, y=64.00, z=62.00], EntityCow['Cow'/173, l='MpServer', x=-193.53, y=64.00, z=59.85], EntityCow['Cow'/174, l='MpServer', x=-198.20, y=64.00, z=65.39], EntityCow['Cow'/175, l='MpServer', x=-191.80, y=64.00, z=64.41], EntityChicken['Chicken'/176, l='MpServer', x=-190.50, y=80.00, z=92.50], EntityChicken['Chicken'/177, l='MpServer', x=-186.51, y=80.00, z=93.69], EntityChicken['Chicken'/178, l='MpServer', x=-192.20, y=81.00, z=97.13], EntityChicken['Chicken'/179, l='MpServer', x=-179.89, y=80.00, z=99.10], EntityChicken['Chicken'/180, l='MpServer', x=-184.50, y=78.00, z=131.50], EntityChicken['Chicken'/181, l='MpServer', x=-186.50, y=78.00, z=132.50], EntityChicken['Chicken'/182, l='MpServer', x=-194.44, y=80.00, z=125.50], EntityChicken['Chicken'/183, l='MpServer', x=-190.50, y=78.00, z=131.50], EntityChicken['Chicken'/188, l='MpServer', x=-174.50, y=81.00, z=116.85], EntityChicken['Chicken'/189, l='MpServer', x=-173.50, y=80.00, z=121.65], EntityChicken['Chicken'/190, l='MpServer', x=-162.71, y=79.00, z=129.14], EntityChicken['Chicken'/191, l='MpServer', x=-174.50, y=80.00, z=120.50], EntityChicken['Chicken'/195, l='MpServer', x=-158.10, y=77.00, z=134.75], EntityChicken['Chicken'/196, l='MpServer', x=-163.19, y=73.00, z=147.36], EntityChicken['Chicken'/197, l='MpServer', x=-156.70, y=76.00, z=137.60], EntityChicken['Chicken'/198, l='MpServer', x=-160.16, y=77.00, z=134.90], EntityBat['Bat'/2258, l='MpServer', x=-304.30, y=32.70, z=142.53], EntityZombie['Zombie'/4351, l='MpServer', x=-270.50, y=29.00, z=82.50], EntityZombie['Zombie'/6399, l='MpServer', x=-291.50, y=48.00, z=107.50], EntitySkeleton['Skeleton'/4389, l='MpServer', x=-245.50, y=38.00, z=134.50], EntitySkeleton['Skeleton'/4390, l='MpServer', x=-246.50, y=38.00, z=133.50], EntitySkeleton['Skeleton'/4394, l='MpServer', x=-153.50, y=34.00, z=69.50], EntityZombie['Zombie'/6522, l='MpServer', x=-217.50, y=86.00, z=88.50], EntitySkeleton['Skeleton'/6570, l='MpServer', x=-277.50, y=48.00, z=102.50], EntitySquid['Squid'/8638, l='MpServer', x=-193.50, y=48.00, z=81.50], EntitySquid['Squid'/8639, l='MpServer', x=-195.50, y=47.00, z=84.50], EntitySquid['Squid'/8640, l='MpServer', x=-195.50, y=47.00, z=84.50], EntitySquid['Squid'/8641, l='MpServer', x=-197.50, y=48.00, z=82.50], EntityBat['Bat'/6632, l='MpServer', x=-256.29, y=32.60, z=10.47], EntityZombie['Zombie'/4620, l='MpServer', x=-283.50, y=46.00, z=101.50], EntityCreeper['Creeper'/6671, l='MpServer', x=-295.50, y=41.00, z=146.50], EntityBat['Bat'/6692, l='MpServer', x=-246.35, y=37.74, z=14.19], EntityBat['Bat'/2793, l='MpServer', x=-274.83, y=19.13, z=101.45], EntityBat['Bat'/2795, l='MpServer', x=-277.85, y=20.32, z=102.49], EntitySpider['Spider'/2916, l='MpServer', x=-193.50, y=14.00, z=126.50], EntityZombie['Zombie'/7015, l='MpServer', x=-263.50, y=46.00, z=107.50], EntityZombie['Zombie'/7016, l='MpServer', x=-266.50, y=46.00, z=107.50], EntityZombie['Zombie'/7017, l='MpServer', x=-263.50, y=46.00, z=106.50], EntitySpider['Spider'/7018, l='MpServer', x=-265.50, y=46.00, z=106.50], EntitySkeleton['Skeleton'/4984, l='MpServer', x=-289.21, y=74.00, z=112.50], EntitySkeleton['Skeleton'/4985, l='MpServer', x=-284.50, y=72.00, z=114.50], EntitySkeleton['Skeleton'/5018, l='MpServer', x=-297.50, y=41.00, z=139.50], EntityHuman['direwolf20'/5112, l='MpServer', x=-304.50, y=41.00, z=143.50], EntityBat['Bat'/3098, l='MpServer', x=-281.50, y=48.70, z=109.56], EntityHuman['DrummingFish'/5187, l='MpServer', x=-128.50, y=54.00, z=83.50], EntityHuman['SethBling'/5189, l='MpServer', x=-126.70, y=54.00, z=86.16], EntityHuman['sct'/5190, l='MpServer', x=-134.26, y=51.00, z=77.40], EntityZombie['Zombie'/7264, l='MpServer', x=-282.45, y=21.00, z=98.75], EntityZombie['Zombie'/7266, l='MpServer', x=-281.30, y=19.00, z=105.31], EntityZombie['Zombie'/7267, l='MpServer', x=-276.65, y=19.00, z=101.35], EntityZombie['Zombie'/5244, l='MpServer', x=-266.50, y=47.00, z=23.50], EntityZombie['Zombie'/5245, l='MpServer', x=-263.76, y=49.00, z=23.50], EntitySkeleton['Skeleton'/3215, l='MpServer', x=-218.50, y=64.00, z=39.50], EntityZombie['entity.Zombie.name'/7326, l='MpServer', x=-205.50, y=14.00, z=101.50], EntityZombie['Zombie'/7327, l='MpServer', x=-204.50, y=14.00, z=102.50], EntityBat['Bat'/3298, l='MpServer', x=-280.95, y=20.83, z=105.17], EntityZombie['Zombie'/5358, l='MpServer', x=-282.50, y=46.00, z=96.50], EntityPlayerSP['Teeto_K'/903, l='MpServer', x=-229.80, y=101.00, z=84.86], EntityHuman['Vswe'/5519, l='MpServer', x=-295.50, y=18.00, z=76.50], EntitySkeleton['Skeleton'/5560, l='MpServer', x=-284.50, y=17.00, z=92.50], EntitySkeleton['Skeleton'/7650, l='MpServer', x=-246.50, y=17.00, z=70.50], EntityCreeper['Creeper'/5658, l='MpServer', x=-288.50, y=47.00, z=112.50], EntityHuman['Arkas'/7718, l='MpServer', x=-251.50, y=26.00, z=122.50], EntitySquid['Squid'/5706, l='MpServer', x=-252.40, y=56.71, z=90.60], EntityHuman['Bopogamel'/7791, l='MpServer', x=-220.50, y=64.00, z=36.50], EntityHuman['Reika'/7792, l='MpServer', x=-218.50, y=64.00, z=36.50], EntitySkeleton['Skeleton'/7793, l='MpServer', x=-217.50, y=64.00, z=38.50], EntityZombie['Zombie'/5826, l='MpServer', x=-298.80, y=78.00, z=156.49], EntitySkeleton['Skeleton'/5828, l='MpServer', x=-299.50, y=77.00, z=154.50], EntitySkeleton['Skeleton'/5846, l='MpServer', x=-251.50, y=22.00, z=130.50], EntityCreeper['Creeper'/5847, l='MpServer', x=-253.50, y=22.00, z=130.50], EntityZombie['Zombie'/5931, l='MpServer', x=-255.65, y=21.00, z=99.35], EntitySkeleton['Skeleton'/5943, l='MpServer', x=-205.50, y=14.00, z=101.50], EntityCreeper['Creeper'/5945, l='MpServer', x=-295.50, y=18.00, z=82.50], EntityCreeper['Creeper'/5946, l='MpServer', x=-295.50, y=18.00, z=87.50], EntitySkeleton['Skeleton'/5985, l='MpServer', x=-304.50, y=41.00, z=130.50], EntityCreeper['Creeper'/5986, l='MpServer', x=-303.50, y=41.00, z=129.50], EntityEnderman['Enderman'/1954, l='MpServer', x=-275.50, y=27.00, z=16.50], EntityEnderman['Enderman'/1969, l='MpServer', x=-275.42, y=27.00, z=17.52], EntityCreeper['Creeper'/6074, l='MpServer', x=-296.50, y=33.00, z=144.50], EntityCreeper['Creeper'/6075, l='MpServer', x=-296.50, y=33.00, z=143.50], EntityHuman['SOTMead'/8123, l='MpServer', x=-239.50, y=49.00, z=200.50], EntityHuman['boni'/8124, l='MpServer', x=-238.50, y=49.00, z=198.50], EntitySquid['Squid'/8141, l='MpServer', x=-264.40, y=49.00, z=87.49], EntitySkeleton['Skeleton'/6142, l='MpServer', x=-282.50, y=18.00, z=92.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1944295824 bytes (1854 MB) / 2618818560 bytes (2497 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2297 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2297.jar) 
	UCHIJAAAA	Forge{12.18.3.2297} [Minecraft Forge] (forge-1.10.2-12.18.3.2297.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.9.267} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.267-universal.jar) 
	UCHIJAAAA	brandonscore{2.1.8} [Brandon's Core] (BrandonsCore-1.10.2-2.1.8.107-universal.jar) 
	UCHIJAAAA	draconicevolution{2.1.0} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.0.232-universal.jar) 
	UCHIJAAAA	headcrumbs{2.0.2} [Headcrumbs] (Headcrumbs-2.0.3.jar) 
	UCHIJAAAA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJAAAA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	Loaded coremods (and transformers): 
Brandon's Core (BrandonsCore-1.10.2-2.1.8.107-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.267-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.3.0' Renderer: 'GeForce GTX 560/PCIe/SSE2'
	CodeChickenLib Invalid Fingerprint Reports: 
	Launched Version: forge-12.18.3.2297
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 560/PCIe/SSE2 GL version 4.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4170 Quad-Core Processor 
```

**Comment by brandon3055** [comment]
This sounds like an issue with Headcrumbs but i will add a try/catch to fix the problem from my end.
