### ISSUE TITLE
Packet Failure with Flux Gate (1.12)

### ISSUE THREAD

**Issue by NaleshSA** [brandon3055/Draconic-Evolution#843]
## Description

Unable to change the Flux Gates RF limiters away from 0 due to the packet being lost.

If you need further information, feel free to jump on the discord in said link, or PM Nalesh in #DraconicEvolution on espernet

## Base information
* Minecraft version: 1.12
* Minecraft Forge version: 1.12-14.21.1.2413
* Mod Pack: https://minecraft.curseforge.com/projects/grimdarker

## Log
```
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: java.lang.UnsupportedOperationException: direct buffer
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at io.netty.buffer.UnpooledUnsafeDirectByteBuf.array(UnpooledUnsafeDirectByteBuf.java:200)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at codechicken.lib.packet.PacketCustom.readArray(PacketCustom.java:620)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at codechicken.lib.data.MCDataUtils.readString(MCDataUtils.java:76)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at codechicken.lib.data.MCDataInput.readString(MCDataInput.java:49)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at com.brandon3055.draconicevolution.blocks.tileentity.flowgate.TileFlowGate.receivePacketFromClient(TileFlowGate.java:82)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at com.brandon3055.brandonscore.network.ServerPacketHandler.handlePacket(ServerPacketHandler.java:21)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.handle(PacketCustom.java:134)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at codechicken.lib.packet.PacketCustom$ServerInboundHandler.lambda$handle$0(PacketCustom.java:132)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at codechicken.lib.packet.PacketCustom$ServerInboundHandler$$Lambda$1734/1904506502.run(Unknown Source)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
[01:33:39] [Server thread/INFO]: [com.brandon3055.brandonscore.network.ServerPacketHandler:handlePacket:27]: 	at java.lang.Thread.run(Thread.java:745)
[01:33:40] [Server thread/ERROR]: Something went wrong while attempting to read a packet sent from this client: EntityPlayerMP['Nalesh'/556, l='New World', x=-189.23, y=124.24, z=-2.08]
```

**Comment by brandon3055** [comment]
If i recall correctly this is an issue with the CCL packet system that is currently being investigated.
