### ISSUE TITLE
[1.12-2.3.2.258] Extraneous error after world load on Dedicated Server

### ISSUE THREAD

**Issue by kreezxil** [brandon3055/Draconic-Evolution#859]
## Description
Extraneous error after world load on Dedicated Server

## Base information
* Minecraft version: 1.12
* Minecraft Forge version: 14.21.1.2428
* Mod Pack: Skyblock Godless (this is my public pack)

## Crash report
```
[14:16:53] [DE Contributors DL Thread/ERROR] [draconicevolution]: Failed to download contributors list
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]: java.net.ConnectException: Connection timed out (Connection timed out)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.net.PlainSocketImpl.socketConnect(Native Method)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.net.Socket.connect(Socket.java:589)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.net.Socket.connect(Socket.java:538)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1022)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection$6.run(HttpURLConnection.java:1020)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.security.AccessController.doPrivileged(Native Method)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1019)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection.access$200(HttpURLConnection.java:91)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1466)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection$9.run(HttpURLConnection.java:1464)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.security.AccessController.doPrivileged(Native Method)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.security.AccessController.doPrivilegedWithCombiner(AccessController.java:782)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1463)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at java.net.URL.openStream(URL.java:1045)
[14:16:53] [DE Contributors DL Thread/INFO] [STDERR]: [com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread:run:177]:         at com.brandon3055.draconicevolution.handlers.ContributorHandler$DLThread.run(ContributorHandler.java:165)

```

**Comment by brandon3055** [comment]
This suggests that your server does not have access to the internet or just can access brandon3055.com
