### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [brandon3055/Draconic-Evolution#862]
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2221
* Mod Pack:

## Crash report
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.8.jar)
  AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.1.21.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.339.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 8/3/17 12:37 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Clipboard (clipboard)
Caused by: java.lang.NoClassDefFoundError: kotlin/TypeCastException
	at net.shadowfacts.clipboard.Clipboard.<init>(Clipboard.kt:27)
	at net.shadowfacts.clipboard.Clipboard.<clinit>(Clipboard.kt:21)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:521)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:559)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:220)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: kotlin.TypeCastException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 940663400 bytes (897 MB) / 1510473728 bytes (1440 MB) up to 5965348864 bytes (5689 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6400m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2221 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2221.jar) 
	UC	Forge{12.18.3.2221} [Minecraft Forge] (forge-1.10.2-12.18.3.2221.jar) 
	UC	AdvancedRocketry{1} [Advanced Rocketry] (minecraft.jar) 
	UC	appliedenergistics2-core{rv4-alpha-11} [Applied Energistics 2 Core] (minecraft.jar) 
	UC	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UC	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UC	securitycraft{v1.8.2.3-hotfix} [SecurityCraft] ([1.10.2] SecurityCraft v1.8.2.3-hotfix.jar) 
	UC	actuallyadditions{1.10.2-r98} [Actually Additions] (ActuallyAdditions-1.10.2-r98.jar) 
	UC	libVulpes{0.2.5.} [libVulpes] (LibVulpes-1.10.2-0.2.5-universal.jar) 
	UC	advancedRocketry{1.10.2-1.0.8} [Advanced Rocketry] (AdvancedRocketry-1.10.2-1.0.8.jar) 
	UC	appliedenergistics2{rv4-alpha-11} [Applied Energistics 2] (appliedenergistics2-rv4-alpha-11.jar) 
	UC	bdlib{1.12.2.21} [BD Lib] (bdlib-1.12.2.21-mc1.10.2.jar) 
	UC	ae2stuff{0.6.0.7} [AE2 Stuff] (ae2stuff-0.6.0.7-mc1.10.2.jar) 
	UC	Baubles{1.3.9} [Baubles] (Baubles-1.10.2-1.3.9.jar) 
	UC	Botania{r1.9-340} [Botania] (Botania r1.9-340.jar) 
	UC	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UC	AppleCore{2.1.0} [AppleCore] (AppleCore-mc1.10.2-2.1.0.jar) 
	UC	appleskin{1.0.5} [AppleSkin] (AppleSkin-mc1.10.2-1.0.5.jar) 
	UC	thedragonlib{1.10.2-1.0.3.0} [TheDragonLib] (thedragonlib-1.10.2-1.0.3.0.jar) 
	UC	armorplus{1.10.2-8.3.0.1} [ArmorPlus] (armorplus-1.10.2-8.3.0.1.jar) 
	UC	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UC	AromaBackup{2.0.0.0.b62} [AromaBackup] (AromaBackup-1.9.4-2.0.0.0.b62.jar) 
	UC	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-2.0.0.0.b62.jar) 
	UC	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UC	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UC	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UC	baconators{3.0.6} [Baconators] (baconators-1.10.2-3.0.6.jar) 
	UC	baublesstuff{3.0.2} [Baubles Stuff] (baublesstuff-3.0.2.jar) 
	UC	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	UC	betterbuilderswands{0.11.0} [Better Builder's Wands] (BetterBuildersWands-1.10.2-0.11.0.215+2d66774.jar) 
	UC	BiblioCraft{2.2.5} [BiblioCraft] (BiblioCraft[v2.2.5][MC1.10.2].jar) 
	UC	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UC	BloodMagic{1.10.2-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.11-80.jar) 
	UC	bookshelf{1.4.3.339} [Bookshelf] (Bookshelf-1.10.2-1.4.3.339.jar) 
	UC	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.10.2.jar) 
	UC	chancecubes{1.10.2-2.3.4.171} [Chance Cubes] (ChanceCubes-1.10.2-2.3.4.171.jar) 
	UC	ChestTransporter{2.5.17} [Chest Transporter] (ChestTransporter-1.10.2-2.5.17.jar) 
	UC	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UC	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UC	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UC	chickens{4.3.2} [Chickens] (chickens-4.3.2.jar) 
	UC	chisel{MC1.10.2-0.0.13.28} [Chisel] (Chisel-MC1.10.2-0.0.13.28.jar) 
	UC	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UE	clipboard{@VERSION@} [Clipboard] (Clipboard-1.10.2-1.1.1.jar) 
	UC	ctm{MC1.10.2-0.2.1.21} [CTM] (CTM-MC1.10.2-0.2.1.21.jar) 
	UC	cyclopscore{0.10.6} [Cyclops Core] (CyclopsCore-1.9.4-0.10.6.jar) 
	UC	darkutils{1.1.6.105} [Dark Utilities] (DarkUtilities-1.10.2-1.1.6.105.jar) 
	UC	deathquotes{1.2.0} [Death Quotes] (DeathQuotes-1.2.0-mc1.9to1.10.2-forge.jar) 
	UC	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.3.6.1_1.10.2.jar) 
	UC	props{2.3.6.1} [Decocraft] (Decocraft-2.3.6.1_1.10.2.jar) 
	UC	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod[V.1.3.0][MC.1.10.2].jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
AppleCore (AppleCore-mc1.10.2-2.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
AdvancedRocketryPlugin (AdvancedRocketry-1.10.2-1.0.8.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
AppEngCore (appliedenergistics2-rv4-alpha-11.jar)
  appeng.coremod.transformer.ASMIntegration
CTMCorePlugin (CTM-MC1.10.2-0.2.1.21.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.3.339.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.53' Renderer: 'GeForce GTX TITAN X/PCIe/SSE2'
	AE2 Version: alpha rv4-alpha-11 for Forge 12.18.3.2185

```

**Comment by covers1624** [comment]
What? this isnt even DE, this is shadowfacts's stuff. You need Forgelin.
