### ISSUE TITLE
RFTools Dynamic Shield + Draconic Evolution Arrows = Crash

### ISSUE THREAD

**Issue by SirWilli** [brandon3055/Draconic-Evolution#90]
Shooting with the bow from Draconic Evolution in to the shield crashes the client or server.

Crash Report:
```
java.lang.ClassCastException: TileMultipart_cmp$$26 cannot be cast to com.mcjty.rftools.blocks.shield.ShieldBlockTileEntity
at com.mcjty.rftools.blocks.shield.AbstractShieldBlock.func_149670_a(AbstractShieldBlock.java:157)
at com.brandon3055.draconicevolution.common.entity.EntityDraconicArrow.func_70071_h_(EntityDraconicArrow.java:319)
at net.minecraft.world.World.func_72866_a(World.java:2647)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
at net.minecraft.world.World.func_72870_g(World.java:2600)
at net.minecraft.world.World.func_72939_s(World.java:2412)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
----------------------------------------------------------------------------------------- Head --
Stacktrace:
at com.mcjty.rftools.blocks.shield.AbstractShieldBlock.func_149670_a(AbstractShieldBlock.java:157)
at com.brandon3055.draconicevolution.common.entity.EntityDraconicArrow.func_70071_h_(EntityDraconicArrow.java:319)
at net.minecraft.world.World.func_72866_a(World.java:2647)
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
at net.minecraft.world.World.func_72870_g(World.java:2600)-- Entity being ticked --
Details:
Entity Type: DraconicEvolution.Arrow (com.brandon3055.draconicevolution.common.entity.EntityDraconicArrow)
Entity ID: 34894
Entity Name: entity.DraconicEvolution.Arrow.name
Entity's Exact location: -1554.00, 69.65, -2837.47
Entity's Block location: World: (-1554,69,-2838), Chunk: (at 14,4,10 in -98,-178; contains blocks -1568,0,-2848 to -1553,255,-2833), Region: (-4,-6; contains chunks -128,-192 to -97,-161, blocks -2048,0,-3072 to -1537,255,-2561)
Entity's Momentum: -0.00, -0.35, 0.00
Stacktrace:
at net.minecraft.world.World.func_72939_s(World.java:2412)
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)-- Affected level --
Details:
Level name: world
All players: 1 total; [EntityPlayerMP['MrWisski'/6549, l='world', x=-1553.50, y=69.22, z=-2839.50](MrWisski at -1553.5,69.21599998474119,-2839.5)]
Chunk stats: ServerChunkCache: 1042 Drop: 0
Level seed: -6809526006874371365
Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
Level generator options:
Level spawn location: World: (0,115,32), Chunk: (at 0,7,0 in 0,2; contains blocks 0,0,32 to 15,255,47), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
Level time: 96341957 game time, 1081869 day time
Level dimension: 0
Level storage version: 0x04ABD - Anvil
Level weather: Rain time: 70136 (now: false), thunder time: 79874 (now: false)
Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by McJty** [comment]
Seems to be a combination bug. RFTools is not checking in its onEntityCollidedWithBlock() if the passed x,y,z coordinate is actually the tile entity that I expect (I just cast). However I wonder why the x,y,z is not the correct position in the first place? The x,y,z that my function gets seems to be another location in the world (probably near where the shield block is).

**Comment by McJty** [comment]
Related to: https://github.com/McJty/RFTools/issues/173

**Comment by brandon3055** [comment]
Fixed in bugfix c
