### ISSUE TITLE
Please help with crash.

### ISSUE THREAD

**Issue by wickeli** [brandon3055/Draconic-Evolution#909]
## Description
Just keep crashing.
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2477
* Mod Pack: Custom one
Animania
Applied Energistics 2
Bad Wither, No Cookie!
Bed Bugs
Biomes O'Plenty
Botania
Chisel
Chisels and Bits
Cooking for Blockheads
Cosmetic Armor Mod
Custom NPCs
Davinci's Vessels
Decocraft
Doggy Talents
Draconic Evolution
Ender IO
Ender Zoo
Fast Leaf Decay
Flux Networks
Forestry
Good Ol' Currency Mod
Pam's HarvestCraft
Immersive Engineering
Inventory Pets
Inventory Tweaks
Journeymap
JustEnoughItems
Mekanism
Multipage Chest
Practical Logistics 2
Props Mod
RFTools
Sleeping Bag
Solar Flux Reborn
Storage Drawers
Tinkers Construct
Ultimate Unicorn Mod
Vein Miner
Wearable Backpacks
## Crash report
``` crash-2017-09-17_17.32.23-client.txt
CRASH REPORT HERE
```---- Minecraft Crash Report ----

WARNING: coremods are present:
  MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  CTMCorePlugin (CTM-MC1.10.2-0.2.2.24.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.12.130-universal (1).jar)
  SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.4.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 9/17/17 5:32 PM
Description: Initializing game

java.lang.OutOfMemoryError: Java heap space
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:221)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:549)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:193)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.client.model.pipeline.UnpackedBakedQuad$Builder.<init>(UnpackedBakedQuad.java:112)
	at net.minecraftforge.client.model.ItemLayerModel.buildQuad(ItemLayerModel.java:369)
	at net.minecraftforge.client.model.ItemLayerModel.buildSideQuad(ItemLayerModel.java:353)
	at net.minecraftforge.client.model.ItemLayerModel.addSideQuad(ItemLayerModel.java:278)
	at net.minecraftforge.client.model.ItemLayerModel.getQuadsForSprite(ItemLayerModel.java:221)
	at net.minecraftforge.client.model.ItemLayerModel.bake(ItemLayerModel.java:126)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:549)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:193)
	at net.minecraft.client.renderer.block.model.ModelManager.func_110549_a(ModelManager.java:28)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:132)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:113)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:755)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:350)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.8.0_74, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 364103504 bytes (347 MB) / 2134114304 bytes (2035 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 5 total; -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.3.2477 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2477.jar) 
	UCHIJA	Forge{12.18.3.2477} [Minecraft Forge] (forge-1.10.2-12.18.3.2477.jar) 
	UCHIJA	appliedenergistics2-core{rv4-stable-1} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJA	io.github.elytra.movingworld.common.asm.coremod{} [MovingWorld CORE] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJA	animania{1.2.2} [Animania] (animania-1.10.2-1.2.2.jar) 
	UCHIJA	appliedenergistics2{rv4-stable-1} [Applied Energistics 2] (appliedenergistics2-rv4-stable-1.jar) 
	UCHIJA	badwithernocookiereloaded{1.10.2-1.10} [Bad Wither No Cookie! Reloaded] (badwithernocookiereloaded-1.10.2-1.10.jar) 
	UCHIJA	Baubles{1.3.11} [Baubles] (Baubles-1.10.2-1.3.11.jar) 
	UCHIJA	bedbugs{@VERSION@} [Bed Bugs] (BedBugs-1.10.2-1.1.6.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2290} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2290-universal.jar) 
	UCHIJA	Botania{r1.9-341} [Botania] (Botania r1.9-341.jar) 
	UCHIJA	CodeChickenLib{2.5.9.283} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.9.283-universal.jar) 
	UCHIJA	brandonscore{2.1.12} [Brandon's Core] (BrandonsCore-1.10.2-2.1.12.130-universal (1).jar) 
	UCHIJA	Chameleon{1.10.2-2.3.0} [Chameleon] (Chameleon-1.10.2-2.3.0.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.14.33} [Chisel] (Chisel-MC1.10.2-0.0.14.33.jar) 
	UCHIJA	JEI{3.14.7.420} [Just Enough Items] (jei_1.10.2-3.14.7.420.jar) 
	UCHIJA	mcmultipart{1.4.0} [MCMultiPart] (MCMultiPart-1.4.0-universal.jar) 
	UCHIJA	chiselsandbits{12.15} [Chisels & Bits] (chiselsandbits-12.15.jar) 
	UCHIJA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJA	cookingforblockheads{4.2.45} [Cooking for Blockheads] (CookingForBlockheads_1.10.2-4.2.45.jar) 
	UCHIJA	cosmeticarmorreworked{1.10.2-v2a} [CosmeticArmorReworked] (CosmeticArmorReworked-1.10.2-v2a.jar) 
	UCHIJA	ctm{MC1.10.2-0.2.2.24} [CTM] (CTM-MC1.10.2-0.2.2.24.jar) 
	UCHIJA	modcurrency{1.10.2-1.2.0} [Good Ol' Currency Mod] (Currency-1.10.2-1.2.0.jar) 
	UCHIJA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(21jul17).jar) 
	UCHIJA	cxlibrary{1.2.4} [CXLibrary] (cxlibrary-1.10.2-1.2.4.jar) 
	UCHIJA	movingworld{1.10.2-0007} [Moving World] (movingworld-1.10.2-0007-full.jar) 
	UCHIJA	davincisvessels{@DVESSELSVER@} [Davinci's Vessels] (davincisvessels-1.10.2-0006-full.jar) 
	UCHIJA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.10.2.jar) 
	UCHIJA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.10.2.jar) 
	UCHIJA	doggytalents{1.14.2.298} [Doggy Talents] (DoggyTalents-1.10.2-1.14.2.298-universal.jar) 
	UCHIJA	draconicevolution{2.1.6} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.1.6.263-universal.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.66-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.66-beta.jar) 
	UCHIJA	EnderIO{1.10.2-3.1.183} [Ender IO] (EnderIO-1.10.2-3.1.183.jar) 
	UCHIJA	EnderZoo{1.10-1.2.3.44} [Ender Zoo] (EnderZoo-1.10-1.2.3.44.jar) 
	UCHIJA	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJA	sonarcore{3.3.0} [SonarCore] (SonarCore-1.10.2-3.3.0.jar) 
	UCHIJA	fluxnetworks{1.2.8} [FluxNetworks] (FluxNetworks-1.10.2-1.2.8.jar) 
	UCHIJA	forestry{5.2.17.388} [Forestry] (forestry_1.10.2-5.2.17.388.jar) 
	UCHIJA	hammercore{1.9.4.3} [Hammer Core] (HammerCore-1.10.2-1.9.4.3.jar) 
	UCHIJA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJA	tconstruct{1.10.2-2.6.5.10} [Tinkers' Construct] (TConstruct-1.10.2-2.6.5.jar) 
	UCHIJA	immersiveengineering{0.10-61} [Immersive Engineering] (ImmersiveEngineering-0.10-61.jar) 
	UCHIJA	InventoryPets{1.4.9.6} [Inventory Pets] (inventorypets-1.10-1.4.9.6.jar) 
	UCHIJA	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UCHIJA	journeymap{1.10.2-5.5.0b4} [JourneyMap] (journeymap-1.10.2-5.5.0b4.jar) 
	UCHIJA	Mekanism{9.2.4} [Mekanism] (Mekanism-1.10.2-9.2.4.103.jar) 
	UCHIJA	MultiPageChest{1.7.3} [Multi Page Chest] (MultiPageChest-1.10.2-1.7.3.jar) 
	UCHIJA	harvestcraft{1.10.2j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.10.2j.jar) 
	UCHIJA	practicallogistics2{2.0.2} [Practical Logistics 2] (PracticalLogistics2-1.10.2-2.0.2.jar) 
	UCHIJA	rftools{5.62} [RFTools] (rftools-1.10-5.62.jar) 
	UCHIJA	shadowmc{3.6.1} [ShadowMC] (ShadowMC-1.10.2-3.6.1.jar) 
	UCHIJA	SleepingBag{1.4.0} [Sleeping Bag] (SleepingBag-1.10.2-1.4.0.jar) 
	UCHIJA	solarfluxreborn{2.17r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-2.17r.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.7.10} [Storage Drawers] (StorageDrawers-1.10.2-3.7.10.jar) 
	UCHIJA	ultimate_unicorn_mod{1.5.12} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!] (ultimate_unicorn_mod-1.10.2-1.5.13.jar) 
	UCHIJA	VeinMiner{0.38.1_1.9-5587fc8} [Vein Miner] (VeinMiner-1.9-0.38.1.618+5587fc8.jar) 
	UCHIJA	VeinMinerModSupport{0.38.1_1.9-5587fc8} [Mod Support] (VeinMiner-1.9-0.38.1.618+5587fc8.jar) 
	UCHIJA	wearablebackpacks{1.7.0} [Wearable Backpacks] (WearableBackpacks-1.10.2-1.7.0.jar) 
	Loaded coremods (and transformers): 
MovingWorldCoreMod (movingworld-1.10.2-0007-full.jar)
  
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.9.283-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
CTMCorePlugin (CTM-MC1.10.2-0.2.2.24.jar)
  team.chisel.ctm.client.asm.CTMTransformer
Brandon's Core (BrandonsCore-1.10.2-2.1.12.130-universal (1).jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
SFRCore (SolarFluxReborn_1.10.2-2.17r.jar)
  com.mrdimka.solarfluxreborn.core.SFRSerializedTransformer
HammerCoreCore (HammerCore-1.10.2-1.9.4.3.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.66-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
AppEngLoadingPlugin (appliedenergistics2-rv4-stable-1.jar)
  appeng.coremod.transformer.IntegrationTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.4.jar)
  cubex2.cxlibrary.CoreModTransformer
	AE2 Version: stable rv4-stable-1 for Forge 12.18.3.2185
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                  * The RF API that is being used (1.5.0 from (guessing) null) differes from that that is reported as being loaded (1.8.9R1.2.0B1 from SonarCore-1.10.2-3.3.0.jar).
                    It is a supported version, but that difference may lead to problems.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/Users/LeighAnn/Library/Application%20Support/minecraft/Shot%20Pack/mods/BrandonsCore-1.10.2-2.1.12.130-universal%20(1).jar!/cofh/api/energy/TileEnergyHandler.class
	Detailed Tesla API diagnostics:
                  * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
                  * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
                  * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
                  * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
                  * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
                  * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
                  * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
                  * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
                  * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
                  * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
                  * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash. Scroll up!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:OFF, RF:ON, RFItem:ON, Waila:OFF, JEI:ON, THE_ONE_PROBE:OFF
	Launched Version: 1.10.2-forge1.10.2-12.18.3.2477
	LWJGL: 2.9.2
	OpenGL: ATI Radeon HD 4670 OpenGL Engine GL version 2.1 ATI-10.0.35, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3 CPU 540 @ 3.07GHz

**Comment by covers1624** [comment]
`java.lang.OutOfMemoryError: Java heap space` 
Allocate more ram.

**Comment by wickeli** [comment]
Thx
