### ISSUE TITLE
[1.12.2] Client crash upon respawn

### ISSUE THREAD

**Issue by DeadSix27** [brandon3055/Draconic-Evolution#943]
## Description
Client crashes upon respawning.

## Base information
* Minecraft version: Draconic-Evolution-1.12-2.3.4.265-universal
* Minecraft Forge version: forge-14.23.0.2512

## Crash report 
Full log can be found here: https://gist.github.com/DeadSix27/797b6c12df9aaab6a63362e0e58382c2
```
Description: Tesselating block model

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[down, up, north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at com.brandon3055.draconicevolution.blocks.tileentity.TilePlacedItem.calculateBounds(TilePlacedItem.java:94)
	at com.brandon3055.draconicevolution.blocks.tileentity.TilePlacedItem.getIndexedCuboids(TilePlacedItem.java:165)
	at com.brandon3055.draconicevolution.blocks.PlacedItem.func_185496_a(PlacedItem.java:140)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185900_c(BlockStateContainer.java:456)
	at net.minecraft.block.Block.func_176225_a(Block.java:396)
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_185894_c(BlockStateContainer.java:435)
	at team.chisel.ctm.client.util.CTMLogic.isConnected(CTMLogic.java:365)
	at team.chisel.ctm.client.util.Dir.isConnected(Dir.java:84)
	at team.chisel.ctm.client.util.CTMLogic.buildConnectionMap(CTMLogic.java:215)
	at team.chisel.ctm.client.util.CTMLogic.createSubmapIndices(CTMLogic.java:161)
	at team.chisel.ctm.client.texture.ctx.TextureContextCTM.<init>(TextureContextCTM.java:29)
	at team.chisel.ctm.client.texture.type.TextureTypeCTM.getBlockRenderContext(TextureTypeCTM.java:24)
	at team.chisel.ctm.client.texture.type.TextureTypeCTM.getBlockRenderContext(TextureTypeCTM.java:14)
	at team.chisel.ctm.api.util.RenderContextList.<init>(RenderContextList.java:36)
	at team.chisel.ctm.client.state.ChiselExtendedState.getContextList(ChiselExtendedState.java:73)
	at team.chisel.ctm.client.model.AbstractCTMBakedModel.func_188616_a(AbstractCTMBakedModel.java:204)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.render(ForgeBlockModelRenderer.java:117)
	at net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer.func_187498_b(ForgeBlockModelRenderer.java:103)
	at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:47)
	at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:38)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:80)
	at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)
	at com.elytradev.architecture.base.BaseAORenderingManager$CustomBlockRendererDispatcher.func_175018_a(BaseAORenderingManager.java:89)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:200)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by brandon3055** [comment]
This should be fixed in the next release.

**Comment by DeadSix27** [comment]
@brandon3055 thanks :)
