### ISSUE TITLE
Server SkyFactory Crash [1.10.2]

### ISSUE THREAD

**Issue by HeberonYT** [brandon3055/Draconic-Evolution#945]
## Description
I'm having the same report over and over again.
We have detected that by having a draconic flux capacitor in inventory and approaching fairylights mod lights, the server crashes.

## Base information
* Minecraft version: spongeforge-1.10.2-2477-5.2.0-BETA-2691.jar
* Minecraft Forge version: Forge 12.18.3.2422
* Mod Pack: Sky Factory 3 (v3.0.15)

## Crash report
```
CRASH REPORT HERE
[https://pastebin.com/raw/GWY22Kxq](url)

**Comment by brandon3055** [comment]
I think you are a little off as to the cause of the crash. I suspect you you are also approaching an energy core when the crash occurs? 
This crash is caused by a flux point most likely attached to an energy pylon. This is a known issue caused by flux networks but it will also be fixed from my side in the next DE update.

**Comment by HeberonYT** [comment]
I have no idea what he's talking about.
The server is empty and it was just decorating the spawn of a new server, there is nothing developed from its mod.
I bring with me an armor and the capacitor of your mod, but only that.
When I placed the lights for decoration, it crashed, so I went back to do some careful testing and that's how I discovered it.

**Comment by covers1624** [comment]
Uhh, Unless you have given the wrong crash report, there is Indeed a energy pylon and flux points placed in your world, the crash doesn't say where, but they absolutely exist in your world somewhere.

**Comment by HeberonYT** [comment]
You're right, I'm sorry for the confusion.
Someone from the staff already has some things placed in the world.
But now I have a doubt, there are no chunks loaders, how come that island is loading in the memory if there was nobody in it and is very far from the spawn?
Do these blocks load the chunks?

**Comment by covers1624** [comment]
Fluxes networks must be caching it's grid across loads and not checking if the chunk is loaded, causing a crash because DE's tile isn't in the correct state.

**Comment by SubtypeZero** [comment]
I have the same issue, but I don't think it has to do with flux capacitors. I've been having the same crash over and over for the past week, several times per day, and I haven't been able to reproduce it.

```
java.lang.NullPointerException: Exception in server tick loop
	at com.brandon3055.draconicevolution.blocks.tileentity.TileEnergyPylon.getEnergyStored(TileEnergyPylon.java:372)
	at com.brandon3055.brandonscore.lib.EnergyHandlerWrapper.getEnergyStored(EnergyHandlerWrapper.java:41)
	at sonar.core.energy.GenericForgeEnergyHandler.removeEnergy(GenericForgeEnergyHandler.java:41)
	at sonar.core.handlers.energy.ForgeEnergyHandler.removeEnergy(ForgeEnergyHandler.java:32)
	at sonar.core.helpers.EnergyHelper.performExtract(EnergyHelper.java:57)
	at sonar.core.helpers.EnergyHelper.extractEnergy(EnergyHelper.java:48)
	at sonar.flux.connection.FluxHelper.pullEnergy(FluxHelper.java:151)
	at sonar.flux.connection.BasicFluxNetwork.lambda$updateNetwork$3(BasicFluxNetwork.java:143)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at sonar.flux.connection.BasicFluxNetwork.updateNetwork(BasicFluxNetwork.java:143)
	at sonar.flux.FluxEvents.onServerTick(FluxEvents.java:35)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_736_FluxEvents_onServerTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:632)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:588)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:602)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by gigabit101** [comment]
Version no longer supported.
